### ISSUE TITLE
`System.MissingMethodException` when using with .NET 7 and calling `.BatchDeleteAsync()`

### ISSUE THREAD

**Issue by benm-eras** [borisdj/EFCore.BulkExtensions#1011]
Just upgraded my project to .NET 7 and am immediately getting exceptions when trying to call `BatchDeleteAsync` or `BatchUpdateAsync`. `BulkInsertAsync` seems to be fine, but I haven't tried any other methods. This is the full exception:

> System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Storage.IRelationalCommand Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GetCommand(Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression)'.
   at EFCore.BulkExtensions.IQueryableExtensions.ToParametrizedSql(IQueryable query)
   at EFCore.BulkExtensions.BatchUtil.GetBatchSql(IQueryable query, DbContext context, Boolean isUpdate)
   at EFCore.BulkExtensions.BatchUtil.GetSqlDelete(IQueryable query, DbContext context)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.GetBatchDeleteArguments(IQueryable query)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchDeleteAsync(IQueryable query, CancellationToken cancellationToken)
   at EFCoreDemo.Program.Main(String[] args) in C:\Users\BenMiller\Downloads\EFCoreDemo\Program.cs:line 34
   at EFCoreDemo.Program.<Main&gt;(String[] args)

I have created a minimal reproduction here: https://github.com/benm-eras/EFCore.BulkExtensions-Demo

**Comment by halllo** [comment]
I have the same problem. This is my query:

`dbContext.HandledMessages.Where(m => m.Handled < expirationDate).BatchDelete();`

**Comment by borisdj** [comment]
DUPE: https://github.com/borisdj/EFCore.BulkExtensions/issues/993
