### ISSUE TITLE
BatchUpdate fail: NullReferenceException

### ISSUE THREAD

**Issue by leehom0123** [borisdj/EFCore.BulkExtensions#103]
My code like this:

```
    public enum FeeStatus
    {
        NotCloseAccount,
        LuNotEstablish,
        NotTransfer,
        Transfered
    }
```

```Fee.cs
    public partial class Fee 
    {
.....
        public virtual FeeStatus Status { get; set; }

        public virtual Guid? CloseAccountId { get; set; } 

        public virtual DateTime? BusinessDate { get; set; } 
.....

    }
```

And when I use BatchUpdateAsync:

```
await context.Fees.Where(x =>
    x.BusinessDate >= ca.StartDate
    && x.BusinessDate <= ca.EndDate
    )
    .BatchUpdateAsync(new Fee
    {
        CloseAccountId = ca.Id,
        Status = FeeStatus.LuNotEstablish
    },
    new List<string> {
        nameof(Fee.CloseAccountId),
        nameof(Fee.Status)
    });
```
There is NullReferenceException:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at EFCore.BulkExtensions.BatchUtil.GetSqlSetSegment[T](DbContext context, T updateValues, List`1 updateColumns)
   at EFCore.BulkExtensions.BatchUtil.GetSqlUpdate[T](IQueryable`1 query, DbContext context, T updateValues, List`1 updateColumns)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchUpdateAsync[T](IQueryable`1 query, T updateValues, List`1 updateColumns)
   at Bit.Lu.Fp.CloseAccountAppService.CalcTransfer(EntityDto`1 input) in D:\Repos\aspnet-core\src\Bit.Lu.Application\Lu\Fp\CloseAccounts\CloseAccountAppService.cs:line 307
 ```

**Comment by borisdj** [comment]
Fixed, and NuGet 2.3.2 published.

**Comment by leehom0123** [comment]
This bug not from enum, like this:

```
    public class Address
    {
         public string Foo { get; set; }
         public string Bar { get; set; }
    }

    public partial class Fee 
    {
.....
        public Address Address { get; set; }

        public virtual FeeStatus Status { get; set; }

        public virtual Guid? CloseAccountId { get; set; } 

        public virtual DateTime? BusinessDate { get; set; } 
.....

    }
```

And in Map:

```

    public partial class FeeMap : IEntityTypeConfiguration<Fee>
    {


        public void Configure(EntityTypeBuilder<Fee> builder)
        {
            builder.OwnsOne(x => x.Address);
       }
    }
```

Then in BatchUtil.cs:
![image](https://user-images.githubusercontent.com/10956708/49057267-c52e3e80-f239-11e8-9709-da6d57c1624e.png)

Property is null.

**Comment by leehom0123** [comment]
```
        public static string GetSqlSetSegment<T>(DbContext context, T updateValues, List<string> updateColumns, List<SqlParameter> parameters) where T : class, new()
        {
            var tableInfo = TableInfo.CreateInstance<T>(context, new List<T>(), OperationType.Read, new BulkConfig());
            string sql = string.Empty;
            Type updateValuesType = typeof(T);
            var defaultValues = new T();
            foreach (var propertyNameColumnName in tableInfo.PropertyColumnNamesDict)
            {
                string propertyName = propertyNameColumnName.Key;
                string columnName = propertyNameColumnName.Value;
                var pArray = propertyName.Split(new char[] { '.' });
                Type lastType = updateValuesType;
                PropertyInfo property = lastType.GetProperty(pArray[0]);
                object propertyUpdateValue = property.GetValue(updateValues);
                object propertyDefaultValue = property.GetValue(defaultValues);
                for (int i = 1; i < pArray.Length; i++)
                {
                    lastType = property.PropertyType;
                    property = lastType.GetProperty(pArray[i]);
                    propertyUpdateValue = property.GetValue(propertyUpdateValue);
                    var lastDefaultValues = lastType.Assembly.CreateInstance(lastType.FullName);
                    propertyDefaultValue = property.GetValue(lastDefaultValues);
                }
         
                bool isDifferentFromDefault = propertyUpdateValue?.ToString() != propertyDefaultValue?.ToString();
                if (isDifferentFromDefault || (updateColumns != null && updateColumns.Contains(propertyName)))
                {
                    sql += $"[{columnName}] = @{columnName}, ";
                    parameters.Add(new SqlParameter($"@{columnName}", propertyUpdateValue));
                }
            }
            if (String.IsNullOrEmpty(sql))
            {
                throw new InvalidOperationException("SET Columns not defined. If one or more columns should be updated to theirs default value use 'updateColumns' argument.");
            }
            sql = sql.Remove(sql.Length - 2, 2); // removes last excess comma and space: ", "
            return $"SET {sql}";
        }
```

Code commited, thank you!

**Comment by borisdj** [comment]
You are welcome.
Pull Request merged, and small change made as fix for when owned type is null.
NuGet 2.3.3 published
