### ISSUE TITLE
BUG NullReferenceException 6.6.4 EFCore.BulkExtensions.SqlServer

### ISSUE THREAD

**Issue by sommmen** [borisdj/EFCore.BulkExtensions#1040]
Using .NET / EF 6.0.12 and EFCore.BulkExtensions.SqlServer 6.6.4:

``` csharp
// Entity
public class HangfireAppLog : AppLog
{ }

public class AppLog : IAppLog
{
    public int Id { get; set; }
    public string Message { get; set; }
    public string MessageTemplate { get; set; }
    public string Level { get; set; }
    public DateTime? TimeStamp { get; set; }
    public string Exception { get; set; }
    public string Properties { get; set; }
}

// Config
var bulkConfig = new BulkConfig
{
    // Should help cleaning up temp tables - see https://github.com/borisdj/EFCore.BulkExtensions/issues/202
    UseTempDB = true,

    PropertiesToExcludeOnUpdate = bulkMergeOptions
        .KeyProperties
        .Concat(bulkMergeOptions.ExcludeProperties)
        .ToList(),

    UpdateByProperties = bulkMergeOptions.CompareProperties,
    
    CalculateStats = true,
};

// Executing code
await context.BulkDeleteAsync(entities, bulkConfig, x => ReportProgress(x, bulkMergeOptions), cancellationToken: cancellationToken);
```

Sample entity (only IDs are set)
  | Name | Value | Type
-- | -- | -- | --
◢ | [0] | {[REDACTED].DAL.AppLogs.Entities.HangfireAppLog} | [REDACTED].DAL.AppLogs.Entities.HangfireAppLog
  | Exception | null | string
  | Id | 3771153 | int
  | Level | null | string
  | Message | null | string
  | MessageTemplate | null | string
  | Properties | null | string
  | TimeStamp | null | System.DateTime?

Exception:

``` 
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=EFCore.BulkExtensions.SqlServer
  StackTrace:
   at EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, Type type, IList`1 entities, Boolean loadOnlyPKColumn)
   at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
   at EFCore.BulkExtensions.DbContextBulkTransaction.<ExecuteAsync>d__1`1.MoveNext()
   at [REDACTED].DAL.Repositories.Bulk.Strategy.BulkMergeDeleteStrategy.<ExecuteAsync>d__3`1.MoveNext() in C:\Repos\dotnet-api\DAL\Repositories\Bulk\Strategy\BulkMergeDeleteStrategy.cs:line 22

  This exception was originally thrown at this call stack:
    [REDACTED].DAL.Repositories.Bulk.Strategy.BulkMergeDeleteStrategy.ExecuteAsync<T>(System.Collections.Generic.IList<T>, Microsoft.EntityFrameworkCore.DbContext, [REDACTED].DAL.Repositories.Bulk.BulkMergeIO.BulkMergeOptions, System.Threading.CancellationToken) in BulkMergeDeleteStrategy.cs
```

**Comment by edokan** [comment]
Hey @sommmen , I've just fixed that in #1039

**Comment by developer1323** [comment]
When this issue will be fix? Cause I have the same broblem

**Comment by sommmen** [comment]
> When this issue will be fix? Cause I have the same problem

When the dev has time. Just downgrade to 6.6.2 and stay on that for a while and you're good.

**Comment by developer1323** [comment]
ok, ok I've already did it, just asking

**Comment by Trapulo** [comment]
Same problem with every BulkInsert after upgrade to .NET 7.0

**Comment by borisdj** [comment]
v6.6.5
