### ISSUE TITLE
context.Items.Where(x => x.SomeString = searchValue).BatchUpdate(...) fails when searchValue contains curly braces

### ISSUE THREAD

**Issue by jaybz** [borisdj/EFCore.BulkExtensions#105]
Similar code to a prior issue I reported with square braces:
```
context.Items.Where(x => x.SomeString == searchValue).BatchUpdate(new Item { BooleanValue = true});
```

If searchValue contains { or } BatchUpdate will throw a System.FormatException. Stacktrace outside my app:

```
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RawSqlCommandBuilder.Build(String sql, IEnumerable`1 parameters)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters)
```
To verify that the problem likely lies with BatchUpdate I tried the following code and it works properly with curly braces:
```
var i = context.Items.Where(x => x.SomeString == searchValue).ToList();
```

**Comment by borisdj** [comment]
NuGet 2.3.4

**Comment by jaybz** [comment]
It's working properly now. Thanks.
