### ISSUE TITLE
Error - System.ArgumentOutOfRangeException: Length cannot be less than zero

### ISSUE THREAD

**Issue by avagarwal** [borisdj/EFCore.BulkExtensions#1050]
I am using MySQL and the following statement is giving an error

_dataContext.Attendance.Where(a => a.AttendanceId >= 1850).BatchDelete();

System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlServerDialect.GetBatchSqlReformatTableAliasAndTopStatement(String sqlQuery, DbServer databaseType)
   at EFCore.BulkExtensions.BatchUtil.GetBatchSql(IQueryable query, DbContext context, Boolean isUpdate)
   at EFCore.BulkExtensions.BatchUtil.GetSqlDelete(IQueryable query, DbContext context)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.GetBatchDeleteArguments(IQueryable query)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchDelete(IQueryable query)

Receiving the same error when using BatchUpdate.

Using version 6.5.6 with EFCore 6.0.12 and .Net 6

What may be reason?

**Comment by shubham4315** [comment]
Any Updates on this? I am facing the same problem when I execute BatchDelete(). I am using Mysql.

**Comment by avagarwal** [comment]
None, till now

**Comment by borisdj** [comment]
Batch ops will probably be deprecated since EF as of v7 now supports it natively with _ExecuteUpdate_ and _ExecuteDelete_.
Library focus in now on **Bulk** (CRUD + SaveCh.) methods.
So best to upgrade to EF7 and use _ExecuteDelete_.

**Comment by borisdj** [comment]
Fixed with latest v.
