### ISSUE TITLE
BatchDeleteAsync - Breaking Change When Upgrading Version

### ISSUE THREAD

**Issue by davidrjones77** [borisdj/EFCore.BulkExtensions#1056]
Hello - I am currently using **EFCore.BulkExtensions** 5.4.2 and **Microsoft.EntityFrameworkCore** 5.0.16.
I would like to update my packages but when I do, the following issue occurs.

Currently, I have the following line of code which works as expected (see below). (The `T` is a generic parameter to the enclosing method.)
`await context.Set<T>().BatchDeleteAsync();`

When I attempt to upgrade either **EFCore.BulkExtensions** or **Microsoft.EntityFrameworkCore** to a later version, this line of code fails with the following error and stack trace:

`System.NullReferenceException: 'Object reference not set to an instance of an object.'`
`   at EFCore.BulkExtensions.SqlAdapters.SqlAdaptersMapping.GetAdapterDialect()
   at EFCore.BulkExtensions.BatchUtil.GetBatchSql(IQueryable query, DbContext context, Boolean isUpdate)
   at EFCore.BulkExtensions.BatchUtil.GetSqlDelete(IQueryable query, DbContext context)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.GetBatchDeleteArguments(IQueryable query)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.<BatchDeleteAsync>d__1.MoveNext()
   at MyDataRepository.<DeleteAllStagingDataAsync>d__9`1.MoveNext() `
   
Is the code above expected to work with the latest version of these packages?

Thank you

**Comment by borisdj** [comment]
Since Batch ops as of EF7 are now natively supported with ExecuteUpdate/ExecuteDelete, Batch extensions will become Deprecated here. Focus is only on **BULK** methods which are the main purpose of the lib.
