### ISSUE TITLE
EFCore.BulkExtensions SQLServer System.Collections.Generic.KeyNotFoundException: The given key 'lfd_nr' was not present in the dictionary.

### ISSUE THREAD

**Issue by HJoost** [borisdj/EFCore.BulkExtensions#1140]
Since updating to V7.03 I get the following error on BulkInsertAsync:

`System.Collections.Generic.KeyNotFoundException: The given key 'lfd_nr' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, Type type, IList`1 entities, Boolean loadOnlyPKColumn)
   at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
   at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
   at BulkInsert.Controllers.PackingController.Post() in C:\Temp\BulkInsertSample\BulkInsert\BulkInsert\Controllers\PackingController.cs:line 40
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)`

![image](https://user-images.githubusercontent.com/13537894/233075740-477ad6ff-e3c9-405d-99f3-2322ea654edf.png)

Before updating using V6.6.5 it worked without problems:

![image](https://user-images.githubusercontent.com/13537894/233076297-8daa8a7d-0299-4ee5-99c9-8d0cee3f1448.png)

I attached a working sample. Be sure to start it via docker compose, because the database is necessary!

Reproduction steps:
- Start via docker-compose
- Swagger UI opens
- Run Post request via "Try it out" --> "Execute" Buttons
- Get request is only for verification whether data got written into the table

It's possible to downgrade the Nuget Package in the sample to 6.6.5 then it works without the error. On 7.0.3 the error appears.

AspNetCore 7
EF Core 7.04
MS SQL Server

[BulkInsertError.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/11273136/BulkInsertError.zip)

**Comment by borisdj** [comment]
I have copied this code into the new test in the source and it passed.
Check again with latest version 7.0.4 and is still having issue can you write a reproducible test analog to existing one in the source of the lib.

**Comment by HJoost** [comment]
Yes 7.0.4 fixed this problem. Thank you for the quick solution!
