### ISSUE TITLE
Timestamp related regression in 7.1.1

### ISSUE THREAD

**Issue by bdbvb** [borisdj/EFCore.BulkExtensions#1151]
I'm using at least BulkDeleteAsync and BulkInsertOrUpdateAsync, with SQL Server.

Suddenly with v7.1.1, I experienced a regression related to Timestamp fields. If I go back to 7.1.0, everything works OK. 

For example, when calling BulkInsertOrUpdateAsync, I get the error below. My entities have the Timestamp attribute on the row version field, the database field is a non-nullable timestamp, and the row version is configured for the data context with IsRowVersion().

Any recent changes that might have impacted this?

Thanks!

```
warn: Hangfire.AutomaticRetryAttribute[0]
      Failed to process the job '15045': an exception occurred. Retry attempt 1 of 5 will be performed in 00:00:20.
      Microsoft.Data.SqlClient.SqlException (0x80131904): Implicit conversion from data type nvarchar to varbinary is not allowed. Use the CONVERT function to run this query.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
         at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
         at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<InternalExecuteNonQueryAsync>b__208_1(IAsyncResult result)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRawAsync(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters, CancellationToken cancellationToken)
         at EFCore.BulkExtensions.SqlAdapters.SqlServer.SqlServerAdapter.MergeAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
         at EFCore.BulkExtensions.SqlAdapters.SqlServer.SqlServerAdapter.MergeAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
         at EFCore.BulkExtensions.SqlAdapters.SqlServer.SqlServerAdapter.MergeAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
         at EFCore.BulkExtensions.SqlBulkOperation.MergeAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
         at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IEnumerable`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)

[...redacted...]

         at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
         at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
      ClientConnectionId:9dcc0cf8-e908-45c5-83d3-70869f1f3148
      Error Number:257,State:3,Class:16
```

**Comment by bdbvb** [comment]
Here is a new GitHub repo with a minimal reproduction of the issue:

https://github.com/bdbvb/BulkIssue

This is a Visual Studio 2022 solution with an ASPNET Core 7 web app, EF Core 7, and SQL 2019 database.

Use the SQL script to create the very simple database on your local dev machine. It contains a table called Test with columns Id (a GUID), Value, and RowVersion (a timestamp).

Then just Ctrl-F5 from Visual Studio to build and run the web app. Then use the Swagger UI to execute the "reproduce-issue" API call.

Result:
![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/11095196/199451f1-4189-48e0-958f-d63fe7571b40)

Relevant code:
![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/11095196/8c0abe1d-80a2-4be9-ac49-7cadb8ada69f)

**Comment by borisdj** [comment]
Issue is caused by changes in the way Stats are calculate.
Until resolved remove that from bulkConfig, also no need to put RowVersion in any of PropToEx.

**Comment by bdbvb** [comment]
Thank you, sir. 

Any rough timeframe on a new patch release?
