### ISSUE TITLE
Failed to read the result set. System.InvalidOperationException: Connection must be Open; current state is Closed

### ISSUE THREAD

**Issue by Afshalkhan** [borisdj/EFCore.BulkExtensions#1190]
var _data = _dbContextOld.Detail;

                List<Transaction> list = new List<Transaction>();
                foreach (var item in _data)
                {
                    list.Add(new Transaction
                    {
                        Status = (int)Common.Status.Active,
                        CreationDate = (DateTime)item.ttrndat,
                        CompanyCode = item.tloccod.PadLeft(item.tloccod.Length + 1, '0'),
                        CreditAmount = (int)item.tcrtamt,
                        DebitAmount = (int)item.tdbtamt,
                        Description = string.IsNullOrWhiteSpace(item.ttrndsc.Trim()) ? null : item.ttrndsc.Trim(),
                        Type = item.ttrntyp,
                    });
                }
                _dbContext.BulkInsert(list);
                
                
This is my code, and I'm getting this error:

MySqlConnector.MySqlException (0x80004005): Failed to read the result set.
 ---> System.InvalidOperationException: Connection must be Open; current state is Closed
   at MySqlConnector.MySqlConnection.get_Session() in /_/src/MySqlConnector/MySqlConnection.cs:line 745
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 115
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 133
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 468
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 296
   at MySqlConnector.MySqlBulkLoader.LoadAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlBulkLoader.cs:line 213
   at MySqlConnector.MySqlBulkCopy.WriteToServerAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlBulkCopy.cs:line 335
   at MySqlConnector.MySqlBulkCopy.WriteToServer(DataTable dataTable) in /_/src/MySqlConnector/MySqlBulkCopy.cs:line 114
   at EFCore.BulkExtensions.SqlAdapters.MySql.MySqlAdapter.InsertAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.MySql.MySqlAdapter.InsertAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.MySql.MySqlAdapter.Insert[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress)
   at EFCore.BulkExtensions.SqlBulkOperation.Insert[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, Type type, IEnumerable`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsert[T](DbContext context, IEnumerable`1 entities, BulkConfig bulkConfig, Action`1 progress, Type type)
   at LC_ERP.Repository.DataMigrationRepo.UpdateTransactionsTable() in E:\Projects\10 - LCERP\LC_ERP\LC_ERP.Repository\Repository\DataMigration\DataMigrationRepo.cs:line 197
   at LC_ERP.Service.DataMigrationService.UpdateTransactionTable() in E:\Projects\10 - LCERP\LC_ERP\LC_ERP.Service\Services\DataMigration\DataMigrationService.cs:line 24
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

**Comment by borisdj** [comment]
Can you write entire code snipped for this issue, Entity model and Context config.
other option to write a test or alter existing one for MySql where the issue would be reporoducible.
