### ISSUE TITLE
(BulkExtensions 6.5.6) Bulk Operation in Azure Function execution failure for severed relationship on BulkInsert

### ISSUE THREAD

**Issue by Prinsn** [borisdj/EFCore.BulkExtensions#1208]
I'm not sure what code to provide other than a few details, don't know what, if any, Azure nuget packages are relevant
1) This is whichever of in/out of process is compared to what it was before 5.0 created the option (I think in process but I cannot remember)
2) This is reproducible locally only in the function, web server project execution shows no issue
3) Same SQL connection string to same database in both contexts

error

>The association between entities '<parent, omitted>' and '<child, omitted>' with the key value '{PartnerRelationshipId: 10905}' has been severed, but the relationship is either marked as required or is implicitly required because the foreign key is not nullable. If the dependent/child entity should be deleted when a required relationship is severed, configure the relationship to use cascade deletes.

```cs
        public void BulkInsert<T>(IList<T> entities) where T : class
        {
            var dbEntries = entities.Select(z => Entry(z)).ToList();

            var config = new BulkConfig
                {
                    SetOutputIdentity = true,
                    TrackingEntities = true,
                };
            DbContextBulkExtensions.BulkInsert(this, entities, config);
        }
  ```
  
And it is only inserting 4 entities, and the first in the list has it's relationship on the EntityEntry as `<null>` in the Watch pin preview on thrown exception, but the navigation properties are populated with unchanged entities

db entries before save
![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/3219355/c465aa2b-9a27-47bd-9051-c66f96f0b2a8)
db entries at exception thrown
![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/3219355/452767d6-73fc-4031-bb3f-19cb14afa574)

And all of the foreign key navigation properties Entries are in state `Unchanged`

I'm at a loss of how to diagnose this further, I've tried clearing the context using the change tracker, iterating over the entities and detaching them all and re-adding them, nothing changes the resulting behavior

Transient or Scoped service lifetime for the DbContext injection doesn't seem to make a difference (which was suggested by the Azure team in previous runins with things working differently in Functions)

stack trace:
```
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.HandleConceptualNulls(Boolean sensitiveLoggingEnabled, Boolean force, Boolean isCascadeDelete)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete, CurrentValueType valueType)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.ConditionallyNullForeignKeyProperties(InternalEntityEntry dependentEntry, InternalEntityEntry principalEntry, IForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.ToDependentFixup(InternalEntityEntry dependentEntry, InternalEntityEntry principalEntry, IForeignKey foreignKey, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.TrackedFromQuery(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.QueryContext.StartTracking(IEntityType entityType, Object entity, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFCore.BulkExtensions.TableInfo.<LoadOutputDataAsync>d__200`1.MoveNext()
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__5`1.MoveNext()
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__5`1.MoveNext()
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.Merge[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsert[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress, Type type)
   at <omitted>.BulkInsert[T](IList`1 entities

**Comment by Prinsn** [comment]
I cannot isolate this to being specifically the fault of the extensions, at least not as reported

It's possible a prior bulk operation creates the conditions for this to happen but running change detection up and down execution, the failure never happens until these specific entities are saved or the navigation property entry is detached

I cannot make any sense of it

**Comment by borisdj** [comment]
There is not enough info in the issue to make it reproducible.
Hope your solved it or found a workaround.
Will close it now, still if you manage to make a test with the issue you can write it here later.
