### ISSUE TITLE
Bulk Insert failing on database generated primary key

### ISSUE THREAD

**Issue by DanKirwan** [borisdj/EFCore.BulkExtensions#1216]
I am using the BulkInsert method to add entities with GUID Generated Ids the error is as follows:
```System.InvalidOperationException: The binary import operation was started with 17 column(s), but 18 value(s) were provided.
   at Npgsql.ThrowHelper.ThrowInvalidOperationException_BinaryImportParametersMismatch(Int32 columnCount, Int32 valueCount)
   at Npgsql.NpgsqlBinaryImporter.CheckColumnIndex()
   at Npgsql.NpgsqlBinaryImporter.Write[T](T value, String dataTypeName, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlBinaryImporter.WriteAsync[T](T value, String dataTypeName, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.PostgreSql.PostgreSqlAdapter.InsertAsync[T](DbContext context, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.PostgreSql.PostgreSqlAdapter.InsertAsync[T](DbContext context, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.PostgreSql.PostgreSqlAdapter.InsertAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlBulkOperation.InsertAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IEnumerable`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)```
```

## Model Definition 

```csharp
public class ExampleModel
{
    [Key]
    [GraphQLType(typeof(IdType))]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public virtual System.Guid Id { get; set; }
    
    // Other non-db generated fields
    //...
}

```

## Data Context

```csharp

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<DataSourcePointer>().Property(x => x.Id).HasDefaultValueSql("NEWID()");
}
```

## Erroring code
```csharp
_db.BulkInsert(cachedUploads);
```

## Packages used
The project is running in .Net7
```
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.4" />
<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="7.0.10" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.10">
<PackageReference Include="EFCore.BulkExtensions" Version="7.1.5" />
```

## Current fix 
This system is being used with both LocalDB SQL servers and Postgres so the current fix is to detect when using Postgres and make sure to use this bulk config: 

```new BulkConfig() { PropertiesToExclude = new List<string> { nameof(IModelShared.Id) } };```
However, if this config is used with normal SQL, it throws an error of a changed schema. 

## Related Issues
#1061 - This is a similar issue, I'm not sure why it wasn't reproducible please let me know if there's more context I can provide 
#769 - This appears to be the same issue too

**Comment by borisdj** [comment]
For SqlServer it works fine, I assume you are having issue only with PG.
But setting `.HasDefaultValueSql("NEWID()");` for Postgres breaks on creating DB.
Do you have separate configuration for PG ?

**Comment by DanKirwan** [comment]
Apologies you are correct, I am using 

```.HasDefaultValueSql("gen_random_uuid()");``` on postgres. 


Other than this everything else is the same.
I believe this is the same issue as all of the other issues I've referenced and is still a problem. I'm happy to create a sample repository which has this problem if that would be useful to help reproduce.

**Comment by borisdj** [comment]
Still not able to reproduce it.
Have added _**GraphQLModel**_ class it tested it in _InsertTestPostgreSql_, and it passes.
