### ISSUE TITLE
BulkInsert throws exception on shadow primary key

### ISSUE THREAD

**Issue by axelgenus** [borisdj/EFCore.BulkExtensions#1333]
I have a SQL Server table with a primary key which is mapped to EFCore as a shadow property:

```csharp
builder.Property<Guid>("Id")
  .HasDefaultValueSql("NEWID()")
  .IsRequired();

builder.HasKey("Id");
```

I am calling `BulkInsertAsync` like this:

```csharp
await _repository.BulkInsertAsync(items,
    config =>
    {
        config.BatchSize = 500;
        config.BulkCopyTimeout = 0;

        config.UseOptionLoopJoin = false;
    },
    pct => { _logger.LogDebug("Progress = {Progress:P1}", pct); },
    cancellationToken);
```

It throws the following exception:

```
System.Collections.Generic.KeyNotFoundException: The given key 'Id' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, Type type, IEnumerable`1 entities, Boolean loadOnlyPKColumn)
   at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, Type type, IEnumerable`1 entities, OperationType operationType, BulkConfig bulkConfig)
   at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IEnumerable`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
[...]
```

Enabling `EnableShadowProperties` and `ShadowPropertyValue` (to set the primary key on client side instead of relying on the SQL default value) do not change the outcome.

I tried debugging using Rider's decompiler and it seems that the exception is thrown in EFCore.BulkExtensions' TableInfo.cs at line 354 ([link](https://github.com/borisdj/EFCore.BulkExtensions/blob/26bcfc796ec101eb0019e2615924f97f1defe805/EFCore.BulkExtensions/TableInfo.cs#L354)).

Looking at the code, it seems an edge case: GUID primary key + shadow property = exception. I could not figure out what dictionary the exception is talking about since `allPropertiesExceptTimeStamp` is an `IEnumerable`.

**Comment by axelgenus** [comment]
There are two workarounds for this issue:

- Define the primary key as a **public** property and just map it as a usual: `builder.HasKey(e => e.Id);`.
- Define the primary key as a **private** property and map it as a shadow property.
