### ISSUE TITLE
BulkRead with UseTempDB throws exception

### ISSUE THREAD

**Issue by palhal** [borisdj/EFCore.BulkExtensions#1360]
When I try to bulk read together with `UseTempDB`, I get the following exception:

```
{Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: MyEntitiesTemp1301e9ab'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.Prepare()
   at EFCore.BulkExtensions.SqlAdapters.Sqlite.SqliteAdapter.GetSqliteCommand[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, SqliteConnection connection, SqliteTransaction transaction)
   at EFCore.BulkExtensions.SqlAdapters.Sqlite.SqliteAdapter.InsertAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.Sqlite.SqliteAdapter.InsertAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.Sqlite.SqliteAdapter.ReadAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.Sqlite.SqliteAdapter.ReadAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.Sqlite.SqliteAdapter.ReadAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlBulkOperation.ReadAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IEnumerable`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
   at BulkRead[T](IList`1 entities)
```

```cs
private async Task BulkRead(IList<MyEntity> entities)
{
    BulkConfig config = new()
    {
        UpdateByProperties = [nameof(MyEntity.Type), nameof(MyEntity.Name)],
        UseTempDB = true
    };

    using (var trans = await _db.Database.BeginTransactionAsync())
    {
        await db.BulkReadAsync(entities, config);
        await trans.CommitAsync();
    };
}

public class MyEntity
{
    public int Id { get; set; }
    public string Type { get; set; }
    public string Name { get; set; }
}

public void Configure(EntityTypeBuilder<MyEntity> builder)
{
    builder.Property(m => m.Id).ValueGeneratedOnAdd();
    builder.HasKey(m => m.Id);
    builder.Property(m => m.Type).IsRequired();
    builder.Property(m => m.Name).IsRequired();
    builder.HasIndex(m => new { m.Type, m.Name }).IsUnique();
}
```

`BulkInsertOrUpdate` works fine with the same BulkConfig. `BulkRead` works fine without UseTempDB.

Is this a bug or am I using `BulkReadAsync` the wrong way?

Using EFCore.BulkExtensions.Sqlite 8.0.1.

**Comment by borisdj** [comment]
It was a bug, now is fixed, will be published with new nuget release soon.

**Comment by palhal** [comment]
Any ETA on the new release?

**Comment by borisdj** [comment]
v8.0.2
