### ISSUE TITLE
batchdelete with entity with ulong -field in postgres

### ISSUE THREAD

**Issue by MannusEtten** [borisdj/EFCore.BulkExtensions#1387]
System.ArgumentException: The parameter data type of UInt64 is invalid.
   at Microsoft.Data.SqlClient.MetaType.GetMetaTypeFromValue(Type dataType, Object value, Boolean inferLen, Boolean streamAllowed)
   at Microsoft.Data.SqlClient.MetaType.GetMetaTypeFromType(Type dataType)
   at Microsoft.Data.SqlClient.SqlParameter.GetMetaTypeOnly()
   at Microsoft.Data.SqlClient.SqlParameter.get_DbType()
   at EFCore.BulkExtensions.SqlAdapters.SqlDefaultDialect.ReloadSqlParameters(DbContext context, List`1 sqlParameters)
   at EFCore.BulkExtensions.BatchUtil.ReloadSqlParameters(DbContext context, List`1 sqlParameters)
   at EFCore.BulkExtensions.BatchUtil.GetSqlDelete(IQueryable query, DbContext context)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.GetBatchDeleteArguments(IQueryable query)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchDelete(IQueryable query)

**Comment by borisdj** [comment]
Batch ops are obsolete since EF 7 when native Execute-Update/Delete were introduced.
Lib focus now is mainly on Bulk methods.
