### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by msigut** [borisdj/EFCore.BulkExtensions#144]
Hi Boris,

please help me with using **Timeout** in **EFCore.BulkExtensions**.

I use Timeout settings in ConnectionString: ` "ConnectionString": "Server=.;Database=<DB>;Trusted_Connection=True;ConnectRetryCount=0;Connection Timeout=60;"`

and then settings by `EFCore.BulkExtensions` documentation (**BulkCopyTimeout = 0**):
`await _context.BulkInsertOrUpdateAsync(result, new BulkConfig { PreserveInsertOrder = true, SetOutputIdentity = true, BulkCopyTimeout = 0 });`

but gets SQL error:
```
[Error] Failed executing DbCommand ("32,537"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""MERGE [dbo].[Cards] WITH (HOLDLOCK) AS T USING (SELECT TOP 45496 * FROM [dbo]
```

stack:
```
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (258): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
ClientConnectionId:27baf91c-cfe4-4f4c-8808-7e6d3d1e8982
Error Number:-2,State:0,Class:11
2019-02-05 07:51:02.841 +01:00 [Error] Application "Something.Commander" crashed
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (258): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommandAsync(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlBulkOperation.MergeAsync[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at EFCore.BulkExtensions.SqlBulkOperation.MergeAsync[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at Something.BLL.Backend.ContentBeService.SyncCards(String[] expansionCodes) in C:\Projects\Something\src\Something\BLL.Backend\ContentBeService.cs:line 171
```

Thank you ...

Martin

**Comment by borisdj** [comment]
I am unable to reproduce the issue.
In EFCoreBulkTestAsync on method RunInsertOrUpdateAsync I have changed BulkConfig to:
```C#
var bulkConfig = new BulkConfig() { SetOutputIdentity = true, PreserveInsertOrder = true, BulkCopyTimeout = 0 };
```
Also EntitiesNumber increased to 100000.
And in TestContext connString is set to the following:
```var connectionString = $"Server=localhost;Database={databaseName};Trusted_Connection=True;MultipleActiveResultSets=true;ConnectRetryCount=0;Connection Timeout=60;";```

And Test passes successfully.
Can you alter this test so that issue would be reproducible, and then write what changes you have made.

**Comment by aloene** [comment]
Hi,

I have the same issue with 4200 records with default timeout.
I have now set BulkCopyTimeout to 0 but waited 5 minutes and the BulkInsertOrUpdateAsync() never returns. I do not understand what is going on.

If it helps the BulkInsertOrUpdateAsync() is part of a transaction : 
```
using (var dbTransaction = _dbContext.Database.BeginTransaction())
            {
[...] (Selects)

await _dbContext.BulkInsertOrUpdateAsync(
                    dbEntries,
                    new BulkConfig
                    {
                        BulkCopyTimeout = 0,
                        SetOutputIdentity = true,
                        UpdateByProperties = new List<string> { nameof(Entry.BusinessId), nameof(Entry.EntryTypeId) },
                        PropertiesToExclude = new List<string> { nameof(Entry.Id), nameof(Entry.ParentId) }
                    });
```
NOTE: There is an index on Entry(EntryTypeId + BusinessId) and 5-6 fields are part of each record (to be inserted/updated)

Any idea ?

Thank you.

**Comment by msigut** [comment]
It's time to time, when run run task again solve-it usually.

Today one exception trace comes with one possible lead:
[09:57:39 ERR] Failed executing DbCommand (30,269ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
IF OBJECT_ID('[dbo].[StoragePriceAtomsTempf086c3e5]', 'U') **IS NOT NULL DROP TABLE [dbo].[StoragePriceAtomsTempf086c3e5]**
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exce
ption (258): The wait operation timed out

Please check this ... I understand that reprodution can be hard ...

Martin

full **stack-trace**:
```
MERGE [dbo].[StoragePriceAtoms] WITH (HOLDLOCK) AS T USING [dbo].[StoragePriceAtomsTempf086c3e5] AS S ON T.[Id] = S.[Id] WHEN MATCHED THEN UPDATE SET T.[ChangeDate] = S.[ChangeDate], T.[ChangePerc] =
S.[ChangePerc], T.[ChangeValue] = S.[ChangeValue], T.[ChangeValueNormative] = S.[ChangeValueNormative], T.[Created] = S.[Created], T.[DateFrom] = S.[DateFrom], T.[DateTo] = S.[DateTo], T.[IsLast] = S.
[IsLast], T.[Note] = S.[Note], T.[Price] = S.[Price], T.[PriceNormative] = S.[PriceNormative], T.[StoragePrice_Id] = S.[StoragePrice_Id];
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exce
ption (258): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, Cancellation
Token cancellationToken)
ClientConnectionId:1b971df4-a3ee-438e-9616-f6d939be10d7
Error Number:-2,State:0,Class:11
[09:57:39 ERR] Failed executing DbCommand (30,269ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
IF OBJECT_ID('[dbo].[StoragePriceAtomsTempf086c3e5]', 'U') IS NOT NULL DROP TABLE [dbo].[StoragePriceAtomsTempf086c3e5]
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exce
ption (258): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, Cancellation
Token cancellationToken)
ClientConnectionId:1b971df4-a3ee-438e-9616-f6d939be10d7
Error Number:-2,State:0,Class:11
[09:57:54 ERR] Application MtG.Commander crashed
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exce
ption (258): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
```

**Comment by borisdj** [comment]
Still can't reproduce it.
Unless you can make a Test where it would reproducible can't help you much.
From the Exception you got it seems that it just can't finish the operation in reasonable time.
The DROP segment in Trace in not the cause, that code only ensures TempTable are not left in Db after some exception.

**Comment by kKen94** [comment]
I have the same problem with update.
I can't riproduce this, it's random.
net core 3.1

**Comment by Iliescu-Dorin** [comment]
Hi, I had a similar issue with BatchUpdate(). Inside the package MergeAsync<T>(), then  ExecuteSqlRawAsync(). Or more precise here: https://github.dev/borisdj/EFCore.BulkExtensions/blob/a95e23539455e8224ead430a55168fff7e59d9ad/EFCore.BulkExtensions/SqlAdapters/SqlServer/SqlServerAdapter.cs#L217-L225

The issue in in the "parameters":
![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/31242262/dfc52728-61e4-4525-9021-780ef1a9bd76)

BulkCopyTimeout is not added inside the parameters to be used further by the EF Core and overwrite SqlCommandTimeout, so it will take the default one (aka. 30 sec). 

**My solution** was to modify the DbContext SqlCommandTimeout in Startup.cs.

services.AddDbContext<YOURDBCONTEXT>(options =>
    {
        options.UseSqlServer(YOURCONNECTIONSTRING,  sqlOptions =>
        {
            **sqlOptions.CommandTimeout(60);**
        });
       },
    );
    
    **Another solution** would be to use DbInterceptors and overwrite the timeout right before EF Core executes it.
    
    But still this can be easily addressed with a small fix to include BulkCopyTimeout  in the parameters and overwrite the SqlCommandTimeout.

**Comment by Iliescu-Dorin** [comment]
Hi, I had a similar issue with BatchUpdate(). Inside the package MergeAsync<T>(), then  ExecuteSqlRawAsync(). Or more precise here: https://github.dev/borisdj/EFCore.BulkExtensions/blob/a95e23539455e8224ead430a55168fff7e59d9ad/EFCore.BulkExtensions/SqlAdapters/SqlServer/SqlServerAdapter.cs#L217-L225

The issue in in the "parameters":
![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/31242262/dfc52728-61e4-4525-9021-780ef1a9bd76)

BulkCopyTimeout is not added inside the parameters to be used further by the EF Core and overwrite SqlCommandTimeout, so it will take the default one (aka. 30 sec). 

**My solution** was to modify the DbContext SqlCommandTimeout in Startup.cs.
``` C#
services.AddDbContext<YOURDBCONTEXT>(options =>
    {
        options.UseSqlServer(YOURCONNECTIONSTRING,  sqlOptions =>
        {
            sqlOptions.CommandTimeout(60);
        });
       },
    );
```    
**Another solution** would be to use DbInterceptors and overwrite the timeout right before EF Core executes it.
    
    But still this can be easily addresed if
