### ISSUE TITLE
MySql/MariaDB error "The transaction associated with this command is not the connection’s active transaction" occurs when a timeout error occurs

### ISSUE THREAD

**Issue by KaRom31** [borisdj/EFCore.BulkExtensions#1467]
Hello,
I have a problem when using any method with MySql/MariaDb when a timeout error occurs.
When the operation timeout is exceeded, an error "The transaction associated with this command is not the connection’s active transaction" occurs, which hides the real problem. This problem is solved by the "IgnoreCommandTransaction=true" flag, but I would not like to always force this option to be used explicitly.

```
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 309
   at MySqlConnector.MySqlCommand.ExecuteNonQuery() in /_/src/MySqlConnector/MySqlCommand.cs:line 108
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRaw(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters)
   at EFCore.BulkExtensions.SqlAdapters.MySql.MySqlAdapter.MergeAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.MySql.MySqlAdapter.Merge[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, Type type, IEnumerable`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkDelete[T](DbContext context, IEnumerable`1 entities, BulkConfig bulkConfig, Action`1 progress, Type type)
```

Code example:
```csharp
using var db = new MainContext();
{
        try
        {
            var entitiesToDelete = db.Elements
                    .AsNoTracking()
                    .ToList();

            db.BulkDelete(entitiesToDelete);
        }
        catch (Exception ex)
        {

        }
}
```

**Comment by baltermia** [comment]
I'm still facing the same issue on `EFCore.BulkExtensions.MySql: 8.1.3` and `Pomelo.EntityFrameworkCore.MySql: 8.0.3`.

**Comment by pierriemostert** [comment]
We ran into similar problems once bulk operations started timing out inside transactional flows.

The hard part is that once timeout handling and transaction handling get coupled too tightly, the secondary transaction error can end up masking the real failure, which makes these cases painful to reason about.

Bulk calls are fine when everything succeeds, but when you hit provider-specific timeout behavior, execution safety becomes just as important as raw speed.

In our case, we had better results by keeping tighter control over transaction boundaries and failure handling instead of relying on a single bulk call path.

Curious whether you’re seeing this only on timeout scenarios, or also under normal high-load execution on MySQL/MariaDB?
