### ISSUE TITLE
Using EF Core 8 Complex Property results in error "Sequence contains no matching element"

### ISSUE THREAD

**Issue by Rookian** [borisdj/EFCore.BulkExtensions#1489]
```csharp
 var dbContext = GetDbContext();
 await dbContext.Database.EnsureDeletedAsync();
 await dbContext.Database.EnsureCreatedAsync();
 
 var tagsToSave = new List<Tag>()
 {
     new() { Name = "Tag1", AuditingInfo = new AuditingInfo("A", DateTimeOffset.Now, "B", DateTimeOffset.Now) }
 };
 var bulkConfig = new BulkConfig
 {
     UseTempDB = true,
     BulkCopyTimeout = 0,
     UpdateByProperties = new List<string>
     {
         // When we used owned properties, we left out nameof(Tag.AuditingInfo)
         // When I now leave out nameof(Tag.AuditingInfo), we get the error "Cannot insert the value NULL into column 'AuditingInfo_CreatedAt'"
         // When we specify nameof(Tag.AuditingInfo) we get the error "Sequence contains no matching element"
         nameof(Tag.Name), nameof(Tag.AuditingInfo)
     }
 };

 await dbContext.Database.CreateExecutionStrategy()
     .ExecuteInTransactionAsync(
         () => dbContext.BulkInsertOrUpdateAsync(tagsToSave, bulkConfig),
         () => Task.FromResult(true));
```

```csharp
[ComplexType]
public class AuditingInfo
{
    public AuditingInfo(string createdBy, DateTimeOffset createdAt, string updatedBy, DateTimeOffset updatedAt)
    {
        CreatedBy = createdBy;
        CreatedAt = createdAt;
        UpdatedBy = updatedBy;
        UpdatedAt = updatedAt;
    }

    [MaxLength(100)]
    public string CreatedBy { get; private set; }

    public DateTimeOffset CreatedAt { get; private set; }

    [MaxLength(100)]
    public string UpdatedBy { get; private set; }

    public DateTimeOffset UpdatedAt { get; private set; }
}

public class Tag : Entity
{

    public ulong RowVersion { get; set; }

    [Column(TypeName = "nvarchar(100)")]
    public string Name { get; set; } = null!;
    public AuditingInfo AuditingInfo { get; set; } = null!;
}
```

Stack trace:
System.InvalidOperationException
Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at EFCore.BulkExtensions.TableInfo.<>c__DisplayClass189_0`1.<LoadData>b__3(String b)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, Type type, IEnumerable`1 entities, Boolean loadOnlyPKColumn)
   at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, Type type, IEnumerable`1 entities, OperationType operationType, BulkConfig bulkConfig)
   at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IEnumerable`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass20_0`1.<<ExecuteInTransactionAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass24_0`2.<<ExecuteInTransactionAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass24_0`2.<<ExecuteInTransactionAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at SampleTest.Should() in ***\SampleTest.cs:line 57

**Comment by abhisheksaraiya** [comment]
I have the same issue for properties configured as ComplexProperty on an entity. It seems to be skipping the properties of the ComplexProperty which is resulting in the error (for example):

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Email_UpdatedAtUtc', table 'UsersDb.dbo.KnownUsers'; column does not allow nulls. UPDATE fails.
The statement has been terminated.
```

**Comment by pianomanjh** [comment]
@abhisheksaraiya I am encountering the same issue, with ComplexProperty configurations

**Comment by Rookian** [comment]
This bug is over 1 year old and we did not get any feedback 😐

**Comment by borisdj** [comment]
@Rookian will take another look in a few days.
If anyone is up for a PR with a fix sooner, am happy to validate it and Merge.

**Comment by Rookian** [comment]
@borisdj Any news here?
