### ISSUE TITLE
BulkDelete with owned type fails: System.InvalidOperationException: The given ColumnMapping does not match up with any column in the source or destination

### ISSUE THREAD

**Issue by sandersaares** [borisdj/EFCore.BulkExtensions#152]
BulkDelete throws if my entity type includes an owned entity:

```
Unhandled Exception: System.InvalidOperationException: The given ColumnMapping does not match up with any column in the source or destination.
   at EFCore.BulkExtensions.SqlBulkOperation.Insert[T](DbContext context, IList`1 entities, TableInfo tableInfo, Action`1 progress)
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkDelete[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress)
   at ConsoleApp1.Program.Main(String[] args) in C:\Source\ConsoleApp1\ConsoleApp1\Program.cs:line 27
```

Code to repro (use migrations to create DB):

```csharp
using EFCore.BulkExtensions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Debug;
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace ConsoleApp1
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            using (var dc = new DataContext())
            {
                dc.Foo.Add(new FooRow
                {
                    Id = Guid.NewGuid(),

                    Version = new VersionNumber()
                });

                dc.SaveChanges();

                dc.BulkDelete(dc.Foo.ToList());
            }
        }

        public class FooRow
        {
            public Guid Id { get; set; }

            [Required]
            public VersionNumber Version { get; set; }
        }

        [Owned]
        public sealed class VersionNumber
        {
            public int Major { get; set; }
            public int Minor { get; set; }
            public int Build { get; set; }
            public int Revision { get; set; }
        }

        public class DataContext : DbContext
        {
            public DbSet<FooRow> Foo { get; set; }

            public DataContext()
            {
            }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.ConfigureWarnings(warnings =>
                {
                    warnings.Throw(RelationalEventId.QueryClientEvaluationWarning);
                });

                optionsBuilder.EnableSensitiveDataLogging();
                optionsBuilder.UseLoggerFactory(MyLoggerFactory);

                if (!optionsBuilder.IsConfigured)
                    optionsBuilder.UseSqlServer("Server=(local);Database=EFCore_Issue_Repro;Trusted_Connection=True;");
            }

            public static readonly LoggerFactory MyLoggerFactory = new LoggerFactory(new[]
            {
                new DebugLoggerProvider((category, level) => true)
            });

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
            }
        }
    }
}
```

Latest stable NuGet packages used, .NET Core 2.2 with SQL Server.

**Comment by borisdj** [comment]
Fixed with 2.4.1
