### ISSUE TITLE
.NET 9 - BulkInsertOrUpdateOrDeleteAsync - Cannot get _selectExpression

### ISSUE THREAD

**Issue by evicio1** [borisdj/EFCore.BulkExtensions#1620]
After upgrading to.NET 9, The following error comes up with BulkInsertOrUpdateOrDeleteAsync

**Message**

`Cannot get _selectExpression`

**StackTrace**

`   at EFCore.BulkExtensions.IQueryableExtensions.ToParametrizedSql(IQueryable query)
   at EFCore.BulkExtensions.BatchUtil.GetBatchSql(IQueryable query, DbContext context, Boolean isUpdate)
   at EFCore.BulkExtensions.SqlAdapters.SqlQueryBuilder.MergeTable[T](DbContext context, TableInfo tableInfo, OperationType operationType, IEnumerable`1 entityPropertyWithDefaultValue)
   at EFCore.BulkExtensions.SqlAdapters.SqlServer.SqlServerAdapter.<MergeAsync>d__9`1.MoveNext()
   at EFCore.BulkExtensions.SqlAdapters.SqlServer.SqlServerAdapter.<MergeAsync>d__9`1.MoveNext()
   at EFCore.BulkExtensions.SqlAdapters.SqlServer.SqlServerAdapter.<MergeAsync>d__8`1.MoveNext()
   at EFCore.BulkExtensions.SqlBulkOperation.<MergeAsync>d__5`1.MoveNext()
   at EFCore.BulkExtensions.DbContextBulkTransaction.<ExecuteAsync>d__1`1.MoveNext()`

**Comment by svenclaesson** [comment]
We are using SQLite and experience this error. It's still dependent on Pomelo MySql?

**Comment by borisdj** [comment]
Not sure, will check it out in a few days.

**Comment by Pete-PlaytimeSolutions** [comment]
Just an FYI on what I have found, when using against the "Microsoft.EntityFrameworkCore.SqlServer" Provider.

I think its failing in IQueryableExtensions.ToParametrizedSql method, due to one or more of the "enumerator" private fields no longer existing in net 9.0..

When running under net8.0, the private field "_relationalCommandCache" always seems to be populated, 
whereas under net 9.0 if no longer exists.

i.e
```
string privateField = "_relationalCommandCache";
RelationalCommandCache relationalCommandCache = (RelationalCommandCache)enumerator.Private(privateField);

```
NOTE: When relationalCommandCache is null, the following fallback code does not work for either versions,
due to the private field "_selectExpression" not being available in either net8.0 or net 9.0.
