### ISSUE TITLE
BulkUpdate with owned types

### ISSUE THREAD

**Issue by amnezin** [borisdj/EFCore.BulkExtensions#200]
Hi!

NuGet version 2.4.9
I faced with an issue while implement BulkUpdate that has some owned types:

```
public class A
{
    public Guid Id {get;set;}
    public string Name {get;set;}
    public virtual B BProperty {get;set;}
    public virtual C CProperty {get;set;}
}

public class B
{
    public int CarCount {get;set;}
}

public class C
{
    public int HouseCount {get;set;}
}

public override void Map(EntityTypeBuilder<A> builder)
{
    builder.HasKey(entity => entity.Id);
    builder.Property(entity => entity.Name).HasMaxLength(200).IsRequired();

    builder.OwnsOne(entity => entity.BProperty);
    builder.OwnsOne(entity => entity.CProperty);
}
```
I want to update just A.BProperty.
I have a repository method:
```
public async Task UpdateOnlyBPropertiesAsync(IList<A> list)
{
    var bProperties = typeof(B)
        .GetProperties(BindingFlags.Public | BindingFlags.Instance)
        .Select(property => $"{nameof(A.BProperty)}_{property.Name}")
        .ToList();

    await DataContext.BulkUpdateAsync(list, new BulkConfig
    {
        PropertiesToInclude = bProperties
    });
}
```

`IList<A> list` entities contains "Id" and "BProperty" fields filled. "Name" and "CProperty" fields is null. 
I received the following error:
```
Column 'CProperty_HouseCount' does not allow DBNull.Value.

   at EFCore.BulkExtensions.SqlBulkOperation.Insert[T](DbContext context, IList`1 entities, TableInfo tableInfo, Action`1 progress)
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkUpdate[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress)
...
```

The same error occurred when I try to use `PropertiesToExclude` method.

Is it possible to update one owned field and exclude all other entity fields? If so, how should I implement it?

**Comment by borisdj** [comment]
Just initialize CProperty to `new C()` instead of leaving it _null_;
You can do it after setting _CarCount_ or in a separate loop before calling BulkUpdate:

```C#
foreach (var entity in list)
{
    entity.CProperty = new C();
}
```

PS Upgrade NuGet to latest version since there was another issue with this that is now fixed.
