### ISSUE TITLE
BulkRead Fail if there is RowVersion 

### ISSUE THREAD

**Issue by vpoorshab** [borisdj/EFCore.BulkExtensions#208]
**Entity :**

```
public class StatementData : EntityBase
    {

        public long StatementDataId { get; set; }

        public string StatementType { get; set; }

        public string DisplayName { get; set; }

        public string FilePath { get; set; }

        public string FileName { get; set; }

        public string FileVersion { get; set; }
        
       [Timestamp]
    public virtual byte[] RowVersion { get; set; }
    }
```
**Usage :** 
```
var existingStatementDataRecord =
   statementData.Select(s => new StatementData() {FileName = s.FileName}).ToList();

await _dbContext.BulkReadAsync(existingStatementDataRecord,
                        config => config.UpdateByProperties = new List<string>() {nameof(StatementData.FileName)});

```
**Debug Info :** 
```
[10:52:34 DBG] Executing DbCommand [Parameters=[], CommandType='"Text"', CommandTimeout='120']
SELECT S.[StatementData_PK], S.[DisplayName], S.[FileName], S.[FilePath], S.[FileVersion],  S.[StatementType] FROM [dbo].[StatementData] AS S JOIN [dbo].[StatementDataTempb6fdc466] AS J ON S.[FileName] = J.[FileName]

```

**Exception:**
```
[10:52:34 ERR] An exception occurred while iterating over the results of a query for context type 'XDbContext'
System.InvalidOperationException: The required column 'RowVersion' was not present in the results of a 'FromSql' operation.
   at Microsoft.EntityFrameworkCore.Query.Sql.Internal.FromSqlNonComposedQuerySqlGenerator.CreateValueBufferFactory(IRelationalValueBufferFactoryFactory relationalValueBufferFactoryFactory, DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.ShaperCommandContext.<NotifyReaderCreated>b__14_0(FactoryAndReader s)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Query.Internal.ShaperCommandContext.NotifyReaderCreated(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
```

**Comment by borisdj** [comment]
Fixed with 2.5.2
