### ISSUE TITLE
System.ArgumentException when calling BatchDelete() on a IQueryable that performs a "Contains"-Operation on an empty Collection

### ISSUE THREAD

**Issue by earloc** [borisdj/EFCore.BulkExtensions#225]
**Steps to reproduce**
See adapted [testcase](https://github.com/earloc/EFCore.BulkExtensions/blob/bc83c6e1f5f75bda669d5e8026056bb308469372/EFCore.BulkExtensions.Tests/EFCoreBatchTest.cs#L113) in my recent [fork](https://github.com/earloc/EFCore.BulkExtensions/tree/Issues/225)

**Expected**
The operation "succeeds" without any erros

**Actual**
A System.ArgumentException is thrown to the caller.

**Additional Info**

> System.ArgumentException: No mapping exists from object type System.Int32[] to a known managed provider native type.
  Stack Trace: 
    at MetaType.GetMetaTypeFromValue(Type dataType, Object value, Boolean inferLen, Boolean streamAllowed)
    at MetaType.GetMetaTypeFromType(Type dataType)
    at SqlParameter.GetMetaTypeOnly()
    at SqlParameter.Validate(Int32 index, Boolean isCommandProc)
    at SqlCommand.BuildParamList(TdsParser parser, SqlParameterCollection parameters, Boolean includeReturnValue)
    at SqlCommand.BuildExecuteSql(CommandBehavior behavior, String commandText, SqlParameterCollection parameters, _SqlRPC& rpc)
    at SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
    at SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
    at SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
    at SqlCommand.ExecuteNonQuery()
    at RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
    at RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
    at RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters)
    at IQueryableBatchExtensions.BatchDelete[T](IQueryable`1 query)

**Comment by earloc** [comment]
Strange, only got this line breaking the test with above Exception:
https://github.com/earloc/EFCore.BulkExtensions/blob/a76b6c60750d75a3d94af45df8ee6bf27d35c6a5/EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs#L303

Wheras the expected to fail test still runs without exception:
https://github.com/earloc/EFCore.BulkExtensions/blob/a76b6c60750d75a3d94af45df8ee6bf27d35c6a5/EFCore.BulkExtensions.Tests/EFCoreBatchTest.cs#L109

**Comment by earloc** [comment]
Ah, got it wrong, ignore last comment. Not the exception I´m actually trying to reproduce at all ;)

**Comment by earloc** [comment]
I must confess, this really is a stupid scenario. Just wanted to let others know about this situation, especially as actually enumerating such a query yields the expected empty-result, at least from an EFCore point-of-view.

Don´t quite know, how such a situation could be detected, as the generated SQL obviously does not contain an "IN-operation", and therefore does not fall into it´s designated [execution-block](https://github.com/earloc/EFCore.BulkExtensions/blob/17a3734e28016811bf0e1663cafebd2a53624c09/EFCore.BulkExtensions/BatchUtil.cs#L105)

**Comment by borisdj** [comment]
You can make a check to see the size of list and if empty not call the BatchDelete.
Thx for the info.
