### ISSUE TITLE
BulkInsert throwing "Value cannot be null. Parameter name: member"

### ISSUE THREAD

**Issue by Menighin** [borisdj/EFCore.BulkExtensions#234]
I have a feature in my system that allows the user to make scenarios from the data.
To do it, I need to copy the data from one scenario to the other, changing the Ids and Foreign keys to keep consistency.
I was doing it fine with EFCore all by itself, but now we are having a lot of more data and it is getting slower by the hour. 
Then I'm trying to use `EFCore.BulkExtensions` to help me improve performance.
One case I'm stuck is to bulk insert some entities with it's translations.
Basically I have the following entities-like:

```
// My book class
public class DbBook
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long Id { get; set; }
    
    public string Title { get; set; }

    public long ScenarioId { get; set; }
    
    public ICollection<DbBookTranslation> BookTranslations { get; set; } = new HashSet<DbBookTranslation>();    
}

// The book translation class, that contains translations for the book description in different languages
public class DbBookTranslation
{

    public long BookId { get; set; }
    
    public string Language { get; set; }
    
    public string Description { get; set; }
}

// Config class for book translation in order to configure its key and some other properties
public class DbBookTranslationMap
{
    public void Configure(EntityTypeBuilder<DbBookTranslation> builder)
    {
        builder.HasKey(a => new {a.Language, a.BookId});
    }
}
```

Then I have my service to copy those entities to a new scenario.
The flow works as follows:

```
// I open a transaction
using (var tr = _ctx.Database.BeginTransaction())
{

    // I get all the books from the old scenario
    var oldBooks = ctx.DbBooks.Where(o => o.ScenarioId == oldScenarioId).AsNoTracking().ToList();

    // I iterate through oldBooks setting their ID to a new one and the ScenarioId to the 
    // new one and add on a list for further inserting
    var newBooks = new List<DbBooks>();
    var i = 0;
    for (var b in oldBooks) 
    {
        b.ScenarioId = newScenarioId;
        b.Id = i++;
        newBooks.Add(b);
    }
    
    // Then I bulk insert it
    // !!THIS IS WHERE IT FAILS!!
    var bulkConfig = new BulkConfig { PreserveInsertOrder = true, SetOutputIdentity = true };
    _ctx.BulkInsert(newBooks, bulkConfig);
    
    // Then I iterate through the translations, setting the new Id with some reflection
    var newTranslations = new List<DbBookTranslation>();
    for (var b in newBooks) {
        for (var t in b.BookTranslations) {
            t.BookId = b.Id; // Its done with reflection in rly
            newTranslations.Add(t);
        }
    }
    
    // Then bulk insert the translations
    _ctx.BulkInsert(newTranslations, bulkConfig);
    
    tr.Commit();
}
```

When I try to make the first `BulkInsertions` of the `DbBook` it fails with the following error:

```
   Value cannot be null. Parameter name: member
   at System.Linq.Expressions.Expression.MakeMemberAccess(Expression expression, MemberInfo member)
   at EFCore.BulkExtensions.TableInfo.OrderBy[T](Expression`1 source, String ordering)
   at EFCore.BulkExtensions.TableInfo.QueryOutputTable[T](DbContext context, String sqlQuery)
   at EFCore.BulkExtensions.TableInfo.LoadOutputData[T](DbContext context, IList`1 entities)
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsert[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress)
   at MyProjectData.Services.ScenarioCopyService.CopyScenarioEntities[T](IEnumerable`1 entitiesEnumerable, Int64 newScenarioId) in C:\Projects\VSTS\MyProject-dotnet\MyProject\MyProject.Data\Services\ScenarioCopyService.cs:line 204
   at MyProject.Data.Services.ScenarioCopyService.CopyScenario(Int64 newScenarioId, Int64 oldScenarioId) in C:\Projects\VSTS\MyProject-dotnet\MyProject\MyProject.Data\Services\ScenarioCopyService.cs:line 77
```

Oddly enough, if I dont pass any `BulkConfig` to the first `BulkInsert` it works. The entities are saved. But then, the second `BulkInsert` fails with `UniqueKeyViolation` because the `BookIds` are not set correctly. 

This is not the REAL REAL code, I can't post it for company reasons. But it is pretty much it.
I have tried debugging the `EFCore.BulkExtensions` code but couldn't make it.
Any help is appreciated.

**Comment by borisdj** [comment]
I have added this code in Test, with creating new dymmy objects, and it passed.
Maybe you could try making a copy of entites, AutoMapper can be used, before changing them.
Also When having multiple Bulk it is good to incapsulate those calls in Transacation as stated in the ReadMe.

Test:
```
C#
		[Fact]
        public void OperationsTestTEMP(DbServer databaseType, bool isBulkOperation)
        {
            // I open a transaction
            using var context = new TestContext(ContextUtil.GetOptions());
            // I get all the books from the old scenario
            var oldBooks = new List<DbBook>
                {
                    new DbBook { Id = 1, Title = "Aa", ScenarioId = 10},
                    new DbBook { Id = 2, Title = "Ba", ScenarioId = 20},
                    new DbBook { Id = 3, Title = "Ca", ScenarioId = 30},
                    new DbBook { Id = 1, Title = "Da", ScenarioId = 40}
                };

            // I iterate through oldBooks setting their ID to a new one and the ScenarioId to the 
            // new one and add on a list for further inserting
            var newBooks = new List<DbBook>();
            var i = 0;
            foreach (var b in oldBooks)
            {
                b.ScenarioId += 1;
                b.Id = i++;
                newBooks.Add(b);
            }

            // Then I bulk insert it
            var bulkConfig = new BulkConfig { PreserveInsertOrder = true, SetOutputIdentity = true };
            context.BulkInsert(newBooks, bulkConfig);

            // Then I iterate through the translations, setting the new Id with some reflection
            var newTranslations = new List<DbBookTranslation>();
            foreach (var b in newBooks)
            {
                foreach (var t in b.BookTranslations)
                {
                    t.BookId = b.Id; // Its done with reflection in rly
                    newTranslations.Add(t);
                }
            }
        }
```
