### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Anduin2017** [borisdj/EFCore.BulkExtensions#239]
## Environment

.netcoreapp3.0

```xml
    <PackageReference Include="EFCore.BulkExtensions" Version="3.0.0-rc" />
```

## My code is here:

```csharp
            int someId = 12345;
            TimeSpan oldestAliveTime = someTimeSpan;
            // Delete outdated
            await _dbContext
                .Messages
                .Where(t => t.ConversationId == someId)
                .Where(t => t.SendTime < oldestAliveTime)
                .BatchDeleteAsync();
```

## My entity design

```csharp
    public class Message
    {
        public int Id { get; set; }

        public int ConversationId { get; set; }

        [JsonIgnore]
        [ForeignKey(nameof(ConversationId))]
        public Conversation Conversation { get; set; }

        public DateTime SendTime { get; set; } = DateTime.UtcNow;
    }
```

## Response

```log
System.NullReferenceException: Object reference not set to an instance of an object.
   at EFCore.BulkExtensions.BatchUtil.GetDbContext(IQueryable query)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchDeleteAsync[T](IQueryable`1 query, CancellationToken cancellationToken)
   at Kahla.Server.Controllers.ConversationController.UpdateMessageLifeTime(UpdateMessageLifeTimeAddressModel model) in D:\Workspace\Aiursoft\Kahla\Kahla.Server\Controllers\ConversationController.cs:line 232
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Aiursoft.Pylon.Middlewares.SwitchLanguageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Kahla.Server.Middlewares.HandleKahlaOptionsMiddleware.Invoke(HttpContext context) in D:\Workspace\Aiursoft\Kahla\Kahla.Server\Middlewares\HandleKahlaOptionsMiddleware.cs:line 43
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Any solution for this?

**Comment by Anduin2017** [comment]
Hi, do you have any solution for this? This issue is stacking us from upgrading.

**Comment by borisdj** [comment]
Should work now:
https://github.com/borisdj/EFCore.BulkExtensions/issues/231
