### ISSUE TITLE
BulkInsert which row has thrown exception

### ISSUE THREAD

**Issue by Yajuvender** [borisdj/EFCore.BulkExtensions#263]
Hi,
While sending 1000 row data (objects) to context.BulkInsert(students), lets say there was an error in 590th object due to NOT NULL constraint. context.BulkInsert is throwing an exception (below is the stacktrace) but I am looking for very specific error like "**in which row the error occurred**" and "**what exactly is the error**". Kindly let me know if there is any out of the box feature to get specific row error in EFCore.BulkExtension (or) please guide me on how to achieve the same.

EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, IList`1 entities, Boolean loadOnlyPKColumn)
   at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsert[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress)
   at EFCodeFirst.PersistData.InsertStudentsInBulk(List`1 students) in D:\EFCodeFirst\PersistData.cs:line 239

**Comment by borisdj** [comment]
Entity should follow its DbTable, so for NotNull column in Db it should also be not null in Entity model.
Also check if some column is null can be added before calling BulkInsert.

Still even if in entity it would be nullable, exception returned gives info:
`{"Cannot insert the value NULL into column 'Quantity', table 'EFCoreBulkTest.dbo.Item'; column does not allow nulls. INSERT fails.\r\nThe statement has been terminated."}`
I have Tested this by changing in `Item`
`int Quantity`
to
`int? Quantity`
And running `EFCoreBulkTest.OperationsTest` (there in `RunInsert` set `Quantity = null`)

**Comment by borisdj** [comment]
When error on Insert is thrown it gives detailed info on which column/row: https://github.com/borisdj/EFCore.BulkExtensions/issues/449
