### ISSUE TITLE
BulkInsertOrUpdateAsync issue when used with Sqlite memory mode.

### ISSUE THREAD

**Issue by StefanBalaban** [borisdj/EFCore.BulkExtensions#265]
I'm using Sqlite memory mode with my unit tests and the issue I'm having is when the code gets to the BulkInsertOrUpdateAsync() method I get the following exception: `Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'near "0": syntax error'.`
The stack trace:
```
at SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
    at SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
    at SqliteCommand.ExecuteReader(CommandBehavior behavior)
    at SqliteCommand.ExecuteNonQuery()
    at DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
    at --- End of stack trace from previous location where exception was thrown ---
    at RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
    at RelationalDatabaseFacadeExtensions.ExecuteSqlCommandAsync(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters, CancellationToken cancellationToken)
    at SqlBulkOperation.MergeAsync[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
```
The method call: 
`await Context.BulkInsertOrUpdateAsync<TDbEntity>(listOfEntities, bulkConfig, null);`
The list is a standard generic list, BulkConfig has only UpdateByProperties and PropertiesToExclude instantieted.

So, is this something related to BulkEtension, Sqlite or am I making a bug?

**Comment by borisdj** [comment]
Try now the latest version 3.1.1.

**Comment by dancoltonart** [comment]
hi, it still does not work, getting this error with 3.1

 SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
    SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
    SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()

data is Queryable

           await data.BatchUpdateAsync(x => new AssessmentRoll 
            { 
               LkAssessmentStatusId = (int)AssessmentStatus.Certified,
               ValueChangeDate = DateTime.Now
           });

**Comment by borisdj** [comment]
If you manage to make a test where this would be reproducible, write it here and we'll reopen the issue.
