### ISSUE TITLE
Can't perform bulk delete due to 'Cannot find field _selectExpression on type Enumerator' exception

### ISSUE THREAD

**Issue by ZlobnyiSerg** [borisdj/EFCore.BulkExtensions#269]
Trying simple bulk delete on my model:
```
await _context.Availabilities.Where(av => av.HotelId == request.HotelId
                                          && av.Date > expectedHorizonDate).BatchDeleteAsync(cancellationToken)
```
with EF Core 3.1, MSSQL 2019 server.
this code fails with exception
```
System.InvalidOperationException : Cannot find field _selectExpression on type Enumerator
   at EFCore.BulkExtensions.IQueryableExtensions.ToSql[TEntity](IQueryable`1 query)
   at EFCore.BulkExtensions.BatchUtil.GetBatchSql[T](IQueryable`1 query, DbContext context, Boolean isUpdate)
   at EFCore.BulkExtensions.BatchUtil.GetSqlDelete[T](IQueryable`1 query, DbContext context)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchDeleteAsync[T](IQueryable`1 query, CancellationToken cancellationToken)
```

**Comment by DustinEwers** [comment]
This is directly related to the 3.1 .NET Core update. This works fine in EF Core 3.0, but tanks (with the error above) when I upgrade EF Core to 3.1.

**Comment by yustun** [comment]
its the same on BulkUpdate as well..

**Comment by gojanpaolo** [comment]
same with SQLite

**Comment by Maleaume** [comment]
Same problematics on my side
![image](https://user-images.githubusercontent.com/28565834/71030907-a6376e80-2112-11ea-93ea-625b9880c270.png)

**Comment by borisdj** [comment]
NuGet 3.1.0 published
