### ISSUE TITLE
BulkUpdate does not work with alot of Linq

### ISSUE THREAD

**Issue by joeydh** [borisdj/EFCore.BulkExtensions#273]
I am getting an error when I am trying to do a bulk update. 

The following is the code:

`	_context.Messages
						   .Where( m => messageIds.Contains( m.TextMessageId ) )
						   .BatchUpdate( x => new TextMessage { Status = Domain.Enums.MessageStatusCode.FailedToQueue } );`

It does work if i remove the contains but if i try anything with an Enumerable like Any or Contains it will fail with the following exception.

The error thrown is :

Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlParameterExpression' to type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlConstantExpression'

And the folllowing in the stacktrace

`   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitIn(InExpression inExpression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GetCommand(SelectExpression selectExpression)
   at EFCore.BulkExtensions.IQueryableExtensions.ToParametrizedSql[TEntity](IQueryable`1 query)
   at EFCore.BulkExtensions.IQueryableExtensions.ToSql[TEntity](IQueryable`1 query)
   at EFCore.BulkExtensions.BatchUtil.GetBatchSql[T](IQueryable`1 query, DbContext context, Boolean isUpdate)
   at EFCore.BulkExtensions.BatchUtil.GetSqlUpdate[T](IQueryable`1 query, DbContext context, Expression`1 expression)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.<BatchUpdateAsync>d__5`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at VertimartSmsService.Application.TextMessages.Commands.CreateTextMessages.TextMessagesCreated.TextMessagesCreatedHandler.<Handle>d__3.MoveNext() in TextMessagesCreated.cs:line 38`

I am using .NET core 3.1,
Latest version of BulkExtentions,
Latest version of SQLite provider

**Comment by svpoon** [comment]
I got the same issue as well. It works on EFCore 2.2 before (using SQL Server)
