### ISSUE TITLE
SqlServer, Spatial, geometry

### ISSUE THREAD

**Issue by yahorsi** [borisdj/EFCore.BulkExtensions#288]
Hi Guys!

Great extension, thanks!
Currently trying to use it and got an exception on the attempt to BulkInsertOrUpdateAsync geometry column and Point type.

Here is the entity I'm tyring to InsertOrUpdate:
```C#
    [Table("Airport")]
    public partial class Airport
    {

        [Key]
        [StringLength(4)]
        public string FourLetterCode { get; set; }
        
        [Required]
        [StringLength(3)]
        public string ThreeLetterCode { get; set; }
        
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        
        [StringLength(3)]
        public string CountryCode { get; set; }
        
        public bool IsDisabled { get; set; }
        
        [Column(TypeName = "datetime")]
        public DateTime Timestamp { get; set; }
        
        [Column(TypeName = "geometry")]
        public Point Location { get; set; }
        
        public string HotelCompany { get; set; }
        
        public string HotelContact { get; set; }
        
        public string HotelPhone { get; set; }
        
        public string HotelMobile { get; set; }
        
        public string HotelFax { get; set; }
        
        public string HotelEmail { get; set; }
        
        public string HotelRemarks { get; set; }
        
    }
```

And the exception:
```C#
System.InvalidOperationException: The given value of type Point from the data source cannot be converted to type udt of the specified target column.
 ---> System.ArgumentException: Specified type is not registered on the target server. NetTopologySuite.Geometries.Point, NetTopologySuite, Version=2.0.0.0, Culture=neutral, PublicKeyToken=f580a05016ebada1.
   at Microsoft.Data.SqlClient.SqlConnection.GetInfoFromType(Type t)
   at Microsoft.Data.SqlClient.SqlConnection.GetBytes(Object o, Format& format, Int32& maxSize)
   at Microsoft.Data.SqlClient.SqlConnection.GetBytes(Object o)
   at Microsoft.Data.SqlClient.SqlBulkCopy.ConvertValue(Object value, _SqlMetaData metadata, Boolean isNull, Boolean& isSqlType, Boolean& coercedToDataFeed)
   --- End of inner exception stack trace ---
   at EFCore.BulkExtensions.SqlBulkOperation.InsertAsync[T](DbContext context, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlBulkOperation.MergeAsync[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlBulkOperation.MergeAsync[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
   at EDW.ReferenceData.API.HostedServices.ServiceBusBackgroundWorker.ExecuteAsync(CancellationToken cancellationToken) in C:\Dev\1stquad\edw.referencedata.api\Source\EDW.ReferenceData.API\ServiceBus\ServiceBusBackgroundWorker.cs:line 151
```

Are there any options available to fix this?

**Comment by valdas1** [comment]
I am having the same issue, but I am using Microsoft.SqlServer.Types for my project. Geometry fields have type of _SqlGeometry_.

```cs
System.InvalidOperationException: The given value of type SqlGeometry from the data source cannot be converted to type udt of the specified target column.
 ---> System.ArgumentException: Specified type is not registered on the target server.Microsoft.SqlServer.Types.SqlGeometry, Microsoft.SqlServer.Types, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91.
   at Microsoft.Data.SqlClient.AssemblyCache.GetInfoFromType(Type t)
   at Microsoft.Data.SqlClient.SqlConnection.GetBytes(Object o, Format& format, Int32& maxSize)
   at Microsoft.Data.SqlClient.SqlConnection.GetBytes(Object o)
   at Microsoft.Data.SqlClient.SqlBulkCopy.ConvertValue(Object value, _SqlMetaData metadata, Boolean isNull, Boolean& isSqlType, Boolean& coercedToDataFeed)
   --- End of inner exception stack trace ---
   at EFCore.BulkExtensions.SqlBulkOperation.Insert[T](DbContext context, IList`1 entities, TableInfo tableInfo, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsert[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress)
```

Would be great to know if any fixes are available, or if it even can be fixed.

**Comment by borisdj** [comment]
https://github.com/borisdj/EFCore.BulkExtensions/issues/88
