### ISSUE TITLE
BatchUpdateAsync fails with Contains

### ISSUE THREAD

**Issue by xumix** [borisdj/EFCore.BulkExtensions#293]
Ef core 2.2, Extensions 2.6.4
Here is full code for my entities:
```
public interface IEntityBase<TKey> : IEntityBase
        where TKey : struct, IComparable<TKey>, IFormattable, IEquatable<TKey>
    {
        new TKey Id { get; set; }
    }

    public interface IEntityBase
    {
        object Id { get; set; }
    }
[DebuggerDisplay("Id: {Id}, Type: {GetType()}")]
    public abstract class EntityIntBase : IEntityBase<int>
    {
        [Key]
        public virtual int Id { get; set; }

        object IEntityBase.Id
        {
            get => Id;

            set => Id = (int)value;
        }
    }

public abstract class ContractFileBase : EntityIntBase
    {
        public virtual ContractFileType ContractFileType { get; set; }

        public virtual int? ContractFileTypeId { get; set; }

        public virtual FileStorage FileStorage { get; set; }

        public virtual int? FileStorageId { get; set; }

        public virtual int? ParentId { get; set; }
    }

public partial class ContractFile : ContractFileBase
    {
        public virtual Contract Parent { get; set; }
    }
```

Trying to update like this:
```
IReadOnlyList<int> fileIds = new List() {1,2,3};
await repository.Query<ContractFile>()
               .Where(c => fileIds.Contains(c.Id))
               .BatchUpdateAsync(c => new ContractFile { ParentId = newContract.Id });
```
Getting this error:
```
System.ArgumentException : No mapping exists from object type System.Int32[] to a known managed provider native type.
   at System.Data.SqlClient.MetaType.GetMetaTypeFromValue(Type dataType, Object value, Boolean inferLen, Boolean streamAllowed)
   at System.Data.SqlClient.MetaType.GetMetaTypeFromType(Type dataType)
   at System.Data.SqlClient.SqlParameter.GetMetaTypeOnly()
   at System.Data.SqlClient.SqlParameter.get_DbType()
   at Microsoft.EntityFrameworkCore.Storage.Internal.DbParameterCollectionExtensions.<>c__DisplayClass0_0.<FormatParameters>b__0(DbParameter p)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.String.JoinCore[T](Char* separator, Int32 separatorLength, IEnumerable`1 values)
   at System.String.Join[T](String separator, IEnumerable`1 values)
   at Microsoft.EntityFrameworkCore.Internal.EnumerableExtensions.Join(IEnumerable`1 source, String separator)
   at Microsoft.EntityFrameworkCore.Storage.Internal.DbParameterCollectionExtensions.FormatParameters(DbParameterCollection parameters, Boolean logParameterValues)
   at Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.CommandError(IDiagnosticsLogger`1 diagnostics, DbCommand command, DbCommandMethod executeMethod, Guid commandId, Guid connectionId, Exception exception, Boolean async, DateTimeOffset startTime, TimeSpan duration)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommandAsync(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchUpdateAsync[T](IQueryable`1 query, Expression`1 updateExpression, CancellationToken cancellationToken)
```

**Comment by mr-xrow** [comment]
I get same issue too
EF Core 3.1, BulkExtensions 3.1
` var list=new []{1,2,3,4,5};
db.Set<Model>().Where(i=>list.Contains(i.Id)).BatchDelete();`
Error:
`nvalidCastException: Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlParameterExpression' to type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlConstantExpression'.`

**Comment by xumix** [comment]
@mr-xrow my bug reproduces when the list is empty

**Comment by svpoon** [comment]
When will this be fixed. I cannot upgrade to Net Core 3.1 without this fixed.

**Comment by devel112** [comment]
I get error with one item in list (havent tested with more)

{"Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlParameterExpression' to type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlConstantExpression'."}

   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitIn(InExpression inExpression)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GetCommand(SelectExpression selectExpression)
   at EFCore.BulkExtensions.IQueryableExtensions.ToParametrizedSql[TEntity](IQueryable`1 query)
   at EFCore.BulkExtensions.IQueryableExtensions.ToSql[TEntity](IQueryable`1 query)
   at EFCore.BulkExtensions.BatchUtil.GetBatchSql[T](IQueryable`1 query, DbContext context, Boolean isUpdate)
   at EFCore.BulkExtensions.BatchUtil.GetSqlDelete[T](IQueryable`1 query, DbContext context)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchDelete[T](IQueryable`1 query)

**Comment by LuanNunes** [comment]
I'm have the same issue with 3.1 version :(

**Comment by borisdj** [comment]
Please try now with v3.1.1.
If the issue still exist write simplified but complete code how to reproduce it
(code in first post there are no definition of classes _FileStorage_ nor _Contract_)

**Comment by LuanNunes** [comment]
It's work! Thanks a lot @borisdj

**Comment by AndriiLab** [comment]
I have similar situation with: 
EF Core 6.0.6
Npgsql.EntityFrameworkCore.PostgreSQL 6.0.5
EFCore.BulkExtensions 6.5.2

When running `BatchUpdate`:
```C#
var ids = new[] {1, 2, 3};
var newId = 5;
await _database.Orders
            .Where(o => ids.Contains(o.UnitId))
            .BatchUpdateAsync(o => new Order {UnitId = newId});
```
I got this:
```
System.ArgumentException: No mapping exists from object type System.Int32[] to a known managed provider native type.
   at Microsoft.Data.SqlClient.MetaType.GetMetaTypeFromValue(Type dataType, Object value, Boolean inferLen, Boolean streamAllowed)
   at Microsoft.Data.SqlClient.MetaType.GetMetaTypeFromType(Type dataType)
   at Microsoft.Data.SqlClient.SqlParameter.GetMetaTypeOnly()
   at Microsoft.Data.SqlClient.SqlParameter.get_DbType()
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlServerDialect.ReloadSqlParameters(DbContext context, List`1 sqlParameters)
   at EFCore.BulkExtensions.BatchUtil.ReloadSqlParameters(DbContext context, List`1 sqlParameters)
   at EFCore.BulkExtensions.BatchUtil.GetSqlUpdate[T](IQueryable`1 query, DbContext context, Type type, Expression`1 expression)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.GetBatchUpdateArguments[T](IQueryable`1 query, Object updateValues, List`1 updateColumns, Expression`1 updateExpression, Type type)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchUpdateAsync[T](IQueryable`1 query, Expression`1 updateExpression, Type type, CancellationToken cancellationToken)
```
