### ISSUE TITLE
BulkInsertOrUpdate Fail

### ISSUE THREAD

**Issue by Tiloran** [borisdj/EFCore.BulkExtensions#294]
Core 3.1, EF 3.1.1, BulkExten 3.1.0
Error occur only in BulkInsertOrUpdate, when insert, update works fine. Same at async method.
Separatly BulkInsert and BulkUpdate works fine.

```
using (var db = new ApplicationDbContext())
            {
                PersonsLostPassports passport = new PersonsLostPassports();
                    passport.Id = 200446956114700904;
                    passport.Ovd = "ДЕРЖАВНА МІГРАЦІЙНА СЛУЖБА УКРАЇНИ";
                    passport.D_series = "EC";
                    passport.D_number = "510962";
                    passport.D_type = "ПАСПОРТ ГРОМАДЯНИНА УКРАЇНИ ДЛЯ ВИЇЗДУ ЗА КОРДОН";
                    passport.D_status = "ВИЗНАНО НЕДІЙСНИМ";
                    passport.Theft_data = new DateTime(2020, 02, 18);
                    passport.Insert_date = new DateTime(2020, 02, 13);
                    passport.Full_numbur_hash = Guid.Parse("6211B62B-7453-8E01-3911-CE50EA141E69");
                    passport.ReestrId = 1;
                    passport.Hash_row = Guid.Parse("126A4DD5-F483-A264-576E-5F901405DA49");
                    passport.Date_create = new DateTime(2020, 02, 18);
                    List<PersonsLostPassports> passports = new List<PersonsLostPassports>();
                    passports.Add(passport);
                    db.BulkInsertOrUpdate(passports,
                        new BulkConfig {BulkCopyTimeout = 10000, BatchSize = 10000});
            }
```
```
public class PersonsLostPassports
    {
        public long Id { get; set; }
        public string Ovd { get; set; }
        public string D_series { get; set; }
        public string D_number { get; set; }
        public string D_type { get; set; }
        public string D_status { get; set; }
        public DateTime? Theft_data { get; set; }
        public DateTime? Insert_date { get; set; }
        public Guid Full_numbur_hash { get; set; } 
        public int ReestrId { get; set; }
        public Guid Hash_row { get; set; }
        public DateTime Date_create { get; set; }
    }
```
```
Microsoft.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'Id', table 'wdt.dbo.PersonsLostPassports'; column does not allow nulls. UPDATE fails.
The statement has been terminated.
  at at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
  at at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
  at at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
  at at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
  at at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
  at at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
  at at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
  at at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
  at at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRaw(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters)
  at at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRaw(DatabaseFacade databaseFacade, String sql, Object[] parameters)
  at at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
  at at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
  at at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsertOrUpdate[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress)
  at ConsoleApp12.Program.Main(String[] args) in C:\WEB\TempProjects\ConsoleApp12\ConsoleApp12\Program.cs:40
```
Table [dbo].[PersonsLostPassports]
![image](https://user-images.githubusercontent.com/18645714/74738360-664e4e00-525f-11ea-8c4b-a1c782728f1d.png)

**Comment by borisdj** [comment]
I've just tested this and it works, however I have used latest version 3.1.1.
Try with that one.

**Comment by Tiloran** [comment]
Yes, now it work.
