### ISSUE TITLE
BatchUpdateAsync generates invalid SQL query with Sqlite

### ISSUE THREAD

**Issue by Manny651** [borisdj/EFCore.BulkExtensions#303]
BatchUpdateAsync generates an invalid statement when used with Sqlite.

Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'near "" AS ("": syntax error'.
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRawAsync(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchUpdateAsync[T](IQueryable`1 query, T updateValues, List`1 updateColumns, CancellationToken cancellationToken)

**Comment by borisdj** [comment]
Merged and NuGet 3.1.1 published.
