### ISSUE TITLE
SQLite In-Memory  'no such table: INFORMATION_SCHEMA.COLUMNS'

### ISSUE THREAD

**Issue by ppittle** [borisdj/EFCore.BulkExtensions#308]
Cross posting with this StackOverflow question: https://stackoverflow.com/questions/60690567/efcore-bulk-insert-sqlite-in-memory-no-such-table-information-schema-columns

I'm using [EFCore BulkExtensions](https://github.com/borisdj/EFCore.BulkExtensions)`2.5.0` with EntityFrameworkCore `2.2.3` and EFCore.SQLite `2.2.6`.

I have some code like:

```csharp
public class UserRepository
{
   private readonly IDbContextProvider<ReportContext> _dbContextProvider;
  
   public async Sync(IList<User> users)
   { 
        await _dbContextProvider.Context.BulkInserOrUpdateAsync(users);
   }
}
```

My application code (which uses EFCore.Sql) runs this just fine.  But when my test code runs using SQLite In-Memory, I get an exception:  **'no such table: INFORMATION_SCHEMA.COLUMNS'**

```
Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'no such table: INFORMATION_SCHEMA.COLUMNS'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.TableInfo.CheckHasIdentityAsync(DbContext context, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlBulkOperation.MergeAsync[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
   at MyCode.Repositories.UserRepository.<>c__DisplayClass5_0.<<Sync>b__0>d.MoveNext() in C:\projects\MyCode\Repositories\UserRepository.cs:line 48
```

`INFORMATION_SCHEMA.COLUMNS` isn't part of my data model and isn't something I'm trying to create or work with.  Do I need to configure or tweak EF Core or SQLite to get it to support Bulk Operations when operation in-memory mode?

I've tried [turning on EF core logging](https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging?tabs=v3) and can see my Db Model being processed and tables being created, but no output on the Bulk Operations, so I'm unsure what generated sql statements are looking for this Information_Schema.Columns table.

**Comment by ppittle** [comment]
Fixed this by updating to `2.6.4`.  

Looks like it was fixed here: https://github.com/borisdj/EFCore.BulkExtensions/commit/32c80df7d4766b87e13252a81a69ce4f5aeb62a1#diff-2890413287118f31c41d64aca4a5970d
