### ISSUE TITLE
BulkInsert using EFCore.BulkExtensions 3.1.1  i am getting CREATE TABLE permission denied in database '*******' error

### ISSUE THREAD

**Issue by karthikmuthukarungu** [borisdj/EFCore.BulkExtensions#324]
I have the same issue when inserting records using BulkInsert. In my local it is working fine. But when i am hosting in server i am getting below error. At the same time i have tried with UseTempDB = true also. Still i am getting below error.

Could you please assist on this.

Source Code:

		using (var bulkInsertTransaction = DbContext.Database.BeginTransaction())
                {
                    var bulkConfig = new BulkConfig { PreserveInsertOrder = true, SetOutputIdentity = true, UseTempDB = true };
                    DbContext.BulkInsert(MyRecords, bulkConfig);
                    bulkInsertTransaction.Commit();
                    foreach (var item in MyRecords)
                    {
                        MyIds.Add(item.MyRecordsId);
                    }
                }

Error:

Microsoft.Data.SqlClient.SqlException (0x80131904): CREATE TABLE permission denied in database '*******'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRaw(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters)
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsert[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress)
   at

**Comment by borisdj** [comment]
You code sample with `UseTempDB = true` seems fine.
It should work, i'm not sure why you still get the exception.
