### ISSUE TITLE
InvalidCastException when update with where in

### ISSUE THREAD

**Issue by kjeske** [borisdj/EFCore.BulkExtensions#327]
An InvalidCastExpression is thrown when using UpdateAsync with WHERE IN. For example:

```c#
await db.Posts
    .Where(x => postIds.Contains(x.Id))
    .UpdateAsync(x => new Post { x.ItemsCount = 0 });
// InvalidCastException
```

Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
System.InvalidCastException: Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlParameterExpression' to type 'Microsoft.EntityFrameworkCore.Query.SqlExpressions.SqlConstantExpression'.
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitIn(InExpression inExpression)
   at Microsoft.EntityFrameworkCore.Query.SqlExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
   at Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GetCommand(SelectExpression selectExpression)
   at EFCore.BulkExtensions.IQueryableExtensions.ToParametrizedSql[TEntity](IQueryable`1 query)
   at EFCore.BulkExtensions.IQueryableExtensions.ToSql[TEntity](IQueryable`1 query)
   at EFCore.BulkExtensions.BatchUtil.GetBatchSql[T](IQueryable`1 query, DbContext context, Boolean isUpdate)
   at EFCore.BulkExtensions.BatchUtil.GetSqlUpdate[T](IQueryable`1 query, DbContext context, Expression`1 expression)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchUpdateAsync[T](IQueryable`1 query, Expression`1 updateExpression, CancellationToken cancellationToken)
```

**Comment by borisdj** [comment]
I don't see which Extension method here you are using, Bulk or Batch, and could you give entire example where this would be reproducible.

**Comment by Jonatthu** [comment]
@borisdj  it fails when descriptionList is coming from an Array instance
