### ISSUE TITLE
Cannot bulk insert into a TPH while explicitly setting the discriminator column as a `bool` 

### ISSUE THREAD

**Issue by benm-eras** [borisdj/EFCore.BulkExtensions#369]
I have an entity which is either "custom" or "generic". The "custom" version inherits from the "generic" version and adds a few new properties. Given the simple relationship I didn't want the default discriminator column being added as a string when a boolean would do, so I specified my entities and discriminator like this:

```csharp
public class Scale
{
  [Key]
  public int Id { get; set; }

  // other stuff
}

public class CustomScale : Scale
{
  public int ExtraThing { get; set; }
}

// in my db context
protected override void OnModelCreating(ModelBuilder builder)
{
  builder.Entity<Scale>(e =>
  {
    e.HasDiscriminator<bool>("Custom")
      .HasValue<Scale>(false)
      .HasValue<CustomScale>(true);
  });
}
```

Whenever I try and insert into this with `BulkInsertAsync` I get the following error:

```
Unhandled exception. System.InvalidOperationException: The given value of type String from the data source cannot be converted to type bit of the specified target column.
 ---> System.FormatException: Failed to convert parameter value from a String to a Boolean.
 ---> System.FormatException: String 'Scale' was not recognized as a valid Boolean.
   at System.Boolean.Parse(ReadOnlySpan`1 value)
   at System.Boolean.Parse(String value)
   at System.String.System.IConvertible.ToBoolean(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Microsoft.Data.SqlClient.SqlParameter.CoerceValue(Object value, MetaType destinationType, Boolean& coercedToDataFeed, Boolean& typeChanged, Boolean allowStreaming)
   --- End of inner exception stack trace ---
   at Microsoft.Data.SqlClient.SqlParameter.CoerceValue(Object value, MetaType destinationType, Boolean& coercedToDataFeed, Boolean& typeChanged, Boolean allowStreaming)
   at Microsoft.Data.SqlClient.SqlBulkCopy.ConvertValue(Object value, _SqlMetaData metadata, Boolean isNull, Boolean& isSqlType, Boolean& coercedToDataFeed)
   --- End of inner exception stack trace ---
   at EFCore.BulkExtensions.SqlBulkOperation.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlBulkOperation.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlBulkOperation.InsertAsync[T](DbContext context, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
```

There are no columns called `Scale`, so I do not really know what that is referencing on the 3rd line of that (`String 'Scale' was not recognized as a valid Boolean.`), but the only thing that is a boolean and has anything to do with these entities/tables is that discriminator column.

I have tried the suggestions [here](https://github.com/borisdj/EFCore.BulkExtensions#tph-inheritance) of adding the entities to the context before calling `BulkInsert` but the result was the same.

Simply adding the discriminator column as a property of my entity allows me to proceed without error, but I would rather not have to do that.

```csharp
public class Scale
{
  [Key]
  public int Id { get; set; }

  // other stuff

  public bool Custom { get; set; } // <- added this to make it work
}
```

**Comment by borisdj** [comment]
I think you should just keep Discriminator column to _sting_ type.

**Comment by benm-eras** [comment]
So a >80 bit string instead of a 1bit bool?! Granted that is unlikely to be an issue with my current scenario but I can see that it could easily be a concern in other situations.
