### ISSUE TITLE
System.ArgumentOutOfRangeException when BulkInsertOrUpdate

### ISSUE THREAD

**Issue by Bo-Yee-Woods** [borisdj/EFCore.BulkExtensions#42]
Hi,

I got System.ArgumentOutOfRangeException: 'StartIndex cannot be less than zero.'
 when run below codes.

       _db.BulkInsertOrUpdate(hotelSegments, new BulkConfig { BatchSize = hotelSegments.Count });

Stack Trace:

      at System.String.Remove(Int32 startIndex, Int32 count)
      at EFCore.BulkExtensions.SqlQueryBuilder.GetCommaSeparatedColumns(List`1 columnsNames, String prefixTable, String equalsTable)
      at EFCore.BulkExtensions.SqlQueryBuilder.MergeTable(TableInfo tableInfo, OperationType operationType)
      at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
      at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsertOrUpdate[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress)

**Comment by Bo-Yee-Woods** [comment]
I found that "GetCommaSeparatedColumns" cannot handle the case when a table whose all columns are primary keys

**Comment by borisdj** [comment]
I have confirmed the bug.
It will be fixed in a few days.

**Comment by borisdj** [comment]
Fixed with latest version.
