### ISSUE TITLE
BulkInsert - Null Exceptions on version >= 3.2.0

### ISSUE THREAD

**Issue by brenwebber** [borisdj/EFCore.BulkExtensions#427]
As part of upgrading to .Net 5, we are upgrading all other referenced packages, including upgrading `EFCore.BulkExtensions` from version 3.1.6 to 3.2.5.

After the upgrade we started getting Null Exceptions for our `BulkInsertAsync` calls. I've tried to troubleshoot but I'm not having much luck. Maybe I am missing something required when upgrading to 3.2?

Version 3.1.6 still works fine (on .Net 5), so we will stick with that for now. Here is the stack trace for the error which changed for version 3.2.4:

**NullReferenceException - Version 3.2.4 - 3.2.5**
```
System.NullReferenceException: Object reference not set to an instance of an object.
 at lambda_method1962(Closure , Object )
 at EFCore.BulkExtensions.SqlBulkOperation.GetDataTable[T](DbContext context, Type type, IList`1 entities, SqlBulkCopy sqlBulkCopy, TableInfo tableInfo)
 at EFCore.BulkExtensions.SqlBulkOperation.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
 at EFCore.BulkExtensions.SqlBulkOperation.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
 at EFCore.BulkExtensions.SqlBulkOperation.InsertAsync[T](DbContext context, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
```

**ArgumentNullException - Version 3.2.0 - 3.2.3**
```
System.ArgumentNullException: Value cannot be null. (Parameter 'method')
 at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0)
 at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
 at EFCore.BulkExtensions.FastProperty.InitializeSet()
 at EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, Type type, IList`1 entities, Boolean loadOnlyPKColumn)
 at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
 at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
 at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
 at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsertAsync[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
```

**Comment by borisdj** [comment]
Dupe https://github.com/borisdj/EFCore.BulkExtensions/issues/405
