### ISSUE TITLE
BatchDelete does not work with FromSqlRaw sub-expressions

### ISSUE THREAD

**Issue by Arithmomaniac** [borisdj/EFCore.BulkExtensions#431]
Using EFCore.BulkExtensions version 3.2.5 on net472, See the following code sample:

```csharp
static class Tester
{
    const string connectionString = "Data Source=.;Integrated Security=SSPI;Initial Catalog=EFBulk-Test";

    public static void Test()
    {
        var dbContext = new TestContext();
        try
        {
            dbContext.Database.EnsureCreated();
            var stringSplitQueryable = dbContext.Set<EFBulkStringSplitEntry>()
                        .FromSqlRaw(@"SELECT ID = CAST(value as int) FROM STRING_SPLIT('1', ',')").Select(x => x.ID);

            var filteredTable = dbContext.Set<EFBulkTableEntry>().Where(x => !stringSplitQueryable.Contains(x.ID));

            var results = filteredTable.ToList();
            var (sql, sqlParameters) = BatchUtil.GetSqlDelete(filteredTable, dbContext);
            var countDeleted = filteredTable.BatchDelete();
        }
        finally
        {
            dbContext.Database.EnsureDeleted();
        }
    }

    class TestContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseLoggerFactory(new LoggerFactory(new[] { new DebugLoggerProvider() }))
                .UseSqlServer(connectionString);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<EFBulkTableEntry>().Property(x => x.ID).ValueGeneratedNever();
            modelBuilder.Entity<EFBulkTableEntry>().HasKey(x => x.ID);
            modelBuilder.Entity<EFBulkStringSplitEntry>().HasNoKey();
        }
    }

    class EFBulkTableEntry  { public int ID { get; set; } }
    class EFBulkStringSplitEntry  { public int ID { get; set; } }
}
```

EF 3.1.8 can handle this fine; the following is logged while populating `results`:
```sql
SELECT [e].[ID]
FROM [EFBulkTableEntry] AS [e]
WHERE [e].[ID] NOT IN (
    SELECT [e0].[ID]
    FROM (
        SELECT ID = CAST(value as int) FROM STRING_SPLIT('1', ',')
    ) AS [e0]
)
```

Which closely matches `sql`:
```sql
DELETE [e]
FROM [EFBulkTableEntry] AS [e]
WHERE [e].[ID] NOT IN (
    SELECT [e0].[ID]
    FROM (
        SELECT ID = CAST(value as int) FROM STRING_SPLIT('1', ',')
    ) AS [e0]
)
```

However, `sqlParameters`, instead of being empty, is a list with a "dud" parameter:
```
//the following is abbreviated output from Immediate Window
sqlParameters[0]
{@__p_0}
    DbType: '((Microsoft.Data.SqlClient.SqlParameter)sqlParameters[0]).DbType' threw an exception of type 'System.ArgumentException'
    ParameterName: "@__p_0"
    SqlDbType: '((Microsoft.Data.SqlClient.SqlParameter)sqlParameters[0]).SqlDbType' threw an exception of type 'System.ArgumentException'
    SqlValue: null
    Value: {object[0]}
```

Which causes an exception when running `BatchDelete`:
```
System.ArgumentException
  HResult=0x80070057
  Message=No mapping exists from object type System.Object[] to a known managed provider native type.
  Source=Microsoft.Data.SqlClient
  StackTrace:
   at Microsoft.Data.SqlClient.MetaType.GetMetaTypeFromValue(Type dataType, Object value, Boolean inferLen, Boolean streamAllowed)
   at Microsoft.Data.SqlClient.SqlParameter.GetMetaTypeOnly()
   at Microsoft.Data.SqlClient.SqlParameter.get_DbType()
   at Microsoft.EntityFrameworkCore.Storage.Internal.DbParameterCollectionExtensions.<>c__DisplayClass0_0.<FormatParameters>b__0(DbParameter p)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join[T](String separator, IEnumerable`1 values)
   at Microsoft.EntityFrameworkCore.Storage.Internal.DbParameterCollectionExtensions.FormatParameters(DbParameterCollection parameters, Boolean logParameterValues)
   at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.LogCommandError(IDiagnosticsLogger`1 diagnostics, DbCommand command, TimeSpan duration, EventDefinition`6 definition)
   at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.CommandError(IDiagnosticsLogger`1 diagnostics, IRelationalConnection connection, DbCommand command, DbContext context, DbCommandMethod executeMethod, Guid commandId, Guid connectionId, Exception exception, DateTimeOffset startTime, TimeSpan duration)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRaw(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchDelete(IQueryable query)
   ...
```

**Comment by borisdj** [comment]
Batch ops do not support with RawSql.
If you are using RawSql then there Update/Delete can be written directly.

**Comment by Arithmomaniac** [comment]
It's more important as a small component of a much larger query. The actual statement was something like
```sql
WITH Raw_Sql_Expression AS (/*.....*/)
UPDATE Widgets 
SET DateSold = {DateTime.Today} 
WHERE DateSold IS NULL 
AND ID NOT IN (SELECT ID FROM Raw_Sql_Expression)
```
 
I'd like to write Something like 
```csharp
Widgets
   .Where(x => x.DateSold == null && Raw_Sql_Queryable.Contains(x.ID))
   .BatchUpdate(new Widget {DateSold = DateTime.Today})
```

Would you accept a PR with this sort of support? (No promises I'd actually work on it.)

**Comment by borisdj** [comment]
If you manage to work it out, you are welocme to make a pull

**Comment by Arithmomaniac** [comment]
Thanks. In the meantime, can you label it as "help wanted"?
