### ISSUE TITLE
How do I use BulkInsert to retrieve back existing ids?

### ISSUE THREAD

**Issue by ermirbeqiraj** [borisdj/EFCore.BulkExtensions#441]
I'm using this lib (great lib) in my project. 
Case is like this: 
- InsertOrUpdate (which works fine)
- Insert (which throws, or returns blank input collection)

here are few rows:

```
var bulkConfigContact = new BulkConfig
{
    BatchSize = _batchSize,
    CalculateStats = true,
    PreserveInsertOrder = true,//message.UpdateExistingData,
    SetOutputIdentity = true,
    TrackingEntities = true,
    UpdateByProperties = new List<string> { nameof(Contacts.Core.Entities.Contact.ClientId), nameof(Contacts.Core.Entities.Contact.Email) },
};

  if (message.UpdateExistingData) // this works great
      _context.BulkInsertOrUpdate(dbContacts, bulkConfigContact);
  else // I need this for cases when no update is needed if the row already exists
      _context.BulkInsert(dbContacts, bulkConfigContact);
```

- When `PreservceInsertOrder` is set to `False`, the collection `dbContacts` is empty (as all the rows already found in db).
- When `PreservceInsertOrder` is set to `True`, the lib throws with `Index out of range exception`

   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException() in /_/src/System.Private.CoreLib/shared/System/ThrowHelper.cs:line 95
   at System.Collections.Generic.List`1.get_Item(Int32 index) in /_/src/System.Private.CoreLib/shared/System/Collections/Generic/List.cs:line 154
   at EFCore.BulkExtensions.TableInfo.UpdateEntitiesIdentity[T](Type type, IList`1 entities, IList`1 entitiesWithOutputIdentity)
   at EFCore.BulkExtensions.TableInfo.LoadOutputData[T](DbContext context, Type type, IList`1 entities)
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsert[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress)

thanks :)

**Comment by borisdj** [comment]
First read in details README, segment:

> When using PreserveInsertOrder with SetOutputIdentity Id value does matter....

If you still don't find the solution, then could you write entire code snipped similar to existing test where this would issue be reproducible.
