### ISSUE TITLE
The type initializer for 'EFCore.BulkExtensions.BatchUtil' threw an exception

### ISSUE THREAD

**Issue by lionthefox** [borisdj/EFCore.BulkExtensions#468]
### Description
After updating from 3.2.7 to 3.3.1 BatchUpdateAsync<T>() throws an exception at EFCore.BulkExtensions.BatchUtil..cctor(). Same happens in 3.3.0. Works fine again, after downgrading to 3.2.7. Looks like a namespace problem.
### Exception
Exception message: The type initializer for 'EFCore.BulkExtensions.BatchUtil' threw an exception.
Stack trace:
  ```at EFCore.BulkExtensions.BatchUpdateCreateBodyData..ctor(String baseSql, DbContext dbContext, IEnumerable`1 innerParameters, IQueryable query, Type rootType, String tableAlias, LambdaExpression updateExpression)
   at EFCore.BulkExtensions.BatchUtil.GetSqlUpdate[T](IQueryable query, DbContext context, Type type, Expression`1 expression)
   at EFCore.BulkExtensions.BatchUtil.GetSqlUpdate[T](IQueryable`1 query, DbContext context, Expression`1 expression)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchUpdateAsync[T](IQueryable`1 query, Expression`1 updateExpression, CancellationToken cancellationToken)
   at ...
InnerException:
Ambiguous match found.
   at System.RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at EFCore.BulkExtensions.BatchUtil..cctor()```

### Further technical details
- EF version: 5.0.3

**Comment by ifgitman** [comment]
Same for me, using EF.Sqlite 5.0.3

**Comment by LeaFrock** [comment]
Same for me, using EF Core  5.0.3  based on SQL Server.

**Comment by borisdj** [comment]
Fixed
