### ISSUE TITLE
Unable to cast object of type 'System.Int64' to type 'System.Int32' - Problem in 3.4.1

### ISSUE THREAD

**Issue by Shusty-6th** [borisdj/EFCore.BulkExtensions#489]
After updating from 3.4.0 to 3.4.1, I have an error calling UpdateBulk and UpdateBulkAsync. My entity's primary key is long. I checked twice by downgrade to version 3.4.0 where everything works and update to 3.4.1 which always showed the following error:

{Message: "Unable to cast object of type 'System.Int64' to type 'System.Int32'.", 
Source: "EFCore.BulkExtensions" 
StackTrace: ExceptionType: "System.InvalidCastException", InnerException: null, StackTrace: "   at EFCore.BulkExtensions.TableInfo.CheckToSetIdentityForPreserveOrder[T](IList`1 entities, Boolean reset)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlBulkOperation.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlBulkOperation.MergeAsync[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)  ...}

**Comment by borisdj** [comment]
Should be now fixed with 3.4.2
