### ISSUE TITLE
Custom int array value converter

### ISSUE THREAD

**Issue by ziadakiki** [borisdj/EFCore.BulkExtensions#508]
Hello,
I have a value converter that converts int arrays to comma separated string for database storage and vice-versa. This is how the implementation looks:
```
var intArray = new ValueConverter<int[], string>(
    v => string.Join(",", v),
    v => Array.ConvertAll(v.Split(",", StringSplitOptions.RemoveEmptyEntries), c => int.Parse(c))
);
```
And is assigned to a Property as follows:
```
item.Property(i => i.IntArrayProperty).HasConversion(intArray);
```
When doing a `BulkInsertOrUpdateAsync`, I'm getting the following error:
```
No parameterless constructor defined for type 'System.Int32[]'.
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, Type type, IList`1 entities, Boolean loadOnlyPKColumn)
   at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
   at EFCore.BulkExtensions.DbContextBulkTransaction.<ExecuteAsync>d__1`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ... own code ...
```
I've found some similar scenarios involving `EnumToString` conversion but they don't seem to target this particular scenario.
Anything that could be done on this matter to solve the issue?

**Comment by borisdj** [comment]
I have tested this and it passes.
Also try again with the latest version from NuGet.
If the issue still occurs can you write entire example for test where this would be reproducible.
Or load the source of library into your project and debug it directly.

**Comment by ziadakiki** [comment]
Updating from 3.5.2 to 3.5.5 fixed the issue.
May I ask why the release cadence is very fast?

**Comment by borisdj** [comment]
Glad it's sorted.
I'm doing some larger refactoring so there have been several changes and fixes lately.

**Comment by ziadakiki** [comment]
Great to hear that. Is there a way to know which version might be considered as stable so we can jump onto it?

**Comment by borisdj** [comment]
Take the last one.

**Comment by ziadakiki** [comment]
I'm reopening the issue, when using `BulkInsertOrUpdateAsync`, I'm getting the following error:
```
The MERGE statement attempted to UPDATE or DELETE the same row more than once. This happens when a target row matches more than one source row. A MERGE statement cannot UPDATE/DELETE the same row of the target table multiple times. Refine the ON clause to ensure a target row matches at most one source row, or use the GROUP BY clause to group the source rows.
```
The database table already contains data.
Should I open another issue?

**Comment by borisdj** [comment]
If the issue is about ValueConverter then you can write it here, otherwise open new one.
In either case write entire code snipped example for test where it can be reproduced.
