### ISSUE TITLE
Error on BulkUpdate with Connect/ShowPlan permissions

### ISSUE THREAD

**Issue by jonathanford** [borisdj/EFCore.BulkExtensions#51]
I have a table that contains a unique, non-clustered, filter index. There are no identity columns or triggers.

When I try to do a bulk update I receive a "CREATE TABLE permission denied in database" error.

The database access is using SQL authentication and user is granted Connect and Show plan permissions. 

My current workaround is to grant Alter permission, however according to related [bcp utility](https://docs.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-2017) documentation:

> A bcp in operation minimally requires SELECT/INSERT permissions on the target table. In addition, ALTER TABLE permission is required if any of the following is true:
> 
> - Constraints exist and the CHECK_CONSTRAINTS hint is not specified. 
> - Triggers exist and the FIRE_TRIGGER hint is not specified. 
> - You use the -E option to import identity values from a data file.

I was expecting to specify only the SqlBulkCopyOptions.CheckConstraints flag so that Alter permission would not be required, however the error still occurs.

Additionally I have successfully been able to do bulk inserts with the same user into a different table without a unique index.

**Comment by borisdj** [comment]
From this info I don't think your Index have anything to do with this.
It only depends of Db permission and Bulk operation.
BulkInsert makes direct INSERT to table but BulkUpdate/BulkInsertOrUpdate have to CREATE temp table.
Your successful bulk insert worked, not because you have no Index in that table, but because it is INSERT.
I assume UPDATE on that table wouldn't work either.

So the error you received is just what it says:
**For UPDATE operation CREATE TABLE permission is required.**

**Comment by jonathanford** [comment]
What you say makes perfect sense, as a direct update with SqlBulkCopy is not possible without a staging table.

I did try CREATE TABLE first however received a different error (sorry I don't have it on hand), so had to grant ALTER instead. In any case I think this is a non-issue. EFCore.BulkExtensions is a great package by the way - it's made a real difference in performance!

**Comment by borisdj** [comment]
Glad we sorted it out, and that you find the library useful.
Closing the issue now.

**Comment by fatemehramezani** [comment]
Hi, I have the same issue. On my local machine, BulkDelete is working but when I deploy it to the server I get this error:
 CREATE TABLE permission denied in database '...'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommand(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters)
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkDelete[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress)
   at Database.Helper.DeleteByBulkDelete[T](DbContext context, IList`1 values, IEnvironment environment, DatabaseState databaseState)

**Comment by borisdj** [comment]
Try setting _BukConfig_ with `UseTempDB = true` if you can't give CREATE permission.

**Comment by fatemehramezani** [comment]
Thank you. How can I find more information about your algorithm? Why does it try to create a table?

**Comment by borisdj** [comment]
You entire SourceCode here on GitHub you can check it.
https://github.com/borisdj/EFCore.BulkExtensions/blob/8fb0a4665f2fcbf5eef81460d1f6ad93a722e689/EFCore.BulkExtensions/SqlBulkOperation.cs#L129
https://github.com/borisdj/EFCore.BulkExtensions/blob/8fb0a4665f2fcbf5eef81460d1f6ad93a722e689/EFCore.BulkExtensions/SqlQueryBuilder.cs#L10

**Comment by karthikmuthukarungu** [comment]
I have the same issue when inserting records using BulkInsert. In my local it is working fine. But when i am hosting in server i am getting below error. At the same time i have tried with UseTempDB = true also. Still i am getting below error.

Source Code:

		using (var bulkInsertTransaction = DbContext.Database.BeginTransaction())
                {
                    var bulkConfig = new BulkConfig { PreserveInsertOrder = true, SetOutputIdentity = true, UseTempDB = true };
                    DbContext.BulkInsert(MyRecords, bulkConfig);
                    bulkInsertTransaction.Commit();
                    foreach (var item in MyRecords
                    {
                        MyIds.Add(item.MyRecordsId);
                    }
                }


Could you please assist on this.

Microsoft.Data.SqlClient.SqlException (0x80131904): CREATE TABLE permission denied in database '*******'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRaw(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters)
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsert[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress)
   at

**Comment by plpilew** [comment]
The same issue occurred to me ("CREATE TABLE permission denied") when bulk updating on environments other than dev (no db_owner permission).
But I think that we are missing something here.

@borisdj : You said that BulkUpdate/BulkInsertOrUpdate operations require to CREATE temp table but in fact SQL Server does not require any additional permissions to create a temp table - a user who has read access to a database can create temp tables.
So I run SQL Server Profiler to investigate and saw that the SQL statement looks like this:
```
SELECT TOP 0 ........
INTO [dbo].[mytableTemp1e890839]
```

It turns out that the library does not use a temporary table, but a regular DB table. That's why it calls for "CREATE TABLE" permission. If instead it used a table name with hash (like **#mytableTemp1e890839**), it would probably work fine.

Is it a bug?

**Comment by plpilew** [comment]
@borisdj: Thanks for your answer, I confirm it fixes the issue - no more permission denied error.

But I also wanted to understand what is happening behind the scenes - does `UseTempDb` setting mean it uses a temp database or a temp table?

By tempDB I mean this database:

![image](https://user-images.githubusercontent.com/6641927/174276925-aba942dc-e073-4ff3-935c-03a70ac11957.png)

So does the library really use tempDB or just the setting name is a bit misguiding?

The ReadMe does not explain this, it only says that `UseTempDB` requires that BulkOperation has to be inside Transaction.
