### ISSUE TITLE
BatchUpdateAsync

### ISSUE THREAD

**Issue by YuliaCher** [borisdj/EFCore.BulkExtensions#568]
Could you please explain how to work with the method:
 public static async Task<int> BatchUpdateAsync(
      this IQueryable query,
      object updateValues,
      List<string> updateColumns = null,
      CancellationToken cancellationToken = default(CancellationToken));

How can we send to updateValues a list of elements? At the moment we get the error:  "Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')". But when we are working with one element (not in collection) everything works fine. 

Stake trace:
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, Type type, IList`1 entities, Boolean loadOnlyPKColumn)
   at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
   at EFCore.BulkExtensions.BatchUtil.GetSqlSetSegment(DbContext context, Type updateValuesType, Object updateValues, List`1 updateColumns, List`1 parameters)
   at EFCore.BulkExtensions.BatchUtil.GetSqlUpdate(IQueryable query, DbContext context, Object updateValues, List`1 updateColumns)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.GetBatchUpdateArguments[T](IQueryable`1 query, Object updateValues, List`1 updateColumns, Expression`1 updateExpression, Type type)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.<BatchUpdateAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Working example:**

`var queryTest = _context.Table1.
                    .Where(x => x.Id == Guid.Parse("A7BC52FF-48CA-4327-876F-02924BE5559A"));
                var obj = await queryTest.SingleAsync(cancellationToken);
                obj.Field1 = null;

                await _context.BatchUpdateAsync(
                    queryTest,
                    obj,
                    new List<string>
                    {
                        nameof(Table1.Field1)
                    },
                    cancellationToken);`

**Not working example:**
 
var queryTest = _context.Table1.
                    .Where(x => x.Id == Guid.Parse("A7BC52FF-48CA-4327-876F-02924BE5559A") || x.Id == Guid.Parse("2D4E5012-3E79-4198-BB43-00699F6C7DA4"));
                var obj = await queryTest.ToListAsync(cancellationToken);
                obj.ForEach(x=> x.Field1 = null);

                await _context.BatchUpdateAsync(
                    queryTest,
                    obj,
                    new List<string>
                    {
                        nameof(Table1.Field1)
                    },
                    cancellationToken);

**Comment by borisdj** [comment]
_BatchUpdate_ is analog for sql operation like:
```
UPDATE table_name
SET column1 = value1
WHERE condition;
```
So it can't be used when having a list with different values.

In that case for Update or Insert *Bulk* ops should be used, more info is in the ReadMe.
