### ISSUE TITLE
Execution Timeout Expired with bulk transaction

### ISSUE THREAD

**Issue by nepdev** [borisdj/EFCore.BulkExtensions#584]
Using EFCore.BulkExtensions version 3.6.3 with an EF Core 3.1 project, connecting to a relatively old SQL Server 2005 instance.

I have code nearly identical to the sample code under "SetOutputIdentity" in the GitHub documentation page. Below is the sample code, not my code - my code is much  longer, but nearly the same except I use context.BulkInsert() 3 times within the same transaction. You should be able to reproduce the issue using the sample code in the docs.

	using (var transaction = context.Database.BeginTransaction())
	{
	    context.BulkInsert(entities, new BulkConfig { SetOutputIdentity = true });
	    foreach (var entity in entities) {
	        foreach (var subEntity in entity.ItemHistories) {
	            subEntity.ItemId = entity.ItemId; // setting FK to match its linked PK that was generated in DB
	        }
	        subEntities.AddRange(entity.ItemHistories);
	    }
	    context.BulkInsert(subEntities);
	    transaction.Commit();
	}

The code works totally fine with 200,000 records. Now I have to load nearly 1 million records and the entire transaction takes nearly 10 minutes, and I get following error: 

        Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.

This is an error one typically gets on command timeouts. 

Stack Trace:

   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at Microsoft.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlBulkCopy.RunParser(BulkCopySimpleResultSet bulkCopyHandler)
   at Microsoft.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinuedOnSuccess(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServer(DataTable table, DataRowState rowState)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServer(DataTable table)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken, Boolean isAsync)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken, Boolean isAsync)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.Insert[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress)
   at EFCore.BulkExtensions.SqlBulkOperation.Insert[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)

I have tried setting the command timeout for EF Core in various ways. What  normally should work is 

        public SqlDataContext(DbContextOptions<SqlDataContext> options) : base(options) 
        {
            Database.SetCommandTimeout(3600);
        }

which would set the timeout to 1 hour.

If I use 

     dbContext.Database.GetCommandTimeout()

in various places inside the transaction, then I do get the value 3600 every time. But it times out after max 10 minutes which is more like 600 seconds. When I say 10 minutes it is the total transaction time, not the time of an individual bulk insert. That would assume it is the total transaction which times out, not an individual BulkInsert operation.

The last of the 3 BulkInsert operation is the longest and the error seems to occur approx 5 minutes into that last insert operation, so if the timeout is related to individual BulkInsert operation it might be timing out after 300 seconds.

Is the BulkExtension library settings its own timeouts? Can I influence them?
Failing that, is there any way to set timeout values on the transaction? 

On regular .Net transactions I can set timeout values, but the sample code uses "context.Database.BeginTransaction()" which has no overload to set timeouts. 

(That the SQL server version is quite old (2005) SHOULD not have anything to do with this because to my knowledge, timeouts are not usually handled/controlled by the server but rather the client environment.)

I queried dbo.sysprocesses table while the query was executing and I do not even see any long running query being executed on that server, but many short ones. That may be how EFCore.Bulkextensions works under the hood, but I cannot figure out what is timing out here.
It must be client code since the server isn't even busy.

**Comment by borisdj** [comment]
You could try with different BulkConfig settings, specifically
`BatchSize,`**`BulkCopyTimeout`**`, TrackingEntities, WithHoldlock`;
_`SqlBulkCopyOptions`_ Flags with one or more options:
`Default, KeepIdentity, CheckConstraints, TableLock, KeepNulls, FireTriggers, UseInternalTransaction`

Also am not sure how much effect has 2005 sql version, but newer are probably more efficient:
[sqlbulkcopy in 2005](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/902d16cf-367b-40f1-9b41-54ca07792520/sqlbulkcopy-in-a-c-app-causes-sql-server-2005-to-lock-up)

**Comment by nepdev** [comment]
I know  you closed it already - just wanted to add that I found the problem now - it was with the SQL server itself, so factually no error in BulkExtensions. Still curious why you would have closed this without any feedback.

**Comment by borisdj** [comment]
I've assumed it was because of 2005.
In case of something else it can be reopened.
Anyway glad you sorted it out.
