### ISSUE TITLE
InvalidOperationException when column name has different casing convention: 'The given ColumnMapping does not match up with any column in the source or destination.'

### ISSUE THREAD

**Issue by JoasE** [borisdj/EFCore.BulkExtensions#586]
Issue in both 3.6.1 and 5.2.6

When a column has the same name, but capitals in different places EF handles this without any custom configuration.
But when using the bulk extension an exception is thrown:

> InvalidOperationException: The given ColumnMapping does not match up with any column in the source or destination.

Consider the following model and sql table:

```csharp
public class Delivery
{
    public int DeliveryId { get; set; }
}
``` csharp

```sql
CREATE TABLE [dbo].[Deliveries] (
    [deliveryid] INT IDENTITY (1, 1) PRIMARY KEY NOT NULL,
);
```

Running the code below will throw an exception when using the bulk insert extension:
```csharp
class Program
{
    static async Task Main(string[] args)
    {
        var entities = new[] { new Delivery(), new Delivery(), new Delivery() };

        using var context = new TestDbContext();
        
        // Works fine
        context.AddRange(entities);
        await context.SaveChangesAsync();

        // Throws exception
        await context.BulkInsertAsync(entities);
    }
}
```

A workaround is specifying the column name explicitly:
```csharp
public class DeliveryConfiguration : IEntityTypeConfiguration<Delivery>
{
    public void Configure(EntityTypeBuilder<Delivery> builder)
    {
        builder.Property(d => d.DeliveryId).HasColumnName("deliveryid");
    }
}
```

Full exception:
```
Unhandled exception. System.InvalidOperationException: The given ColumnMapping does not match up with any column in the source or destination.
   at Microsoft.Data.SqlClient.SqlBulkCopy.AnalyzeTargetAndCreateUpdateBulkCommand(BulkCopySimpleResultSet internalResults)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
--- End of stack trace from previous location where exception was thrown ---
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken, Boolean isAsync)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken, Boolean isAsync)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken, Boolean isAsync)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlBulkOperation.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
   at EfBulkErrorMapping.Program.Main(String[] args)
```

**Comment by borisdj** [comment]
BulkExtensions are using **SqlBulkTools** which is [CaseSensitive](https://stackoverflow.com/questions/20228359/the-given-columnmapping-does-not-match-up-with-any-column-in-the-source-or-desti), so the only solution is one you already have, defining exact column name either with FluentApi or Annotations.
