### ISSUE TITLE
SetSynchronizeFilter expression is not translated to SQL on Unix systems

### ISSUE THREAD

**Issue by ReactiveThings** [borisdj/EFCore.BulkExtensions#593]
BulkInsertOrUpdateOrDeleteAsync method with bulk config SetSynchronizeFilter is not translated to SQL on Unix systems. 
I think this line is responsible for that issue.
https://github.com/borisdj/EFCore.BulkExtensions/blob/7f417b6810b02337789250f3dbffce5f62aecdf0/EFCore.BulkExtensions/SqlQueryBuilder.cs#L228

Probably we should use Environment.NewLine instead of hardcoded \r\n

**Comment by ReactiveThings** [comment]
Tests are failing on linux

> [xUnit.net 00:00:21.80]     EFCore.BulkExtensions.Tests.EFCoreBulkTestAsync.OperationsTestAsync(dbServer: SqlServer, isBulk: True) [FAIL]
  Failed EFCore.BulkExtensions.Tests.EFCoreBulkTestAsync.OperationsTestAsync(dbServer: SqlServer, isBulk: True) [8 s]
  Error Message:
   Assert.Equal() Failure
Expected: 4999
Actual:   5000
  Stack Trace:
     at EFCore.BulkExtensions.Tests.EFCoreBulkTestAsync.RunInsertOrUpdateOrDeleteAsync(Boolean isBulk) in /workspaces/EFCore.BulkExtensions/EFCore.BulkExtensions.Tests/EFCoreBulkTestAsync.cs:line 277
   at EFCore.BulkExtensions.Tests.EFCoreBulkTestAsync.OperationsTestAsync(DbServer dbServer, Boolean isBulk) in /workspaces/EFCore.BulkExtensions/EFCore.BulkExtensions.Tests/EFCoreBulkTestAsync.cs:line 43
--- End of stack trace from previous location ---
[xUnit.net 00:01:02.21]     EFCore.BulkExtensions.Tests.EFCoreBulkTest.OperationsTest(dbServer: SqlServer, isBulk: True) [FAIL]
  Failed EFCore.BulkExtensions.Tests.EFCoreBulkTest.OperationsTest(dbServer: SqlServer, isBulk: True) [7 s]
  Error Message:
   Assert.Equal() Failure
Expected: 4999
Actual:   5000
  Stack Trace:
     at EFCore.BulkExtensions.Tests.EFCoreBulkTest.RunInsertOrUpdateOrDelete(Boolean isBulk) in /workspaces/EFCore.BulkExtensions/EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs:line 283
   at EFCore.BulkExtensions.Tests.EFCoreBulkTest.OperationsTest(DbServer dbServer, Boolean isBulk) in /workspaces/EFCore.BulkExtensions/EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs:line 41

Failed!  - Failed:     2, Passed:    53, Skipped:     0, Total:    55, Duration: 1 m 19 s - /workspaces/EFCore.BulkExtensions/EFCore.BulkExtensions.Tests/bin/Debug/net5.0/EFCore.BulkExtensions.Tests.dll (net5.0)

**Comment by borisdj** [comment]
PR merged and v5.2.9 published.
Thx for contrib.
