### ISSUE TITLE
Any way for BulkRead to retrieve Timestamp/RowVersion?

### ISSUE THREAD

**Issue by adr-v** [borisdj/EFCore.BulkExtensions#600]
The value for a Timestamp/RowVersion column doesn't seem to be retrieved when using BulkRead, Any way to achieve that?

**Comment by vnikopol** [comment]
I have the same problem in 3.2.5 version. In 3.6.2 there is another bug 
`Unhandled exception. System.InvalidOperationException: The given ColumnMapping does not match up with any column in the source or destination.
   at Microsoft.Data.SqlClient.SqlBulkCopy.AnalyzeTargetAndCreateUpdateBulkCommand(BulkCopySimpleResultSet internalResults) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlBulkCopy.cs:line 726
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlBulkCopy.cs:line 2810
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlBulkCopy.cs:line 3042
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlBulkCopy.cs:line 3101
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlBulkCopy.cs:line 2037
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServer(DataTable table, DataRowState rowState) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlBulkCopy.cs:line 1778
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServer(DataTable table) in /_/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlBulkCopy.cs:line 1751
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken, Boolean isAsync) in D:\ProjectsPriv\EFCore.BulkExtensions\EFCore.BulkExtensions\SQLAdapters\SQLServer\SqlServerAdapter.cs:line 63
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken, Boolean isAsync) in D:\ProjectsPriv\EFCore.BulkExtensions\EFCore.BulkExtensions\SQLAdapters\SQLServer\SqlServerAdapter.cs:line 90
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken, Boolean isAsync) in D:\ProjectsPriv\EFCore.BulkExtensions\EFCore.BulkExtensions\SQLAdapters\SQLServer\SqlServerAdapter.cs:line 101
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.ReadAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken, Boolean isAsync) in D:\ProjectsPriv\EFCore.BulkExtensions\EFCore.BulkExtensions\SQLAdapters\SQLServer\SqlServerAdapter.cs:line 323
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.ReadAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken, Boolean isAsync) in D:\ProjectsPriv\EFCore.BulkExtensions\EFCore.BulkExtensions\SQLAdapters\SQLServer\SqlServerAdapter.cs:line 359
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.Read[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress) in D:\ProjectsPriv\EFCore.BulkExtensions\EFCore.BulkExtensions\SQLAdapters\SQLServer\SqlServerAdapter.cs:line 293
   at EFCore.BulkExtensions.SqlBulkOperation.Read[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress) in D:\ProjectsPriv\EFCore.BulkExtensions\EFCore.BulkExtensions\SqlBulkOperation.cs:line 55
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress) in D:\ProjectsPriv\EFCore.BulkExtensions\EFCore.BulkExtensions\DbContextBulkTransaction.cs:line 35
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkRead[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress, Type type) in D:\ProjectsPriv\EFCore.BulkExtensions\EFCore.BulkExtensions\DbContextBulkExtensions.cs:line 138
   at Program.Main()`

**Comment by borisdj** [comment]
Try with latest 5.x version (v3 is not actively supported), you can check it in TimeStampTest:
https://github.com/borisdj/EFCore.BulkExtensions/blob/bcca7c93f5518ff82838c8af0afc3ed3509b4bfc/EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs#L146
