### ISSUE TITLE
Unable to cast object of type 'System.Int64' to type 'System.Decimal' (SetOutputIdentity = true)

### ISSUE THREAD

**Issue by willisga** [borisdj/EFCore.BulkExtensions#629]
Hello, thank you very much for the contribution to all.

Currently I use this library with the repository pattern and my entities have the Id property of decimal type as their primary key.

```CSharp
public class Entity : IEntityBase<decimal>
{
        public decimal Id { get; set; }
        public int IdUserCreator { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool State { get; set; }
        public DateTime DateCreated { get; set; }
}
```

The library generates the following exception when the SetOutputIdentity property of the BulkConfig class is true

**Message**:  Unable to cast object of type 'System.Int64' to type 'System.Decimal'
**StackTrace**
```
   at EFCore.BulkExtensions.FastProperty.Set(Object instance, Object value) in D:\Privado\Fuentes\EFCore.BulkExtensions\EFCore.BulkExtensions\FastProperty.cs:line 44
   at EFCore.BulkExtensions.TableInfo.CheckToSetIdentityForPreserveOrder[T](TableInfo tableInfo, IList`1 entities, Boolean reset) in D:\Privado\Fuentes\EFCore.BulkExtensions\EFCore.BulkExtensions\TableInfo.cs:line 728
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<InsertAsync>d__2`1.MoveNext() in D:\Privado\Fuentes\EFCore.BulkExtensions\EFCore.BulkExtensions\SQLAdapters\SQLServer\SqlServerAdapter.cs:line 37
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.Insert[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress) in D:\Privado\Fuentes\EFCore.BulkExtensions\EFCore.BulkExtensions\SQLAdapters\SQLServer\SqlServerAdapter.cs:line 26
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__5`1.MoveNext() in D:\Privado\Fuentes\EFCore.BulkExtensions\EFCore.BulkExtensions\SQLAdapters\SQLServer\SqlServerAdapter.cs:line 207
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__5`1.MoveNext() in D:\Privado\Fuentes\EFCore.BulkExtensions\EFCore.BulkExtensions\SQLAdapters\SQLServer\SqlServerAdapter.cs:line 288
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.Merge[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress) in D:\Privado\Fuentes\EFCore.BulkExtensions\EFCore.BulkExtensions\SQLAdapters\SQLServer\SqlServerAdapter.cs:line 114
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress) in D:\Privado\Fuentes\EFCore.BulkExtensions\EFCore.BulkExtensions\SqlBulkOperation.cs:line 41
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress) in D:\Privado\Fuentes\EFCore.BulkExtensions\EFCore.BulkExtensions\DbContextBulkTransaction.cs:line 43
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsert[T](DbContext context, IList`1 entities, Action`1 bulkAction, Action`1 progress, Type type) in D:\Privado\Fuentes\EFCore.BulkExtensions\EFCore.BulkExtensions\DbContextBulkExtensions.cs:line 26
   at Nexa.Data.EntityFramework.Core.CoreRepository`1.BulkInsert[TEntity](IList`1 data, Action`1 bulkAction, Action`1 progress) in D:\Privado\Fuentes\Sdk\Nexa.Data.EntityFramework\src\Nexa.Data.EntityFramework\Core\CoreRepository.cs:line 283
   at Nexa.Data.EntityFramework.Test.Tests.BathOperationsTest.<BulkInsert_WithActionBulkConfig>b__6_0(IEntityRepository repository) in D:\Privado\Fuentes\Sdk\Nexa.Data.EntityFramework\tests\Nexa.Data.EntityFramework.Test\Tests\BathOperationsTest.cs:line 206
   at Nexa.Data.EntityFramework.Test.ContextService.BuildEntityRepository(Action`1 process) in D:\Privado\Fuentes\Sdk\Nexa.Data.EntityFramework\tests\Nexa.Data.EntityFramework.Test\ContextService.cs:line 100
   at Nexa.Data.EntityFramework.Test.Tests.BathOperationsTest.BulkInsert_WithActionBulkConfig() in D:\Privado\Fuentes\Sdk\Nexa.Data.EntityFramework\tests\Nexa.Data.EntityFramework.Test\Tests\BathOperationsTest.cs:line 200
```

The way I solved it was adding the following code block to convert to decimal type.

```CSharp
else if (idType == typeof(decimal))
     idValue = (decimal)value;
```

**Class**: TableInfo
**Method**: CheckToSetIdentityForPreserveOrder
**Reference**: https://github.com/borisdj/EFCore.BulkExtensions/blob/0e14dfe545b3f549c0287c94fecca697c2e30bd2/EFCore.BulkExtensions/TableInfo.cs#L724

It would be nice if this change can be included in a future version.

Thanks

**Comment by borisdj** [comment]
Added with v5.3.9
Thx for contrib.

**Comment by loic-escudero** [comment]
Hello @borisdj,

First of all, big thanks for your work!

I've encountered a similar issue by using the PreserveInsertOrder (with a 'true' default value since this [commit](https://github.com/borisdj/EFCore.BulkExtensions/commit/a150819ab5b0746a73fa097c53f332d88d96f773)) on a Nullable<int> identity primary key (Id).

Class example : 

```
    public class LicenseError
    {
        [Key]
        public int? Id { get; set; }
        public int? BatchId { get; set; }
        [Column(TypeName= "varchar(255)")]
        public string BillingAccount { get; set; }
        public string UserName { get; set; }
        [Column(TypeName = "varchar(50)")]
        public string CountryCode { get; set; }
        [Column(TypeName = "varchar(255)")]
        public string SkuCode { get; set; }
        public int? Quantity { get; set; }
    }
```

Message: Unable to cast object of type 'System.Int64' to type 'System.Nullable`1[System.Int32]'
StackTrace:

```
TableInfo.CheckToSetIdentityForPreserveOrder[T](TableInfo tableInfo, IList`1 entities, Boolean reset)
SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
SqlBulkOperation.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
```

On my side, I solved the issue by setting PreserveInsertOrder to 'false' but it could be very useful to use this feature on a nullable int PK.

Thank you.
