### ISSUE TITLE
Sequence contains no matching element

### ISSUE THREAD

**Issue by willisga** [borisdj/EFCore.BulkExtensions#631]
Hello, thank you very much for solving the issue  [629](https://github.com/borisdj/EFCore.BulkExtensions/issues/629)

The following exception occurs when the destination table (Merge) is not associated with an entity.

Exception Line :
https://github.com/borisdj/EFCore.BulkExtensions/blob/e6cea2398b64a3d81fd38860e79857f75a16913d/EFCore.BulkExtensions/TableInfo.cs#L172

Message: Sequence contains no matching element
StackTrace: 
```
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at EFCore.BulkExtensions.TableInfo.<>c__DisplayClass159_0`1.<LoadData>b__3(String b)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, Type type, IList`1 entities, Boolean loadOnlyPKColumn)
   at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsertOrUpdate[T](DbContext context, IList`1 entities, Action`1 bulkAction, Action`1 progress, Type type)
   at Nexa.Data.EntityFramework.Core.CoreRepository`1.BulkInsertOrUpdate[TEntity](IList`1 data, Action`1 bulkAction, Action`1 progress)
   at Nexa.Microservice.Api.Outbound.EntityFramework.Repository.GenesysRepository.BulkInsertOrUpdateGenesys(List`1 data, Double percentageNotification, Action`3 progress) in D:\Privado\Fuentes\NexaPlus\Nexa.Microservice.Api.Outbound\src\Nexa.Microservice.Api.Outbound.EntityFramework\Repository\GenesysRepository.cs:line 53
   at Nexa.Microservice.Api.Outbound.EntityFramework.Repository.GenesysRepository.BulkInsertOrUpdateOperation(IList data, Double percentageNotification, Action`3 progress) in D:\Privado\Fuentes\NexaPlus\Nexa.Microservice.Api.Outbound\src\Nexa.Microservice.Api.Outbound.EntityFramework\Repository\GenesysRepository.cs:line 127
   at Nexa.Microservice.Api.Outbound.Logic.Services.Outbound.OutboundService.<>c__DisplayClass26_0`1.<BulkInsertOrUpdateAsync>b__0() in D:\Privado\Fuentes\NexaPlus\Nexa.Microservice.Api.Outbound\src\Nexa.Microservice.Api.Outbound.Logic\Services\Outbound\OutboundService.cs:line 347
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   
   ```
Here's an image to provide a bit of context 

![Dependence ](https://user-images.githubusercontent.com/16823804/133007108-48c2b859-f511-4004-8f4f-90e6b8e0ceed.png)

To solve the exception create an option in the bulk config that allows me to assign the name of the target table that I will assign in the merge without affecting the current TableInfo processes.

BulkConfig.cs: https://github.com/borisdj/EFCore.BulkExtensions/blob/master/EFCore.BulkExtensions/BulkConfig.cs
```
        public string DestinationMergeTableName { get; set; }
```

**Table Info.cs**
https://github.com/borisdj/EFCore.BulkExtensions/blob/master/EFCore.BulkExtensions/TableInfo.cs

Add Properties
![image](https://user-images.githubusercontent.com/16823804/133007406-1fffe9b9-2294-4604-ab25-5d04db934f69.png)

Update Method `LoadData<T>(DbContext context, Type type, IList<T> entities, bool loadOnlyPKColumn)`
![image](https://user-images.githubusercontent.com/16823804/133007382-33d18c38-eba3-422f-9129-48dd7e8ae2ca.png)

**SqlQueryBuilder.cs**
File: https://github.com/borisdj/EFCore.BulkExtensions/blob/master/EFCore.BulkExtensions/SqlQueryBuilder.cs

![image](https://user-images.githubusercontent.com/16823804/133007347-a98c9602-c823-41eb-9b65-563b9b76cd48.png)

Debugger:
![image](https://user-images.githubusercontent.com/16823804/133007228-a219d0ad-58c9-4f9d-bc0e-2822ceb7d6c7.png)

Query Result: 
![image](https://user-images.githubusercontent.com/16823804/133007314-12ec66fd-40b4-4743-a61f-72b2a5a9c42c.png)

I do not know if it is the correct way but I will be attentive to provide more information and to help in the most optimal solution defined by the repo administrator.

**Comment by borisdj** [comment]
BulkConfig has `CustomDestinationTableName`.
There is Example of usage in TablePerTypeInsertTest:
https://github.com/borisdj/EFCore.BulkExtensions/blob/e6cea2398b64a3d81fd38860e79857f75a16913d/EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs#L703
