### ISSUE TITLE
BulkInsert: InvalidOperationException when entity has more then one ownedType

### ISSUE THREAD

**Issue by rmelnikov2501** [borisdj/EFCore.BulkExtensions#671]
I have owned entity that is used two times in two classes like this:

```
    public class SomeOwnedEntity
    {
        public decimal Value { get; set; }
        public string Alpha3Code { get; set; }
    }

    public class MyEntity1
    {
        public int Id { get; set; }
        public virtual SomeOwnedEntity BasePricePerUnit { get; set; }
        public virtual SomeOwnedEntity ApplyedDiscountValue { get; set; }
    }

    public class MyEntity2
    {
        public int Id { get; set; }
        public virtual SomeOwnedEntity CostPricePerUnit { get; set; }
        public virtual SomeOwnedEntity BalanceCostPricePerUnit { get; set; }
    }
```

In this case BulkInsert throws exception:

> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, Type type, IList`1 entities, Boolean loadOnlyPKColumn) in D:\r.melnikov\Projects\External\EFCore.BulkExtensions\EFCore.BulkExtensions\TableInfo.cs:line 409

**Comment by borisdj** [comment]
Fixed with v6.1.2
