### ISSUE TITLE
BatchDelete fails with ArgumentException: No mapping exists from DbType UInt32 to a known SqlDbType

### ISSUE THREAD

**Issue by Arbalets** [borisdj/EFCore.BulkExtensions#683]
_System.ArgumentException: No mapping exists from DbType UInt32 to a known SqlDbType._ is thrown when passing uint parameter to BatchDelete or BatchDeleteAsync query.

``` charp
uint myId = 5;
await context.MyDbSet.Where(x => x.MyUintId == myId).BatchDeleteAsync();
```

Tested using SQLite and EFCore.BulkExtensions 6.1.5.
This is happening starting from EFCore.BulkExtensions 6.0.0 and up, with version 5.4.1 everything was fine.

Here's the call stack:
```
System.ArgumentException
No mapping exists from DbType UInt32 to a known SqlDbType.
   at Microsoft.Data.SqlClient.MetaType.GetMetaTypeFromDbType(DbType target)
   at Microsoft.Data.SqlClient.SqlParameter.set_DbType(DbType value)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.CreateParameter(DbCommand command, String name, Object value, Nullable`1 nullable)
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(DbCommand command, Object value)
   at EFCore.BulkExtensions.IQueryableExtensions.ToParametrizedSql(IQueryable query)
   at EFCore.BulkExtensions.BatchUtil.GetBatchSql(IQueryable query, DbContext context, Boolean isUpdate)
   at EFCore.BulkExtensions.BatchUtil.GetSqlDelete(IQueryable query, DbContext context)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.GetBatchDeleteArguments(IQueryable query)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchDeleteAsync(IQueryable query, CancellationToken cancellationToken)
```

**Comment by borisdj** [comment]
Unable to reproduce this, can you write a test for the issue.

**Comment by Arbalets** [comment]
> Unable to reproduce this, can you write a test for the issue.

[Here you go.](https://github.com/Arbalets/SqliteBatchDelete)

**Comment by borisdj** [comment]
Try v6.1.6

**Comment by Arbalets** [comment]
Problem solved, thanks
