### ISSUE TITLE
PostgreSql BulkInsert with decimal property use PrecisionAttribute fail

### ISSUE THREAD

**Issue by MoondanceZ** [borisdj/EFCore.BulkExtensions#703]
use ef core 6
throw exception `System.ArgumentException:“A PostgreSQL type with the name numeric(10,2) was not found in the database”`
My entity like this : 
```C#
public class Blog
{
    [Key]
    public int Id { get; set; }

    public string? Name { get; set; }

    [Precision(precision: 10, scale: 2)]
    public decimal Price { get; set; }
}
```
I think the `PostgreSqlAdapter.cs` may change like this :
```C#
// string is 'text' which works fine
if (columnType.StartsWith("character varying")) // when MaxLength is defined
    columnType = "character"; // 'character' is like 'string'
else if (columnType.StartsWith("varchar"))
    columnType = "varchar";
else if (columnType.StartsWith("numeric"))   //the columnType is 'numeric(10,2)', parse it to 'numeric'
    columnType = "numeric";
```

other problem in `PostgreSqlAdapter.cs`, is `(long)propertyValue`?
```C#
var convertibleDict = tableInfo.ConvertibleColumnConverterDict;
if (convertibleDict.ContainsKey(propertyColumnName) && convertibleDict[propertyColumnName].ModelClrType.IsEnum)
{
    if (propertyValue != null)
    {
        var clrType = tableInfo.ConvertibleColumnConverterDict[propertyColumnName].ProviderClrType;
        if (clrType == typeof(byte)) // columnType == "smallint"
            propertyValue = (byte)propertyValue;
        if (clrType == typeof(short))
            propertyValue = (short)propertyValue;
        if (clrType == typeof(Int32))
            propertyValue = (int)propertyValue;
        if (clrType == typeof(Int64))
            propertyValue = (int)propertyValue;   //Have a problem, is this long?????????????????
    }
}
```
I add a pr : https://github.com/borisdj/EFCore.BulkExtensions/pull/704/commits/028abbe849d277d2e15978d25df918e4707aa192

**Comment by fanshaohua-fan** [comment]
I have the same problem while the Column data types specified.

```csharp
public class SegmentCustomerEntity
    {
        public string Id { get; set; }
        [Column(TypeName = "VARCHAR(36)")]
        public string CustomerId { get; set; }
        public SegmentEntity Segment { get; set; }
        [Column(TypeName = "VARCHAR(36)")]
        public string SegmentId { get; set; }
    }
```

Exeception detail:
```
{System.ArgumentException: A PostgreSQL type with the name VARCHAR(36) was not found in the database
   at Npgsql.Internal.NpgsqlDatabaseInfo.GetPostgresTypeByName(String pgName)
   at Npgsql.TypeMapping.ConnectorTypeMapper.ResolveByDataTypeName(String typeName, Boolean throwOnError)
   at Npgsql.TypeMapping.ConnectorTypeMapper.ResolveByDataTypeName(String typeName)
   at Npgsql.NpgsqlParameter.ResolveHandler(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlBinaryImporter.Write[T](T value, NpgsqlParameter param, Boolean async, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SQLAdapters.PostgreSql.PostgreSqlAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken, Boolean isAsync)
   at EFCore.BulkExtensions.SQLAdapters.PostgreSql.PostgreSqlAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken, Boolean isAsync)
   at EFCore.BulkExtensions.SQLAdapters.PostgreSql.PostgreSqlAdapter.Insert[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress)
   at EFCore.BulkExtensions.SqlBulkOperation.Insert[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsert[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress, Type type)
   at segments.SegmentsService.CreateSegment(Segment request, ServerCallContext context) in /home/fan/repos/loyalty-cloud/src/segments-grpc/Services/SegmentsService.cs:line 242}
```

**Comment by MoondanceZ** [comment]
😂 maybe should ignoreCase while comparing.

**Comment by fanshaohua-fan** [comment]
Seems that's because I didn't define it properly. 😂
According to the [EFcore document](https://docs.microsoft.com/en-us/ef/core/modeling/entity-properties?tabs=data-annotations%2Cwithout-nrt#column-data-types) and [postgreSQL datetype](https://www.postgresql.org/docs/current/datatype-character.html)
It should be lower case **varchar** for PostgreSQL...

**Comment by borisdj** [comment]
Thx for contrib. and PR, v6.2.5 published.
