### ISSUE TITLE
On Batch operation involving list in Where clause, NpgsqlArrayListTypeMapping being used with non-Npgsql parameter type SqlParameter

### ISSUE THREAD

**Issue by angelsl** [borisdj/EFCore.BulkExtensions#706]
On EFCore.BulkExtensions 6.2.5 with Npgsql.EntityFrameworkCore.PostgreSQL 6.0.1, when I do something like this:

```cs
await _ctx.Items.Where(r => userIds.Contains(r.UserId)).BatchDeleteAsync();
```

where `userIds` is a `List<int>`, the following happens:

```
System.ArgumentException: Npgsql-specific type mapping Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping.NpgsqlArrayListTypeMapping being used with non-Npgsql parameter type SqlParameter
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping.NpgsqlArrayTypeMapping.ConfigureParameter(DbParameter parameter)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.CreateParameter(DbCommand command, String name, Object value, Nullable`1 nullable)
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(DbCommand command, Object value)
   at EFCore.BulkExtensions.IQueryableExtensions.ToParametrizedSql(IQueryable query)
   at EFCore.BulkExtensions.BatchUtil.GetBatchSql(IQueryable query, DbContext context, Boolean isUpdate)
   at EFCore.BulkExtensions.BatchUtil.GetSqlDelete(IQueryable query, DbContext context)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.GetBatchDeleteArguments(IQueryable query)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchDeleteAsync(IQueryable query, CancellationToken cancellationToken)
```

**Comment by borisdj** [comment]
Fixed with 6.2.6
