### ISSUE TITLE
Postgres BatchUpdate issues

### ISSUE THREAD

**Issue by IvanMarusic** [borisdj/EFCore.BulkExtensions#727]
Hi,

I get the following exception while trying to perform BatchUpdateAsync on JsonDocument property which is mapped on jsonb db column:

`System.ArgumentException: No mapping exists from object type System.Text.Json.JsonDocument to a known managed provider native type.
   at Microsoft.Data.SqlClient.MetaType.GetMetaTypeFromValue(Type dataType, Object value, Boolean inferLen, Boolean streamAllowed)
   at Microsoft.Data.SqlClient.MetaType.GetMetaTypeFromType(Type dataType)
   at Microsoft.Data.SqlClient.SqlParameter.GetMetaTypeOnly()
   at Microsoft.Data.SqlClient.SqlParameter.get_DbType()
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlServerDialect.ReloadSqlParameters(DbContext context, List``1 sqlParameters)
   at EFCore.BulkExtensions.BatchUtil.GetSqlUpdate(IQueryable query, DbContext context, Object updateValues, List``1 updateColumns)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.GetBatchUpdateArguments[T](IQueryable``1 query, Object updateValues, List``1 updateColumns, Expression``1 updateExpression, Type type)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchUpdateAsync(IQueryable query, Object updateValues, List``1 updateColumns, CancellationToken cancellationToken)`

This line of code throws the exception above: SqlServerDialect -> ReloadSqlParameters:
`var dt = sqlParameter.DbType;`

Regards

**Comment by borisdj** [comment]
Fixed with v6.3.0

**Comment by IvanMarusic** [comment]
Hi, issue still exists for the JsonDocument. I see that it has been fixed for the JsonElement, but JsonDocument still throws an exception.

`System.ArgumentException: No mapping exists from object type System.Text.Json.JsonDocument to a known managed provider native type.`

Regards

**Comment by borisdj** [comment]
Hello

> ili Zdravo, da ubacimo malo po naški :)
> Možeš li napisati test za ovaj problem.
> Meni prodje uredno za naredni primjer:

```C#
public class Doc
{
	public string Name { get; set; }
	public int Value { get; set; }
}
public class Item
{
	...
	public JsonDocument JsonDocument { get; set; }
}

var doc = new Doc() { Name = "Test", Value = 10 };
entities3[1].JsonDocument = JsonDocument.Parse(JsonSerializer.SerializeToUtf8Bytes(doc));
context.BulkUpdate(entities3, configUpdateBy);
```

**Comment by IvanMarusic** [comment]
Pozdrav, može :)

Samo kratki update da nisam pozivao BulkUpdate nego BatchUpdate. Mogu poslati primjer ukoliko i dalje kod tebe radi nakon BatchUpdate testa.

**Comment by borisdj** [comment]
v.6.3.3 ;)
