### ISSUE TITLE
BulkSaveChanges not working with PostgreSQL

### ISSUE THREAD

**Issue by MelnikovVA** [borisdj/EFCore.BulkExtensions#739]
Hello. I'm trying to insert records of entities of various types, some of which have a foreign key to entities from other tables that are also being inserted within the same business transaction. After preparing all the entities for insertion, I'm calling the BulkSaveChanges() method (the DBMS is PostgreSQL, using BulkExtensions 6.3.1). Regardless of the input data (in each case the entities have an integer primary key generated by the database) and BulkConfig configuration, I keep getting the following exception: 

`Cannot create a DbSet for 'object' because this type is not included in the model for the context.`

The stack trace is:
`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Cannot create a DbSet for 'object' because this type is not included in the model for the context.
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet1.System.Linq.IQueryable.get_Provider()
   at Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.FromSqlRaw[TEntity](DbSet1 source, String sql, Object[] parameters)
   at EFCore.BulkExtensions.SQLAdapters.PostgreSql.PostgreSqlAdapter.MergeAsync[T](DbContext context, Type type, IList1 entities, TableInfo tableInfo, OperationType operationType, Action1 progress, CancellationToken cancellationToken, Boolean isAsync) in EFCore.BulkExtensions\SQLAdapters\PostgreSql\PostgreSqlAdapter.cs:line 0
   at EFCore.BulkExtensions.SQLAdapters.PostgreSql.PostgreSqlAdapter.MergeAsync[T](DbContext context, Type type, IList1 entities, TableInfo tableInfo, OperationType operationType, Action1 progress, CancellationToken cancellationToken, Boolean isAsync) in EFCore.BulkExtensions\SQLAdapters\PostgreSql\PostgreSqlAdapter.cs:line 255
   at EFCore.BulkExtensions.SQLAdapters.PostgreSql.PostgreSqlAdapter.Merge[T](DbContext context, Type type, IList1 entities, TableInfo tableInfo, OperationType operationType, Action1 progress) in EFCore.BulkExtensions\SQLAdapters\PostgreSql\PostgreSqlAdapter.cs:line 140
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, Type type, IList1 entities, TableInfo tableInfo, OperationType operationType, Action1 progress) in EFCore.BulkExtensions\SqlBulkOperation.cs:line 41
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, Type type, IList1 entities, OperationType operationType, BulkConfig bulkConfig, Action1 progress) in EFCore.BulkExtensions\DbContextBulkTransaction.cs:line 48
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsert[T](DbContext context, IList1 entities, BulkConfig bulkConfig, Action1 progress, Type type) in EFCore.BulkExtensions\DbContextBulkExtensions.cs:line 15
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at EFCore.BulkExtensions.DbContextBulkTransactionSaveChanges.InvokeBulkMethod(DbContext context, List1 entities, Type entityType, String methodName, BulkConfig bulkConfig, Action1 progress, CancellationToken cancellationToken, Boolean isAsync) in EFCore.BulkExtensions\DbContextBulkTransactionSaveChanges.cs:line 183
   at EFCore.BulkExtensions.DbContextBulkTransactionSaveChanges.SaveChangesAsync(DbContext context, BulkConfig bulkConfig, Action1 progress, CancellationToken cancellationToken, Boolean isAsync) in EFCore.BulkExtensions\DbContextBulkTransactionSaveChanges.cs:line 133
   at EFCore.BulkExtensions.DbContextBulkTransactionSaveChanges.SaveChangesAsync(DbContext context, BulkConfig bulkConfig, Action1 progress, CancellationToken cancellationToken, Boolean isAsync) in EFCore.BulkExtensions\DbContextBulkTransactionSaveChanges.cs:line 165
   at EFCore.BulkExtensions.DbContextBulkTransactionSaveChanges.SaveChanges(DbContext context, BulkConfig bulkConfig, Action1 progress) in EFCore.BulkExtensions\DbContextBulkTransactionSaveChanges.cs:line 19
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, Type type, IList1 entities, OperationType operationType, BulkConfig bulkConfig, Action1 progress) in EFCore.BulkExtensions\DbContextBulkTransaction.cs:line 23
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkSaveChanges(DbContext context, BulkConfig bulkConfig, Action1 progress) in EFCore.BulkExtensions\DbContextBulkExtensions.cs:line 175`

After investigating the source code I've noticed that the reason for the exception is that the BulkInsert<T> method, which is called dynamically by reflection, always gets passed the "object" type as the generic type parameter by the InvokeBulkMethod, where one of the method parameters is defined as "List\<object> entities". This "object" generic type parameter value then gets passed down to the methods up to the MergeAsync<T> in PostgreSqlAdapter.
Then, there's this line 215 in PostgreSqlAdapter:
`var returningQuery = context.Set<T>().FromSqlRaw(sqlMergeTable);`
Since the method had been passed an IList<object> for the "entities" parameter, the inferred generic type value is "object", and we're going to try to return a DbSet<object> from the DbContext, which breaks everything unless it has such a property (but there's absolutely no use doing that, and it's also going to produce another exception). 

I think that a similar problem is going to occur in the SqlQueryBuilder file, at line 226, where a similar context.Set\<T>() call is made.

If you have any idea how to fix this (I guess there is a way to replace using the generic context.Set\<T>() method call with reflection, but I'm not sure how many changes it would require to be made) or get around it without having to resort to sequential calls of BulkInsert() (which would make my code kinda ugly, as opposed to a single SaveChanges() call), I'd appreciate it a lot.

P.S. I've noticed that the InsertPostgeSql test currently fails when run, you might want to take a look into that.

**Comment by borisdj** [comment]
Can confirm the issue, will see if .Set<T> could be replaced with general object list.
At the moment only solution would be to use separate Bulk ops instead of SaveChanges.

**Comment by borisdj** [comment]
Fixed with 6.4.0

Btw in SqlQueryBuilder file, call to `Set<T>()` is under condition _if InsertOrUpdateOrDelete_ method which is not used In SaveChanges.

**Comment by MelnikovVA** [comment]
Works perfectly, thank you so much!
