### ISSUE TITLE
Bulk instert/update/delete with PRIMARY KEY is numeric (10, 0)

### ISSUE THREAD

**Issue by ken-thoi** [borisdj/EFCore.BulkExtensions#749]
I try to bulk insert/update/delete table Sql Server with PRIMARY KEY IDENTITY (1, 1) is numeric (10, 0) type and hav  this issue, please help me resolve:

![Screenshot 2022-02-03 165423](https://user-images.githubusercontent.com/10280813/152319951-a8f88b7f-3e54-49ae-81d1-7561a5a50744.png)

2022-01-23 23:39:58.302 +07:00 [EROR] Cannot insert explicit value for identity column in table 'conf_rpt_appr' when IDENTITY_INSERT is set to OFF.
2022-01-23 23:39:58.324 +07:00 [EROR]    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRaw(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters)
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at EFCore.BulkExtensions.SqlBulkOperation.Merge(DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute(DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsert(DbContext context, Type entityType, IList`1 entities, BulkConfig bulkConfig, Action`1 progress)
   at APPLIC.EFCore.Generics.DomainRepository`3.BulkInsert(IList`1 entities, CancellationToken cancellationToken) in C:\Users\xuandt10\Source\Workspaces\IRS\10.Development\10.Source\58.RMD_API\RMD-External\APPLIC.EFCore\Generics\DomainRepository.cs:line 81
   at APPLIC.EFCore.Generics.GenericRepository`3.BulkInsert(IList`1 entities, CancellationToken cancellationToken) in C:\Users\xuandt10\Source\Workspaces\IRS\10.Development\10.Source\58.RMD_API\RMD-External\APPLIC.EFCore\Generics\GenericRepository.cs:line 76
   at APPLIC.API.Common.Controllers.ProcessController`3.Apr(Int32 reqId, ApproveStatusReq approveStatusReq) in C:\Users\xuandt10\Source\Workspaces\IRS\10.Development\10.Source\58.RMD_API\RMD-External\APPLIC.API.Common\Controllers\ProcessController.cs:line 401

**Comment by borisdj** [comment]
In _BulkConfig_ try set _SqlBulkCopyOptions_ with **KeepIdentity**.

**Comment by ken-thoi** [comment]
> 

Iam set SqlBulkCopyOptions = KeepIdentity, but this issue not work, pls help

**Comment by borisdj** [comment]
Can you write test where the issue would be reproducible.
