### ISSUE TITLE
Postsgres Error on character type on bulkUpdateAsync

### ISSUE THREAD

**Issue by JackBaloukjiBT** [borisdj/EFCore.BulkExtensions#750]
System.ArgumentException: A PostgreSQL type with the name character(1) was not found in the database
   at Npgsql.Internal.NpgsqlDatabaseInfo.GetPostgresTypeByName(String pgName)
   at Npgsql.TypeMapping.ConnectorTypeMapper.ResolveByDataTypeName(String typeName, Boolean throwOnError)
   at Npgsql.NpgsqlParameter.ResolveHandler(ConnectorTypeMapper typeMapper)
   
   I am currently on version 6.3.7

**Comment by borisdj** [comment]
Can you write test where the issue would be reproducible.

**Comment by JackBaloukjiBT** [comment]
I have a property with the following configuration in the entity:
entity.Property(e => e.StoreType)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength()
                .HasDefaultValueSql("('A')");

**Comment by JackBaloukjiBT** [comment]
@borisdj 

if (columnType.StartsWith("character varying")) // when MaxLength is defined
                            columnType = "character"; // 'character' is like 'string'
                            
 i guess if we just change the start with to character the issue should be resolved

**Comment by borisdj** [comment]
Try now with v6.3.9
If _StoreType_ doesn't have value you need to set BulkConfig with `PropertiesToExclude = new List<string> { "StoreType" }`
