### ISSUE TITLE
On Batch operation involving DateTime in Where clause, NpgsqlTimestampTypeMapping being used with non-Npgsql parameter type SqlParameter

### ISSUE THREAD

**Issue by xzxzxc** [borisdj/EFCore.BulkExtensions#758]
On EFCore.BulkExtensions 6.4.0 with Npgsql.EntityFrameworkCore.PostgreSQL 6.0.3, when I do something like this:

`await _ctx.Items.Where(r => r.DateCreated < date).BatchDeleteAsync();`
where date is a `DateTime`, the following happens:

```csharp
System.InvalidOperationException
Npgsql-specific type mapping NpgsqlTimestampTypeMapping being used with non-Npgsql parameter type SqlParameter
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping.NpgsqlTypeMapping.ConfigureParameter(DbParameter parameter)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.CreateParameter(DbCommand command, String name, Object value, Nullable`1 nullable)
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(DbCommand command, Object value)
   at EFCore.BulkExtensions.IQueryableExtensions.ToParametrizedSql(IQueryable query)
   at EFCore.BulkExtensions.BatchUtil.GetBatchSql(IQueryable query, DbContext context, Boolean isUpdate)
   at EFCore.BulkExtensions.BatchUtil.GetSqlDelete(IQueryable query, DbContext context)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.GetBatchDeleteArguments(IQueryable query)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchDeleteAsync(IQueryable query, CancellationToken cancellationToken)
```

**Comment by QsROg8320** [comment]
I have the same issue version 5.4.2

**Comment by jjxtra** [comment]
Still seeing issue in 6.5.2
