### ISSUE TITLE
BulkUpdateAsync With Shadow Property Throws Exception

### ISSUE THREAD

**Issue by dragos-rosca** [borisdj/EFCore.BulkExtensions#779]
Hello

I have this weird error when I try to `BulkUpdateAsync` an entity:

```
[11:34:09 ERR] An unhandled exception has occurred while executing the request.
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable1 source, Int32 index)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.GetDiscriminatorColumn(TableInfo tableInfo)   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InnerGetDataTable[T](DbContext context, Type& type, IList1 entities, TableInfo tableInfo)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.GetDataTable[T](DbContext context, Type type, IList1 entities, SqlBulkCopy sqlBulkCopy, TableInfo tableInfo)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList1 entities, TableInfo tableInfo, Action1 progress, CancellationToken cancellationToken, Boolean isAsync)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList1 entities, TableInfo tableInfo, Action1 progress, CancellationToken cancellationToken, Boolean isAsync)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList1 entities, TableInfo tableInfo, Action1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync[T](DbContext context, Type type, IList1 entities, TableInfo tableInfo, OperationType operationType, Action1 progress, CancellationToken cancellationToken, Boolean isAsync)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync[T](DbContext context, Type type, IList1 entities, TableInfo tableInfo, OperationType operationType, Action1 progress, CancellationToken cancellationToken, Boolean isAsync)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync[T](DbContext context, Type type, IList1 entities, TableInfo tableInfo, OperationType operationType, Action1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlBulkOperation.MergeAsync[T](DbContext context, Type type, IList1 entities, TableInfo tableInfo, OperationType operationType, Action1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IList1 entities, OperationType operationType, BulkConfig bulkConfig, Action1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.DbContextBulkTransactionSaveChanges.InvokeBulkMethod(DbContext context, List1 entities, Type entityType, String methodName, BulkConfig bulkConfig, Action1 progress, CancellationToken cancellationToken, Boolean isAsync)
   at EFCore.BulkExtensions.DbContextBulkTransactionSaveChanges.SaveChangesAsync(DbContext context, BulkConfig bulkConfig, Action1 progress, CancellationToken cancellationToken, Boolean isAsync)
   at EFCore.BulkExtensions.DbContextBulkTransactionSaveChanges.SaveChangesAsync(DbContext context, BulkConfig bulkConfig, Action1 progress, CancellationToken cancellationToken, Boolean isAsync)
   at EFCore.BulkExtensions.DbContextBulkTransactionSaveChanges.SaveChangesAsync(DbContext context, BulkConfig bulkConfig, Action1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IList1 entities, OperationType operationType, BulkConfig bulkConfig, Action1 progress, CancellationToken cancellationToken)
   at Notifier.Data.UnitOfWork.UserEfUow.<>c__DisplayClass4_0.<<SaveChangesAsync>b__0>d.MoveNext() in D:\Workspace\Projects\lsng_notifier\src\Notifier.Data\UnitOfWork\UserEfUow.cs:line 44
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c.<<ExecuteAsync>b__3_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass33_02.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func4 operation, Func4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func4 operation, Func4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func4 operation, Func4 verifySucceeded, CancellationToken cancellationToken)
   at Notifier.Data.UnitOfWork.UserEfUow.SaveChangesAsync(CancellationToken cancellationToken) in D:\Workspace\Projects\lsng_notifier\src\Notifier.Data\UnitOfWork\UserEfUow.cs:line 35
   at Notifier.Application.CommandHandlers.UserNotificationsHandler.Handle(MarkNotificationAsRead request, CancellationToken cancellationToken) in D:\Workspace\Projects\lsng_notifier\src\Notifier.Application\CommandHandlers\UserNotificationsHandler.cs:line 42
   at MediatR.Pipeline.RequestPostProcessorBehavior2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate1 next)
   at Notifier.Api.Controllers.NotifierController.MarkAsRead(MarkNotificationAsRead command) in D:\Workspace\Projects\lsng_notifier\src\Notifier.Api\Controllers\NotifierController.cs:line 39
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at NBB.MultiTenancy.AspNet.TenantMiddleware.Invoke(HttpContext context, ITenantIdentificationService tenantIdentificationService, ITenantContextAccessor tenantContextAccessor, ITenantRepository tenantRepository, IOptions1 tenancyOptions)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)
```

The problem seems to be caused by a shadow property.
My entity has configured in dbContext an extra column that is not represented by a property and it's marked as required. The error describes an out of range exception (an array index is going to far).

``` csharp
// The Entity class
public class Entity
 {
  public Guid Id { get; private set; }
  public String Column1 { get; private set; }

  private Entity() { }
  internal Entity(Guid id, String column1)
  {
   Id = id;
   Column1 = column1;
  }
 }
```

```csharp
// The configuration class
public class EntityConfiguration : IEntityTypeConfiguration<Entity>
{
 public void Configure(EntityTypeBuilder<Entity> builder)
 {
   builder.ToTable("Entity").HasKey(e => new { e.id });
   builder.Property<Guid>("NewColumn2").IsRequired(); // this has a default in the DB
 }
}
```

Now the weird part.
If I write:
```csharp
await _context.BulkUpdateAsync(modifiedEntity);
```
I get the error above and the DB has no change.

But if I write:
```csharp
await _context.BulkUpdateAsync(modifiedEntity, cfg =>
  {
      cfg.EnableShadowProperties = true;
  });
```
I still get the error but the DB has the change. 

It's cool that I have the changes in the DB but I don't want the error.

How am I suppose to handle this properly so I don't get any errors?

Thank you in advance!

Kind regards

**Comment by borisdj** [comment]
When _EnableShadowProperties_ set to True, test I have tried passes without exception.

**Comment by dragos-rosca** [comment]
Hello,

Thanks for checking and I apologies for the missing info.
I managed to produce the error because we are using the unit of work concept.
The code below is in continuation of the code I wrote above.

So while it is true that this code will pass without errors:
```csharp
var existingId = new Guid("5443E8BE-E11F-48B2-886C-C223EEF3FF1A");
var entity = new Entity(existingId, "new value for Column1");
await _context.BulkUpdateAsync(entity, cfg =>
  {
      cfg.EnableShadowProperties = true;
  });
```

The difference in my code (that I did not post before by mistake, sorry) is how I get the entity.
This code should throw the exception:
```csharp
var entity = await _context.Entities.SingleOrDefaultAsync(e=>e.Id == new Guid("5443E8BE-E11F-48B2-886C-C223EEF3FF1A"));
entity.Column1 =  "new value for Column1";

await unitOfWork.SaveChangesAsync(); // inside this I call "BulkUpdateAsync()"
```
And inside that `SaveChangesAsync()` I do something like this:

```csharp
var modifiedEntities = _context.ChangeTracker.Entries<Entity>()
            .Where(e => e.State == EntityState.Modified)
            .Select(e => e.Entity)
            .ToList();

await _context.BulkUpdateAsync(modifiedEntities, cfg =>
  {
      cfg.EnableShadowProperties = true;
  });
```
In the past I used to go through the `ChangeTracker` and reset the status to `EntityState.Unchanged` after `BulkUpdateAsync` but now I see it's taken care of.

I also just noticed that there is a `BulkSaveChangesAsync` and it works just fine, so I will use that one.

Sorry for all the trouble. The code works if used correctly but the error is there if you use it as described above.

Have a nice day!

Kind regards

**Comment by dragos-rosca** [comment]
Hello,

Yes, I see it's working. Due to old code I was using both `BulkUpdateAsync` and `BulkSaveChangesAsync` (a few lines down) so even when I was configuring the update, the `SaveChanges` was crashing.

I will use only the  `BulkSaveChangesAsync` because I see it's working (I think it wasn't in the past).

Thank you for the help.
Sorry for the trouble!

Have a great day!
