### ISSUE TITLE
SetOutputIdentity BulkInsert with function backed Computed Column

### ISSUE THREAD

**Issue by willisd2** [borisdj/EFCore.BulkExtensions#784]
I'm running into the same issue described here #54 but I'm using version 6.4.2. This other issue seems to be related as well. #93 

My Scenario: 
Running a BulkInsert against a table with a Computed Column that is backed by a user-defined function. SetOutputIdentity is true, and I've also added my column to the PropertiesToExclude list. I end up with the following error:

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Column 'inserted.Amount' cannot be referenced in the OUTPUT clause because the column definition contains a subquery or references a function that performs user or system data access. A function is assumed by default to perform data access if it is not schemabound. Consider removing the subquery or function from the column definition or removing the column from the OUTPUT clause.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRaw(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken, Boolean isAsync)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken, Boolean isAsync)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.Merge[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsert[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress, Type type)
```

I'm using a DB First approach. The generated entities don't have the `[DatabaseGenerated(DatabaseGeneratedOption.Computed)]` attribute above the computed column property, but the FluentApi has it as follows:
```
entity.Property(e => e.Amount).HasComputedColumnSql("([dbo].[ufn_CalculateAmount]([Id]))", false);
```

Adding the DatabaseGenerated attribute manually to the entity property didn't change the behavior either. I'm using Entity Framework Core 6.0.3 as well.

**Comment by willisd2** [comment]
I also have UseTempDB set to true

**Comment by borisdj** [comment]
This issue is limit of SqlServer, not of BulkOps.
Maybe try to alter function with **schemabound** as explained here:
[exacthelp_function-is-not-allowed-in-output](https://www.exacthelp.com/2012/04/function-is-not-allowed-in-output.html)
