### ISSUE TITLE
NullReferenceException for v6.4.3 with SqlServer

### ISSUE THREAD

**Issue by sommmen** [borisdj/EFCore.BulkExtensions#796]
Hiya @borisdj ,

I'm getting a `NullReferenceException` for the following code, which does work in v6.4.2 and in versions before, but not in the latest v6.4.3

``` csharp
private async Task DeleteEntities<TEntity>(string name, List<TEntity> entities,
    IDisposableBulkRepository<TEntity> bulkRepository,
    CancellationToken cancellationToken = default)
    where TEntity : class, IAppLog, new()
{
    Logger.LogInformation("{name} About to delete {EntityCount} entities", name, entities.Count);

    var sw = Stopwatch.StartNew();
    var bulkConfig = new BulkConfig
    {
        // Should help cleaning up temp tables - see https://github.com/borisdj/EFCore.BulkExtensions/issues/202
        UseTempDB = true,

        // Cause its cool.
        CalculateStats = true,
    };

    var bulkProgress = Logger.WriteProgressBar($"{name} Bulk {entities.Count}");

    await using var tran = await bulkRepository.BeginTransactionAsync(cancellationToken);
    await bulkRepository.BulkDeleteAsync(entities, bulkConfig, a => bulkProgress.SetValue((double)a * 100.0d),
        cancellationToken: cancellationToken);
    await tran.CommitAsync(cancellationToken);

    Logger.LogInformation("{name} Bulk {deleted} deleted for entity {EntityName} in {Elapsed}", name,
        bulkConfig.StatsInfo?.StatsNumberDeleted, typeof(TEntity).Name, sw.StopElapsed());
}
```

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=EFCore.BulkExtensions
  StackTrace:
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.GetSqlBulkCopy(SqlConnection sqlConnection, IDbContextTransaction transaction, BulkConfig config)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<InsertAsync>d__2`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<InsertAsync>d__2`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<InsertAsync>d__1`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__5`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__5`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__4`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at EFCore.BulkExtensions.SqlBulkOperation.<MergeAsync>d__5`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at EFCore.BulkExtensions.DbContextBulkTransaction.<ExecuteAsync>d__1`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at [REDACTED].<DeleteEntities>d__8`1.MoveNext() in [REDACTED].cs:line 145

  This exception was originally thrown at this call stack:
    EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.GetSqlBulkCopy(Microsoft.Data.SqlClient.SqlConnection, Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction, EFCore.BulkExtensions.BulkConfig)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
    ...
    [Call Stack Truncated]
```

Entity:
``` csharp
public class AppLog : IAppLog
{
    public int Id { get; set; }
    public string Message { get; set; }
    public string MessageTemplate { get; set; }
    public string Level { get; set; }
    public DateTime? TimeStamp { get; set; }
    public string Exception { get; set; }
    public string Properties { get; set; }
}
```

**Comment by sommmen** [comment]
Was this perhaps already fixes in  https://github.com/borisdj/EFCore.BulkExtensions/commit/abe6ca5ed73634bca19f47f8335a736d4ca5d119 but not yet released?

**Comment by borisdj** [comment]
It is, as exception is about _GetSqlBulkCopy_.

**Comment by borisdj** [comment]
try v6.4.4
