### ISSUE TITLE
Connection is not opened - BulkMerge

### ISSUE THREAD

**Issue by Feoni4** [borisdj/EFCore.BulkExtensions#8]
In EFCore.BulkExtensions.TableInfo.CheckHasIdentity there are **conn.OpenAsync()**. I think you have to **await** here, or use **sync** method

```
System.InvalidOperationException: ExecuteReader requires an open and available Connection. The connection's current state is connecting.
   at System.Data.SqlClient.SqlConnection.GetOpenTdsConnection(String method)
   at System.Data.SqlClient.SqlConnection.ValidateConnectionForExecute(String method, SqlCommand command)
   at System.Data.SqlClient.SqlCommand.ValidateCommand(Boolean async, String method)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at EFCore.BulkExtensions.TableInfo.CheckHasIdentity(DbContext context) in D:\Projects\! GitHub\EFCore.BulkExtensions\EFCore.BulkExtensions\TableInfo.cs:line 61
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType) in D:\Projects\! GitHub\EFCore.BulkExtensions\EFCore.BulkExtensions\SqlBulkOperation.cs:line 49
   at Auto1.Prices.Repositories.ProductRepository.InsertOrUpdate(IEnumerable`1 entities) in D:\Projects\Auto1.Prices\Auto1.Prices\Repositories\ProductRepository.cs:line 55
   at Auto1.Prices.Controllers.ExchangeController.UpdateProducts(ExchangeProduct[] products) in D:\Projects\Auto1.Prices\Auto1.Prices\Controllers\ExcangeController.cs:line 49
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()    at System.Data.SqlClient.SqlConnection.GetOpenTdsConnection(String method)
   at System.Data.SqlClient.SqlConnection.ValidateConnectionForExecute(String method, SqlCommand command)
   at System.Data.SqlClient.SqlCommand.ValidateCommand(Boolean async, String method)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at EFCore.BulkExtensions.TableInfo.CheckHasIdentity(DbContext context) in D:\Projects\! GitHub\EFCore.BulkExtensions\EFCore.BulkExtensions\TableInfo.cs:line 61
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType) in D:\Projects\! GitHub\EFCore.BulkExtensions\EFCore.BulkExtensions\SqlBulkOperation.cs:line 49
   at Auto1.Prices.Repositories.ProductRepository.InsertOrUpdate(IEnumerable`1 entities) in D:\Projects\Auto1.Prices\Auto1.Prices\Repositories\ProductRepository.cs:line 55
   at Auto1.Prices.Controllers.ExchangeController.UpdateProducts(ExchangeProduct[] products) in D:\Projects\Auto1.Prices\Auto1.Prices\Controllers\ExcangeController.cs:line 49
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
```

**Comment by borisdj** [comment]
I will change this to _Open()_ only.
And to mention that I have plans to add support for fully Asynchronous Bulk operations.

**Comment by borisdj** [comment]
Merged

**Comment by borisdj** [comment]
Support for **Async** operations is now added.
