### ISSUE TITLE
Did EFCore.BulkExtensions5.4.2 Support PostgreSQL ?

### ISSUE THREAD

**Issue by aprilyush** [borisdj/EFCore.BulkExtensions#803]
Version: EFCore.BulkExtensions 5.4.2 .Net 5
DataBase:  PostgreSQL 11.1 on x86_64-pc-mingw64, compiled by gcc.exe (Rev5, Built by MSYS2 project) 4.9.2, 64-bit
```
List<SysLogEntity> logs=new List<SysLogEntity>();
  SysLogEntity logModel = new SysLogEntity();
                        logModel.LogSummary = log.LogSummary;
                        logModel.LogMessage = log.LogMessage;
                        logModel.LogType = log.LogType;
                        logModel.LogTime = log.LogTime;
                        logs.Add(logModel);
   _dbContext.BulkInsert(logs);
```
Exception:
```  
Unable to cast object of type 'Npgsql.NpgsqlConnection' to type 'Microsoft.Data.SqlClient.SqlConnection'.£»  
 at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken, Boolean isAsync)
         at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken, Boolean isAsync)
         at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.Insert[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress)
         at EFCore.BulkExtensions.SqlBulkOperation.Insert[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress)
         at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
         at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsert[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress, Type type)
         at DeviceManage.Server.API.Jobs.LogHostedService.DoWork()
```

**Comment by borisdj** [comment]
No, PG supported was added in 6+.
Will added a comment about that in the ReadMe.
