### ISSUE TITLE
Postgres BatchUpdateAsync TagWith not working

### ISSUE THREAD

**Issue by SirOrel** [borisdj/EFCore.BulkExtensions#844]
Executing such update triggers an exception:
```csharp
await _DbContext.Users.TagWith("My tag").Where(user => user.Id == userId).BatchUpdateAsync(user => new User { LastLoginDate = DateTime.UtcNow });
```
```
System.ArgumentOutOfRangeException: Length cannot be less
 than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at EFCore.BulkExtensions.SQLAdapters.PostgreSql.SqlQueryBuilderPostgreSql.RestructureForBatch(String sql, Boolean isDelete)
   at EFCore.BulkExtensions.BatchUtil.GetSqlUpdate[T](IQueryable`1 query, DbContext context, Type type, Expression`1 expression)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.GetBatchUpdateArguments[T](IQueryable`1 query, Object updateValues, List`1 updateColumns, Expression`1 updateExpression, Type type)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchUpdateAsync[T](IQueryable`1 query, Expression`1 updateExpression, Type type, CancellationToken cancellationToken)
```
Without TagWith everything works fine.

**Comment by borisdj** [comment]
_TagWith_ is not supported.

**Comment by SirOrel** [comment]
@borisdj will it be supported?

**Comment by borisdj** [comment]
Will try to add it, but can't put timeframe on it.

**Comment by borisdj** [comment]
Since Batch ops as of EF7 are now natively supported with _ExecuteUpdate_/_ExecuteDelete_ Batch extensione will become deprecated here. Focus is only on BULK methods which is the main purpose of the lib.
