### ISSUE TITLE
Version 5.6.1 produces Npgsql.PostgresException (0x80004005): 42601: syntax error at end of input

### ISSUE THREAD

**Issue by Syzuna** [borisdj/EFCore.BulkExtensions#847]
Hello.

After upgrading to 5.6.1 I started to get Npgsql.PostgresException exceptions when using BulkExtensions.

Stacktrace:

```
Npgsql.PostgresException (0x80004005): 42601: syntax error at end of input

      POSITION: 362
         at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|213_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRawAsync(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters, CancellationToken cancellationToken)
         at EFCore.BulkExtensions.SQLAdapters.PostgreSql.PostgreSqlAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
         at EFCore.BulkExtensions.SQLAdapters.PostgreSql.PostgreSqlAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
         at EFCore.BulkExtensions.SQLAdapters.PostgreSql.PostgreSqlAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
         at EFCore.BulkExtensions.SqlBulkOperation.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
         at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
```
```
        Exception data:
          Severity: ERROR
          SqlState: 42601
          MessageText: syntax error at end of input
          Position: 362
          File: scan.l
          Line: 1168
          Routine: scanner_yyerror
```

I downgraded to 6.5.0 for now

**Comment by borisdj** [comment]
v6.5.1 was added support for PropertiesToExcludeOnUpdate.
Can you write example with test where the issue would be reproducible.

**Comment by RebelEcheveria** [comment]
@borisdj

I checked this out a while back when I ran into the issue as well - the problem occurs when you're using a naming strategy on the database that results in the database column names differing from the POCO property names.

The GetColumnList method within the SqlQueryBuilderPostgreSql.cs file returns the names of the columns as they appear in the database, but the code within the MergeTable method of the same file looks at the POCO property names that it has stored as keys in the "tableInfo.PropertyColumnNamesUpdateDict" dictionary when it's determining which properties to include in the SQL string. The result is that there may be no overlap when the database column names differ from the POCO property names and it can generate invalid SQL that ends with "DO UPDATE SET ".

@MatiKloster should be able to fix this issue fairly easily

Thank you both for your awesome work

**Comment by Syzuna** [comment]
I am sorry for not getting back on it in over a week but the last days have been busy as hell and the weather was way too hot.
Thanks Rebel for doing a more in depth look!

**Comment by MatiKloster** [comment]
> @RebelEcheveria @MatiKloster since PropertyColumnNamesUpdateDict maps POCO property names to database column names, wouldn't it suffice to check the existence of values instead of keys in PropertyColumnNamesUpdateDict?
> 
> [SqlQueryBuilderPostgreSql.cs:92](https://github.com/borisdj/EFCore.BulkExtensions/blob/f8009e4aba252bcf711e4e0c3134b719cf705fc1/EFCore.BulkExtensions/SQLAdapters/PostgreSql/SqlQueryBuilderPostgreSql.cs#L92)
> 
> ```
> CURRENT:
> var columnsToUpdate = columnsListEquals.Where(c => tableInfo.PropertyColumnNamesUpdateDict.ContainsKey(c)).ToList();
> 
> FIXED:
> var columnsToUpdate = columnsListEquals.Where(c => tableInfo.PropertyColumnNamesUpdateDict.ContainsValue(c)).ToList();
> ```
> 
> [Pull request](https://github.com/borisdj/EFCore.BulkExtensions/pull/870)

Sorry... I've been swamped as hell these days.

Looks good!

**Comment by alexanderlunden** [comment]
@Syzuna Will you please re-test your code with the latest version that includes a fix for this bug, and if it works close the issue?

**Comment by borisdj** [comment]
Published v.6.5.3
