### ISSUE TITLE
BulkInsertOrUpdateAsync with complex Model (Generic inheritance)

### ISSUE THREAD

**Issue by ciacco85** [borisdj/EFCore.BulkExtensions#863]
When i execute BulkInsertOrUpdateAsync with a list of Permission
```cs
public partial class Permission : Permission<Area>
    {
        public Permission()
        {            
            RolePermissions = new HashSet<RolePermission<Area>>();
        }
        public string Name { get; set; }
        public ICollection<PermissionModule> PermissionModules { get; set; }       
    }
public abstract class Permission<T> : GuidRowVersionModelBase where T : Area<T>
    {
        public string Code { get; set; }
        public string Description { get; set; }
        public ICollection<RolePermission<T>> RolePermissions { get; set; }
    }
public abstract class Area<T> : GuidRowVersionModelBase where T : Area<T>
    {
        public string Name { get; set; }
        public Guid? ParentAreaId { get; set; }
        public T ParentArea { get; set; }
        public ICollection<T> ChildrenAreas { get; set; }
        public ICollection<UserRoleArea<T>> UserRoleAreas { get; set; }
    }
public class GuidRowVersionModelBase : RowVersionModelBase<Guid>, IGuidRowVersionModelBase, IRowVersionModelBase<Guid>, IModelBase<Guid>
    {
    }
public class RowVersionModelBase<ID> : ModelBase<ID>, IRowVersionModelBase<ID>, IModelBase<ID> where ID : struct
    {
        public byte[] RowVersion { get; set; }
    }
public class ModelBase<ID> : IModelBase<ID> where ID : struct
    {
        public ID Id { get; set; }
        public bool IsDeleted { get; set; }
    }
```
I get this error
`
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.GetDiscriminatorColumn(TableInfo tableInfo)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InnerGetDataTable[T](DbContext context, Type& type, IList`1 entities, TableInfo tableInfo)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.GetDataTable[T](DbContext context, Type type, IList`1 entities, SqlBulkCopy sqlBulkCopy, TableInfo tableInfo)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlBulkOperation.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
   at EFS.Seed.Core.SeedDataClass.SeedPermissions() in C:\ProgeRepos\PROGE_3FS\3FS\EFS.Seed.Core\SeedDataClass.Permissions.cs:line 29
`
I've focused my analysis on the inheritance of the model, since the output table is really simple
![image](https://user-images.githubusercontent.com/4320587/175576009-3ee2794a-b7a2-41d6-969c-97ff46ee69a1.png)
And my idea is that the bulk insert doesn't manage such scenario

**Comment by ciacco85** [comment]
It was working with 6.0.0

**Comment by borisdj** [comment]
Can you write entire test where the issue would be reproducible, also try to simplify it to minimal structure required for issue to occur.
