### ISSUE TITLE
PostGre - out of range exception during bulkRead 

### ISSUE THREAD

**Issue by Maleaume** [borisdj/EFCore.BulkExtensions#871]
in [TableInfo.cs](https://github.com/borisdj/EFCore.BulkExtensions/blob/master/EFCore.BulkExtensions/TableInfo.cs) we can see that (line 826)

```
 for (int i = 0; i < NumberOfEntities; i++)
  {
....
   if (existingEntity == null && isPostgreSQL)
   {
      existingEntity = existingEntities[i]; // TODO check if BinaryImport with COPY on Postgres preserves order
    }
} ```

you have an index out of range exception when the `existingEntities `collection is smaller that `entities` one. 

**Use Case :**

Take a table with 5 elements.
Create bulkRead on 6 elements with one  key that does not exist
```
entities.Count()  = 6
existingEntities.Count() = 5

the main loop is on entities collection
and if mapping is not found (that is normal) this code is call for Postgrey only 
```
 if (existingEntity == null && isPostgreSQL)
  {
      existingEntity = existingEntities[i]; // TODO check if BinaryImport with COPY on Postgres preserves order
  }
``` 
 **Exception** 
` "Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')"   `

 
```
Stack Trace
` at System.Collections.Generic.List`1.get_Item(Int32 index)
   at EFCore.BulkExtensions.TableInfo.UpdateReadEntities[T](IList`1 entities, IList`1 existingEntities, DbContext context)
   at EFCore.BulkExtensions.SQLAdapters.PostgreSql.PostgreSqlAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SQLAdapters.PostgreSql.PostgreSqlAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SQLAdapters.PostgreSql.PostgreSqlAdapter.ReadAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SQLAdapters.PostgreSql.PostgreSqlAdapter.Read[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress)
   at EFCore.BulkExtensions.SqlBulkOperation.Read[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkRead[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress, Type type)`

**Comment by maximebono** [comment]
Hi,

Same problem here. I wrote a little test to explain it.

**In class "EFCoreBulkTest" :**
```
[Theory]
[InlineData(DbServer.PostgreSQL)]
[InlineData(DbServer.SQLite)]
[InlineData(DbServer.SQLServer)]
public void ReadTestPostgreSql(DbServer dbServer)
{
	ContextUtil.DbServer = dbServer;

	using var context = new TestContext(ContextUtil.GetOptions());

	if (dbServer == DbServer.PostgreSQL)
	{
		context.Database.ExecuteSqlRaw($@"DELETE FROM ""{nameof(Item)}""");
		context.Database.ExecuteSqlRaw($@"ALTER SEQUENCE ""{nameof(Item)}_{nameof(Item.ItemId)}_seq"" RESTART WITH 1");

		context.Database.ExecuteSqlRaw($@"DELETE FROM ""{nameof(Box)}""");
		context.Database.ExecuteSqlRaw($@"ALTER SEQUENCE ""{nameof(Box)}_{nameof(Box.BoxId)}_seq"" RESTART WITH 1");

		context.Database.ExecuteSqlRaw($@"DELETE FROM ""{nameof(UserRole)}""");
	}

	var readConfig = new BulkConfig { UpdateByProperties = new List<string> { nameof(Item.Name) } };
	var items = new List<Item>() { new Item { Name = "Items test" } };
	context.BulkRead(items, readConfig);
	Assert.Single(items);

	Assert.Equal(0, items.FirstOrDefault()?.ItemId);
	Assert.Equal("Items test", items.FirstOrDefault()?.Name);
}
```

**With the following result :** 
  ```
ReadTestPostgreSql (3 tests) [0:12.763] Failed: One or more child tests failed: 1 test failed
   ReadTestPostgreSql(dbServer: PostgreSQL) [0:00.830] Failed: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
System.ArgumentOutOfRangeException
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at EFCore.BulkExtensions.TableInfo.UpdateReadEntities[T](IList`1 entities, IList`1 existingEntities, DbContext context) in C:\DEV\PERSO\EFCore.BulkExtensions\EFCore.BulkExtensions\TableInfo.cs:line 801
   at EFCore.BulkExtensions.SQLAdapters.PostgreSql.PostgreSqlAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken) in C:\DEV\PERSO\EFCore.BulkExtensions\EFCore.BulkExtensions\SQLAdapters\PostgreSql\PostgreSqlAdapter.cs:line 0
   at EFCore.BulkExtensions.SQLAdapters.PostgreSql.PostgreSqlAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken) in C:\DEV\PERSO\EFCore.BulkExtensions\EFCore.BulkExtensions\SQLAdapters\PostgreSql\PostgreSqlAdapter.cs:line 276
   at EFCore.BulkExtensions.SQLAdapters.PostgreSql.PostgreSqlAdapter.ReadAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken) in C:\DEV\PERSO\EFCore.BulkExtensions\EFCore.BulkExtensions\SQLAdapters\PostgreSql\PostgreSqlAdapter.cs:line 289
   at EFCore.BulkExtensions.SQLAdapters.PostgreSql.PostgreSqlAdapter.Read[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress) in C:\DEV\PERSO\EFCore.BulkExtensions\EFCore.BulkExtensions\SQLAdapters\PostgreSql\PostgreSqlAdapter.cs:line 281
   at EFCore.BulkExtensions.SqlBulkOperation.Read[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress) in C:\DEV\PERSO\EFCore.BulkExtensions\EFCore.BulkExtensions\SqlBulkOperation.cs:line 84
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress) in C:\DEV\PERSO\EFCore.BulkExtensions\EFCore.BulkExtensions\DbContextBulkTransaction.cs:line 44
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkRead[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress, Type type) in C:\DEV\PERSO\EFCore.BulkExtensions\EFCore.BulkExtensions\DbContextBulkExtensions.cs:line 365
   at EFCore.BulkExtensions.Tests.EFCoreBulkTest.ReadTestPostgreSql(DbServer dbServer) in C:\DEV\PERSO\EFCore.BulkExtensions\EFCore.BulkExtensions.Tests\EFCoreBulkTest.cs:line 70


   ReadTestPostgreSql(dbServer: SQLServer) [0:04.893] Success
   ReadTestPostgreSql(dbServer: SQLite) [0:07.039] Success

```

**Comment by borisdj** [comment]
Should be fixed with v6.5.3
