### ISSUE TITLE
SQlite BulkInsertOrUpdate with options.IncludeGraph = true

### ISSUE THREAD

**Issue by Bondarenko1990** [borisdj/EFCore.BulkExtensions#892]
I get error in my Desktop App when I use BulkInsertOrUpdate with options.IncludeGraph = true
`context.BulkInsertOrUpdate<T>(new List<T> { entity }, options => options.IncludeGraph = true);
                        await transaction.CommitAsync();`
Error message 
`Sqlite is not currently supported due to its BulkInsert implementation.`
StackTrace
`at EFCore.BulkExtensions.DbContextBulkTransactionGraphUtil.<ExecuteWithGraphAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EFCore.BulkExtensions.DbContextBulkTransactionGraphUtil.ExecuteWithGraph(DbContext context, IEnumerable`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsertOrUpdate[T](DbContext context, IList`1 entities, Action`1 bulkAction, Action`1 progress, Type type)`
 I want update child entites when I update parent entity. How can I do it?

**Comment by borisdj** [comment]
You need separate Bulk calls.
Take a look at ReadMe segment _Example of SetOutputIdentity with parent-child FK related tables_ **Option 1**.
