### ISSUE TITLE
Could not load type IBinarySerialize from Microsoft.Data.SqlClient 5.0

### ISSUE THREAD

**Issue by dahovey** [borisdj/EFCore.BulkExtensions#934]
When using `EFCore.BulkExtensions` version `6.5.6` and also including package reference to `Microsoft.Data.SqlClient` 5.0.0 the below exception is generated.

```
tests-integration-tests-1  |    System.TypeLoadException : Could not load type 'Microsoft.Data.SqlClient.Server.IBinarySerialize' from assembly 'Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5'.
tests-integration-tests-1  |   Stack Trace:
tests-integration-tests-1  |      at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InnerGetDataTable[T](DbContext context, Type& type, IList`1 entities, TableInfo tableInfo)
tests-integration-tests-1  |    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.GetDataTable[T](DbContext context, Type type, IList`1 entities, SqlBulkCopy sqlBulkCopy, TableInfo tableInfo)
tests-integration-tests-1  |    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
tests-integration-tests-1  |    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
tests-integration-tests-1  |    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
tests-integration-tests-1  |    at EFCore.BulkExtensions.SqlBulkOperation.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
tests-integration-tests-1  |    at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
tests-integration-tests-1  |    at ...
```

The above exception occurs when calling

```csharp
await dbContext.BulkInsertAsync(companies, new BulkConfig() { });
```

Running inside Docker container based on `FROM mcr.microsoft.com/dotnet/sdk:6.0`

**Comment by dahovey** [comment]
Downgrading `Microsoft.Data.SqlClient` to 4.1.0 doesn't throw exception as above.

Originally I thought the exception only occurred within Docker container, but that is incorrect. Occurs regardless of environment or architecture.

**Comment by borisdj** [comment]
EFCore v6 is using SqlClient 2.1.4, only with EF core 7 will the newer versions be used.

**Comment by dahovey** [comment]
Thanks for quick answer. Good to know.
