### ISSUE TITLE
`Received an invalid column length from the bcp client for colid` with `DbContext.BulkInsertAsync` but only when `SetOutputIdentity` is set to true

### ISSUE THREAD

**Issue by benm-eras** [borisdj/EFCore.BulkExtensions#958]
When trying to use `DbContext.BulkInsertAsync(entities, new BulkConfig() { SetOutputIdentity = true })` I am now getting an exception with the following message `SqlException (0x80131904): Received an invalid column length from the bcp client for colid 11.` (full stack trace below). 

If I change `SetOutputIdentity = false` it runs just fine, though I need to run another query to get the IDs for the inserted entities which I would like to avoid. 

This was working previously and has just stopped working. I had updated some nuget packages, but I have also reverted to the old versions with no effect. 

I see from other issues (#449) that I might expect to get detailed information about the problematic columns in the exception message, but I do not.

Its a .NET 6 console project, SDK 6.0.401 with EFCore.BulkExtensions 6.5.6 and Microsoft.EntityFrameworkCore 6.0.9.

```
Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): Received an invalid column length from the bcp client for colid 11.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlBulkCopy.RunParser(BulkCopySimpleResultSet bulkCopyHandler)
   at Microsoft.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinuedOnSuccess(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at Microsoft.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
--- End of stack trace from previous location ---
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SqlBulkOperation.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
``` 

## Update
Going through all our commits using trial and error I narrowed it down to a default value being set on a concurrency stamp property defined on an entity base class:

```
public abstract class AccountBase
{
    [Timestamp]
    public byte[] ConcurrencyStamp { get; set; } = Guid.NewGuid().ToByteArray();
}
```

Removing the default value (it was added to facilitate tests using Sqlite that doesn't support row versioning by marking properties with `[Timestamp]`) resolved the issue. However:

- I am still not sure why it worked when not using the bulk extensions (standard Entity Framework inserts)
- Nor why it only caused problems when `SetOutputIdentity` was set to `true`
- Or why I did not get detailed information in the exception message to help nail this down

**Comment by borisdj** [comment]
Very unusual case, that happens only with combination of all those elements.
Great debugging.
Can confirm the issue, but still haven't found a way to exclude it automatically.

**Comment by borisdj** [comment]
Fixed now with latest v.

**Comment by Saibamen** [comment]
@borisdj: Can you please add `#` to before issue number (#958) to your commits/Pull Requests etc, so everything will be linked?

For example here: https://github.com/borisdj/EFCore.BulkExtensions/commit/2264edada635cd9ef6923831e0d7f67acb8552b7

I was searching for any changelog, and even if I checked recent commits it is hard to navigate between issues and commits
