### ISSUE TITLE
Postgres - BulkInsert -  cannot insert into column "id"

### ISSUE THREAD

**Issue by E-PressSend** [borisdj/EFCore.BulkExtensions#969]
Hi There, 

I'm facing an issue when I'm trying to insert an object with a classic parent-child [1:M] relationship.
When I BulkSavechanges I keep getting the error message `cannot insert into column "id"` where "id" is the PK (IDENTITY) column of the child entity.

Child entities (ICollection of ExAggTranItem) can be  quite a log (>400k) so I'd like to use Bulk

Can you please quickly look at this code and let me know what is wrong:

```
await strategy.ExecuteAsync(async () =>
            {
                var bulkConfig = new BulkConfig { SetOutputIdentity = true, PreserveInsertOrder = true };
                await using var transaction = await this.snapzlDb.Database.BeginTransactionAsync();
     //data is of type ExAggTrans, child is of type  ICollection of ExAggTranItem
                this.snapzlDb.BulkInsertOrUpdate(new List<ExAggTrans>() { data }, bulkConfig);
                
                await transaction.CommitAsync();
                watch.Stop();
                var elapsedSecs = watch.ElapsedMilliseconds / 1000;
                this.logger.LogInformation("Saved Aggregated data for tenant {tenant} in {time}s", data.TenantId, elapsedSecs);

            });
```

this code also doesn't work and fails exactly with the same error message:
```

await strategy.ExecuteAsync(async () =>
            {
                var bulkConfig = new BulkConfig { SetOutputIdentity = true, PreserveInsertOrder = true };

                await using var transaction = await this.snapzlDb.Database.BeginTransactionAsync();
                //data is of type ExAggTrans, child is of type  ICollection<ExAggTranItem>
                var agg = await this.snapzlDb.ExAggTrans.AddAsync(data);
                this.snapzlDb.BulkSaveChanges(bulkConfig);

                await transaction.CommitAsync();
                watch.Stop();
                var elapsedSecs = watch.ElapsedMilliseconds / 1000;
                this.logger.LogInformation("Saved Aggregated data for tenant {tenant} in {time}s", data.TenantId, elapsedSecs);

            });

```
this is the class definition:
```
    public partial class ExAggTrans
    {
        public ExAggTrans()
        {
            ExAggTranItem = new HashSet<ExAggTranItem>();
        }

        public string TenantId { get; set; }
        public int ItemsCount { get; set; }
        public bool? IsProgression { get; set; }
        public bool? IsCategory { get; set; }
        public DateTime LastUpdated { get; set; }

        [Key]
        public int Id { get; set; }

        public virtual Tenants Tenant { get; set; }
        public virtual ICollection<ExAggTranItem> ExAggTranItem { get; set; }
    }

    public partial class ExAggTranItem
    {
        public int Id { get; set; }
        public int FinPeriod { get; set; }
        public int YearMonthPeriod { get; set; }
        public decimal? AmountSum { get; set; }
        public int? ItemsCount { get; set; }
        public string ExternalAccountId { get; set; }
        public string ExternalCategoryItemId { get; set; }
        public int ExAggTransId { get; set; }

        public virtual ExAggTrans ExAggTrans { get; set; }
        public virtual ExAccount ExternalAccount { get; set; }
        public virtual ExCatItem ExternalCategoryItem { get; set; }
    }
```

error message:
```

[2022-10-08T02:02:14.088Z] Npgsql.PostgresException (0x80004005): 428C9: cannot insert into column "id"
[2022-10-08T02:02:14.088Z] 
[2022-10-08T02:02:14.088Z] DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
[2022-10-08T02:02:14.088Z]    at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
[2022-10-08T02:02:14.088Z]    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
[2022-10-08T02:02:14.088Z]    at Npgsql.NpgsqlDataReader.NextResult()
[2022-10-08T02:02:14.088Z]    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
[2022-10-08T02:02:14.088Z]    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
[2022-10-08T02:02:14.088Z]    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
[2022-10-08T02:02:14.088Z]    at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
[2022-10-08T02:02:14.088Z]    at System.Data.Common.DbCommand.ExecuteReader()
[2022-10-08T02:02:14.088Z]    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
[2022-10-08T02:02:14.088Z]    at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
[2022-10-08T02:02:14.089Z]    at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__19_0(DbContext _, Enumerator enumerator)
[2022-10-08T02:02:14.089Z]    at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
[2022-10-08T02:02:14.089Z]    at Microsoft.EntityFrameworkCore.Query.Internal.FromSqlQueryingEnumerable`1.Enumerator.MoveNext()
[2022-10-08T02:02:14.089Z]   Exception data:
[2022-10-08T02:02:14.089Z]     Severity: ERROR
[2022-10-08T02:02:14.089Z]     SqlState: 428C9
[2022-10-08T02:02:14.089Z]     MessageText: cannot insert into column "id"
[2022-10-08T02:02:14.089Z]     Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
[2022-10-08T02:02:14.089Z]     Hint: Use OVERRIDING SYSTEM VALUE to override.
[2022-10-08T02:02:14.089Z]     File: rewriteHandler.c
[2022-10-08T02:02:14.089Z]     Line: 843
[2022-10-08T02:02:14.089Z]     Routine: rewriteTargetListIU
[2022-10-08T02:02:14.089Z] Npgsql: 428C9: cannot insert into column "id"
[2022-10-08T02:02:14.089Z] 
[2022-10-08T02:02:14.089Z] DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
```

**Comment by E-PressSend** [comment]
further to that, this is also what I see in the log:

```
[2022-10-08T06:50:35.200Z] Failed executing DbCommand (21ms) [Parameters=[], CommandType='Text', CommandTimeout='600']
[2022-10-08T06:50:35.200Z] INSERT INTO "ExAggTrans" ("id", "IsCategory", "IsProgression", "itemsCount", "lastUpdated", "tenantId") (SELECT "id", "IsCategory", "IsProgression", "itemsCount", "lastUpdated", "tenantId" FROM "ExAggTransTemp49efae72") ON CONFLICT ("id") DO UPDATE SET "IsCategory" = EXCLUDED."IsCategory", "IsProgression" = EXCLUDED."IsProgression", "itemsCount" = EXCLUDED."itemsCount", "lastUpdated" = EXCLUDED."lastUpdated", "tenantId" = EXCLUDED."tenantId" RETURNING "id", "IsCategory", "IsProgression", "itemsCount", "lastUpdated", "tenantId";
```

No matter what option I set, it always tries to do an UPDATE on CONFLICT.

**Comment by E-PressSend** [comment]
nothing here? any help would be appreciated.

**Comment by brunocasarotti** [comment]
I am having the same problem with many versions

**Comment by borisdj** [comment]
Try again with the latest version.
If still having problems check Test _SaveChangesTest_ and alter it to make issue reproducible.
